---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.networking.k8s.io/backendtlspolicy_v1alpha3.json
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: desktop-backend-tls
spec:
  targetRefs:
    - group: ''
      kind: Service
      name: desktop
      sectionName: https
  validation:
    caCertificateRefs:
      - name: rnatr-internal-ca
        group: ''
        kind: Secret
    hostname: desktop.thin-client.svc.cluster.local
