---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: desktop
spec:
  chartRef:
    kind: OCIRepository
    name: desktop
  interval: 1h
  values:
    controllers:
      desktop:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/kasmweb/desktop
              tag: 1.15.0
            env:
              VNC_PW: password
              TZ: America/New_York
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
              seccompProfile:
                type: Unconfined
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      nodeSelector:
        kubernetes.io/arch: amd64
    service:
      app:
        ports:
          https:
            appProtocol: https
            port: 6901
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - "desktop.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 6901
    persistence:
      config:
        existingClaim: desktop
        globalMounts:
          - path: /home/kasm-user
      shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 512Mi
        globalMounts:
          - path: /dev/shm
      tls:
        type: custom
        volumeSpec:
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: rnatr-internal-ca
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/dns-names: desktop.thin-client.svc.cluster.local
        advancedMounts:
          desktop:
            app:
              - path: /etc/ssl/certs/ssl-cert-snakeoil.pem
                subPath: tls.crt
                readOnly: true
              - path: /etc/ssl/private/ssl-cert-snakeoil.key
                subPath: tls.key
                readOnly: true
