apiVersion: v1
kind: Secret
metadata:
    name: wazuh-secret
type: opaque
stringData:
    #ENC[AES256_GCM,data:A51AWs317kZXtER6,iv:+T8e+9owKWNzYiwkwBhSTki+jslhYuGWaKxqlvDjiVc=,tag:hm0AHDY+Iia2ZBgwClOuiA==,type:comment]
    INDEXER_USERNAME: ENC[AES256_GCM,data:lx6uhHg=,iv:CzVhvu0rJGhcZuDqud6VdI21xVNA4EGq18xURN+luts=,tag:DjkX7Ft00b6IiwbeBaXEOg==,type:str]
    INDEXER_PASSWORD: ENC[AES256_GCM,data:TE4Bv9Ioi+m9+6BLU0WkBWjbQ5lrbxkN1Ie9MmAjvEM=,iv:cYTwnj/J10UuWUUTkzzRQHr6RnGDhah8B7OUNHqx67A=,tag:ctIQ3UND/vH8QEVyauSEOw==,type:str]
    INDEXER_PASSWORD_HASH: ENC[AES256_GCM,data:j5ieTwHCnc9PHd488p89gAYjxVv45AwieBqUek6Gb+SN8Z06pd3JmAqOoIa2RoqQTyMTFpDt5Qf4KEITTbUlLhPj7TPbjfOTBXW+w0p14D3wTw2bL9b1ly3NeqXmrKKour1OXs2Bl9krzw==,iv:057l15YsA9H9hHonUG6awxEMHSoNwjD4TNYyPijAdq8=,tag:QQwUfjcgMpg/OSQcmlzNtA==,type:str]
    #ENC[AES256_GCM,data:xh3EsyvNpG68EjH9b0c=,iv:pl20ACUMQ7CaLdPi2OasyjGi1Z6BOw7Mhd+dr+m1gok=,tag:QBjnt5zDl8cxctK5Vj+eRw==,type:comment]
    DASHBOARD_USERNAME: ENC[AES256_GCM,data:wcPgXJ9tKnDpR7je,iv:XojOOzhdv+yLqWuv6gn0HlfGqHyjtiPOL6t+RCm11O8=,tag:N0mS49IhZnvNwdvgLWBkxg==,type:str]
    DASHBOARD_PASSWORD: ENC[AES256_GCM,data:wB4stHYHcyAVyWWmbAsWiOgs/ZJ6TmZ2BGIMiNQl43A=,iv:/YGdzkGasMN2fTeYOIB/ap+v0HBEFnwva4vPKZ7rnFY=,tag:USRHaFHvbgKK0XQXrz4Ovw==,type:str]
    DASHBOARD_PASSWORD_HASH: ENC[AES256_GCM,data:HqhC9A7wY2ap957v4IuIwrn2D4SKeYRxPwlqDulPlXrywNjjgvVEx0b05UXqv8O+iqHSM9lEwwhghLIGdvU4OCWb0DK/WUQhy08qylzz5tSsLBtm/Rc9H9dbyWBo7w1T+x2fjy7MTZnK1Q==,iv:UoaA6Us4ks6qcujHYef00fWj+DE9GkNqH3Xqx2DnJAs=,tag:4063UagZGwnuL1WF10T7yg==,type:str]
    #ENC[AES256_GCM,data:UkfKmHlP6Uc=,iv:QFGDeXmv8XLOhXAWeSmopaCMa/8PJ3QXcsT1kowkXHA=,tag:+GJQ8rME5/VKwXSYoj/klw==,type:comment]
    API_USERNAME: ENC[AES256_GCM,data:dKY/8RSFLjl8,iv:AgmPY6MBaknC1+LsGNgEJjnGxay8Y0mv17ZL93Ch4ps=,tag:9fPk3XfPTLIONzT1LyI2hw==,type:str]
    API_PASSWORD: ENC[AES256_GCM,data:99lKR3VlcbFP8pHonzo0mSRhMI5XUzaxgkvc6s49HpE3,iv:KCBxL9CBA3/YgzWVn4GBc46atfzFwoM8k3QBhfBEkKs=,tag:371aBBmd2Re2NsLHJw/ePg==,type:str]
    #ENC[AES256_GCM,data:n4eGaDaUGMc7nTsKFGtp2IG1F4X+VfY5fTjOl5I=,iv:9mBUbbJCj3kI425xW4krL6XEcbhtnIbcNajuZ9kqlwo=,tag:buBaYy0g8yiVMrsl7jZe4Q==,type:comment]
    AUTHD_PASS: ENC[AES256_GCM,data:EB2XXukehlmYc7ClZwgLK+7Qv8IZRwxtqK+tdywA0II=,iv:1mSEqr4rOiRUat+wARSzCRjSKZJYJt2bny0B/YbaA6Q=,tag:OIntL6H3xZ8zt75xSUxH/w==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T00:25:13Z"
    mac: ENC[AES256_GCM,data:2QxgAyl5FEKjxKYqM/lDBqzZxvYKBs3zsQGvc7SBvWv9d2/7gqejA/LOgV+p09VgL2fMpButcPAKJsCSRdJutyLAzldY4iUiDDkfhXrd9bP6b5h43TbcXqrAX4XGFVwCzIOHrn2FF9H7nOMESizT3IaGL0FoZR5nCzCcLy5N4h4=,iv:6s3FusL4VRhtoxptek/8DCpCIJywnMQeAlAT+chgCLk=,tag:u5W2jyzki7swoJFpUGJSYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-passwords
type: opaque
stringData:
    #ENC[AES256_GCM,data:5t1h8PKbrueEqXkrx5yXRMd/ETV/z2m0Q1xd3XmAkRVqM5yyYZvkZtEqw68F5iHPkPuVvk08bS/W,iv:xLpwZpbTx26c2WpRwgiG9Vr6VBU+VP6/oOG54TBqp/4=,tag:7G53BAK4b1DCCvmKd1HIHg==,type:comment]
    authd.pass: ENC[AES256_GCM,data:Xz8Vas6I4i1MATJHtlCqu6HJmTs7fpDNbxMqn8BK6ho=,iv:yMkttuD4XWtoDeHF6JiZtvl1kpu1vd2Qmw2O0hYhG9Q=,tag:46M9CucKUNmRElrIpmnxqw==,type:str]
    #ENC[AES256_GCM,data:Gmsd4H7TJENgtxleqpkFxgskxzYmFTvAW46xYu2+,iv:bZEbk9ZAy6cJCwejMrCmXEWKNzxoOLMA1xDE+/b+UGM=,tag:bqH32t/tWHh97ZyZY8IJdA==,type:comment]
    INDEXER_USERNAME: ENC[AES256_GCM,data:lx6uhHg=,iv:CzVhvu0rJGhcZuDqud6VdI21xVNA4EGq18xURN+luts=,tag:DjkX7Ft00b6IiwbeBaXEOg==,type:str]
    INDEXER_PASSWORD: ENC[AES256_GCM,data:TE4Bv9Ioi+m9+6BLU0WkBWjbQ5lrbxkN1Ie9MmAjvEM=,iv:cYTwnj/J10UuWUUTkzzRQHr6RnGDhah8B7OUNHqx67A=,tag:ctIQ3UND/vH8QEVyauSEOw==,type:str]
    API_USERNAME: ENC[AES256_GCM,data:dKY/8RSFLjl8,iv:AgmPY6MBaknC1+LsGNgEJjnGxay8Y0mv17ZL93Ch4ps=,tag:9fPk3XfPTLIONzT1LyI2hw==,type:str]
    API_PASSWORD: ENC[AES256_GCM,data:99lKR3VlcbFP8pHonzo0mSRhMI5XUzaxgkvc6s49HpE3,iv:KCBxL9CBA3/YgzWVn4GBc46atfzFwoM8k3QBhfBEkKs=,tag:371aBBmd2Re2NsLHJw/ePg==,type:str]
    DASHBOARD_USERNAME: ENC[AES256_GCM,data:wcPgXJ9tKnDpR7je,iv:XojOOzhdv+yLqWuv6gn0HlfGqHyjtiPOL6t+RCm11O8=,tag:N0mS49IhZnvNwdvgLWBkxg==,type:str]
    DASHBOARD_PASSWORD: ENC[AES256_GCM,data:wB4stHYHcyAVyWWmbAsWiOgs/ZJ6TmZ2BGIMiNQl43A=,iv:/YGdzkGasMN2fTeYOIB/ap+v0HBEFnwva4vPKZ7rnFY=,tag:USRHaFHvbgKK0XQXrz4Ovw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T00:25:13Z"
    mac: ENC[AES256_GCM,data:2QxgAyl5FEKjxKYqM/lDBqzZxvYKBs3zsQGvc7SBvWv9d2/7gqejA/LOgV+p09VgL2fMpButcPAKJsCSRdJutyLAzldY4iUiDDkfhXrd9bP6b5h43TbcXqrAX4XGFVwCzIOHrn2FF9H7nOMESizT3IaGL0FoZR5nCzCcLy5N4h4=,iv:6s3FusL4VRhtoxptek/8DCpCIJywnMQeAlAT+chgCLk=,tag:u5W2jyzki7swoJFpUGJSYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
