apiVersion: v1
kind: Secret
metadata:
    name: wazuh-dashboard-secret
type: opaque
stringData:
    #ENC[AES256_GCM,data:E7/ftyTiouk2s/k36eZruMWYvT/MD3DWCochEz+gOwaqDvsjhPadoTYNV83534NFwOSJRclk55B63h6KmkFhAFeM/L2YMGOCo1Euewc/wbtUzG/hrvoYxWPn/cnhQk9mK6lJALA+fBLGKu0PERT5iK7/zmMRGkNeM1Xvzm16T1c2A5RoMVm6yQh8Hvcxhk0NNhawQcQmf6ECTqXdjo5ooQ==,iv:IOcWl50wlq3dKuaYhtV0xBja8qqOCXAnIXlLk0MxMFg=,tag:zHEt9rn+hkSIqI0FkmOSrA==,type:comment]
    DASHBOARD_USERNAME: ENC[AES256_GCM,data:8dS3QHs=,iv:+wvYvzvddfJqHNxCAkx0k0nXeGXTjd6G6QS7FPbtPYk=,tag:3ox2rPcx3mj6RGHdAHKBCQ==,type:str]
    DASHBOARD_PASSWORD: ENC[AES256_GCM,data:gF/Bs8/lcrY=,iv:dssmRiqS6Ul6cNsgY0/dryJsuaXuPhgBqAZvE7R192A=,tag:VETjFga93E28wsVUqU9WOg==,type:str]
    DASHBOARD_PASSWORD_HASH: ENC[AES256_GCM,data:P/Cqam0tshDIA3Qq3i0WpIEghm60qQNSVEAzFWIqIYPocUmaQMoqBHXi+RlMtRczmsaP/b8GTujiC8d2,iv:6W620XkAq/7OrZY9vDgmM1RVTsEHMMgJP5hzdo1QKqI=,tag:qa7SaFY/3myYGGJ74dq5/A==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T01:56:40Z"
    mac: ENC[AES256_GCM,data:g6z0yAznfum7BQP//4wA8Y6SQutDyyIIaObBOH0WL/f5DsCGWOrpkacq1suxKbeUHF/9BZFRAkxOC676SWY4mp7kij3V3YbYN2L1pKQYTy8HjBhC0QMRTyeTmC+ZO24qsnTTjOBWnvnbBYpKYnB1EwrqwV9ghysmG3OuDmfjG2o=,iv:F+LvKjl7Qm9stOB6iLAl+uiyywMPiHPec7btbd3SzPc=,tag:ipca/ZuOgW5q8ILQRrRWxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-api-secret
type: opaque
stringData:
    #ENC[AES256_GCM,data:E7/ftyTiouk2s/k36eZruMWYvT/MD3DWCochEz+gOwaqDvsjhPadoTYNV83534NFwOSJRclk55B63h6KmkFhAFeM/L2YMGOCo1Euewc/wbtUzG/hrvoYxWPn/cnhQk9mK6lJALA+fBLGKu0PERT5iK7/zmMRGkNeM1Xvzm16T1c2A5RoMVm6yQh8Hvcxhk0NNhawQcQmf6ECTqXdjo5ooQ==,iv:IOcWl50wlq3dKuaYhtV0xBja8qqOCXAnIXlLk0MxMFg=,tag:zHEt9rn+hkSIqI0FkmOSrA==,type:comment]
    API_USERNAME: ENC[AES256_GCM,data:ugtaYAQ=,iv:KUZ0WnNr+SBFYtjSth2/CfQzQ4UvrgO61n7M6WfW7o0=,tag:unMRUWuHuJwbh0ies1GC1w==,type:str]
    API_PASSWORD: ENC[AES256_GCM,data:7GxX9Xs8UvlJ,iv:SamrcrA0yheHgOzA8uBBm+cI6qyb5TJ2erv5jfszjbc=,tag:5c1ZYpQlOqxaaOkgx/CGQQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T01:56:40Z"
    mac: ENC[AES256_GCM,data:g6z0yAznfum7BQP//4wA8Y6SQutDyyIIaObBOH0WL/f5DsCGWOrpkacq1suxKbeUHF/9BZFRAkxOC676SWY4mp7kij3V3YbYN2L1pKQYTy8HjBhC0QMRTyeTmC+ZO24qsnTTjOBWnvnbBYpKYnB1EwrqwV9ghysmG3OuDmfjG2o=,iv:F+LvKjl7Qm9stOB6iLAl+uiyywMPiHPec7btbd3SzPc=,tag:ipca/ZuOgW5q8ILQRrRWxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
