apiVersion: v1
kind: Secret
metadata:
    name: wazuh-dashboard-secret
type: opaque
stringData:
    DASHBOARD_USERNAME: ENC[AES256_GCM,data:8dS3QHs=,iv:+wvYvzvddfJqHNxCAkx0k0nXeGXTjd6G6QS7FPbtPYk=,tag:3ox2rPcx3mj6RGHdAHKBCQ==,type:str]
    DASHBOARD_PASSWORD: ENC[AES256_GCM,data:gF/Bs8/lcrY=,iv:dssmRiqS6Ul6cNsgY0/dryJsuaXuPhgBqAZvE7R192A=,tag:VETjFga93E28wsVUqU9WOg==,type:str]
    DASHBOARD_PASSWORD_HASH: ENC[AES256_GCM,data:P/Cqam0tshDIA3Qq3i0WpIEghm60qQNSVEAzFWIqIYPocUmaQMoqBHXi+RlMtRczmsaP/b8GTujiC8d2,iv:6W620XkAq/7OrZY9vDgmM1RVTsEHMMgJP5hzdo1QKqI=,tag:qa7SaFY/3myYGGJ74dq5/A==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T11:05:34Z"
    mac: ENC[AES256_GCM,data:PF/gopHOAR3VdAvcyD4xTHgJus7aZmioc6TywZza4JWi9qF2sLcnl+YX+ykbSzqDkFKZ2vTyAPuHxQwp8z8eKScwNa3av5Q7FEabFZAzteMERJROtl3xaXL+zaYd9jduiulOVr/Vn9KzqxlVvSosQY43Ali6vTmW7Dubh1trQUk=,iv:zaiZwBpvlPPM/zHB2/BzAjRvLsMN0zEtcGwK5aTvUx4=,tag:/sDcUX8uoLIQqkdf1rM90Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-api-secret
type: opaque
stringData:
    API_USERNAME: ENC[AES256_GCM,data:ugtaYAQ=,iv:KUZ0WnNr+SBFYtjSth2/CfQzQ4UvrgO61n7M6WfW7o0=,tag:unMRUWuHuJwbh0ies1GC1w==,type:str]
    API_PASSWORD: ENC[AES256_GCM,data:7GxX9Xs8UvlJ,iv:SamrcrA0yheHgOzA8uBBm+cI6qyb5TJ2erv5jfszjbc=,tag:5c1ZYpQlOqxaaOkgx/CGQQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T11:05:34Z"
    mac: ENC[AES256_GCM,data:PF/gopHOAR3VdAvcyD4xTHgJus7aZmioc6TywZza4JWi9qF2sLcnl+YX+ykbSzqDkFKZ2vTyAPuHxQwp8z8eKScwNa3av5Q7FEabFZAzteMERJROtl3xaXL+zaYd9jduiulOVr/Vn9KzqxlVvSosQY43Ali6vTmW7Dubh1trQUk=,iv:zaiZwBpvlPPM/zHB2/BzAjRvLsMN0zEtcGwK5aTvUx4=,tag:/sDcUX8uoLIQqkdf1rM90Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-indexer-admin-secret
type: opaque
stringData:
    username: ENC[AES256_GCM,data:r6MI7sM=,iv:NE8p+jxd8QPkXF2ii74K+ofV5oqTdmrm8C0ILK3Mha0=,tag:KmlKBaB/BngXx0NXaX2B9Q==,type:str]
    password: ENC[AES256_GCM,data:Axw4hUVeeJay,iv:yiYbgMs9ZZMYn4oTlE7O/qHU5hJv/EwhUKgpENoZ+A8=,tag:xOELkqX5nochNCGDFRSYsA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T11:05:34Z"
    mac: ENC[AES256_GCM,data:PF/gopHOAR3VdAvcyD4xTHgJus7aZmioc6TywZza4JWi9qF2sLcnl+YX+ykbSzqDkFKZ2vTyAPuHxQwp8z8eKScwNa3av5Q7FEabFZAzteMERJROtl3xaXL+zaYd9jduiulOVr/Vn9KzqxlVvSosQY43Ali6vTmW7Dubh1trQUk=,iv:zaiZwBpvlPPM/zHB2/BzAjRvLsMN0zEtcGwK5aTvUx4=,tag:/sDcUX8uoLIQqkdf1rM90Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: indexer-cred
type: opaque
stringData:
    INDEXER_USERNAME: ENC[AES256_GCM,data:qwiDriA=,iv:Xow29pJoFeFi6yhgB8EbAOc89+lCnrWe2yS4LMd6Kko=,tag:26hmQSaQslG0k6iP2uS8/Q==,type:str]
    INDEXER_PASSWORD: ENC[AES256_GCM,data:193l7350fH7J,iv:s5W/QG12A7Yrl8h0/SvXRqg5R+8N+2ha+MlXnSbB1XY=,tag:liE+/hTTOAK8lohT6r8+3w==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T11:05:34Z"
    mac: ENC[AES256_GCM,data:PF/gopHOAR3VdAvcyD4xTHgJus7aZmioc6TywZza4JWi9qF2sLcnl+YX+ykbSzqDkFKZ2vTyAPuHxQwp8z8eKScwNa3av5Q7FEabFZAzteMERJROtl3xaXL+zaYd9jduiulOVr/Vn9KzqxlVvSosQY43Ali6vTmW7Dubh1trQUk=,iv:zaiZwBpvlPPM/zHB2/BzAjRvLsMN0zEtcGwK5aTvUx4=,tag:/sDcUX8uoLIQqkdf1rM90Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
