apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-modifier
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: sysctl-modifier
  template:
    metadata:
      labels:
        name: sysctl-modifier
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
      initContainers:
      - name: sysctl-modifier
        image: busybox:latest
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.2