apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: freshrss
  interval: 30m
  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostUsers: false
        containers:
          app:
            image:
              repository: freshrss/freshrss
              tag: 1.28.1-alpine
            env:
              LISTEN: &port 8080
              DOMAIN: freshrss.rnatr.com
              TZ: America/New_york
              CRON_MIN: 3,33
              TRUSTED_PROXY: 10.0.0.0/8 172.16.0.1/12 192.168.0.1/16
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M
        statefulset:
          volumeClaimTemplates:
            - name: config
              storageClass: ceph-block
              accessMode: ReadWriteOnce
              size: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.rnatr.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          freshrss:
            app:
              - path: /var/www/FreshRSS/data
                subPath: data
                readOnly: false
              - path: /var/www/FreshRSS/extensions
                subPath: extensions
                readOnly: false
      tmp:
        type: emptyDir