apiVersion: v1
kind: Secret
metadata:
    name: agentmemory
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:kje1V9IuoburtGSOPI1OF4wEXy14J5Dt4g==,iv:dbe+g7ge1JcV0rl/yZDDCijlEFVHlXUjmg5nUdTDHVo=,tag:0CReoqzU4CEY9vavuVtaew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczJPSkg4bjJDUGpVUkE5
            R3dEYlZnbDZ3YlZpUUVqRkY1bXhDL3c3d3kwCmdYMUY2bWFUd0N6UlFyZXp6MDBU
            TTR2ZXJjK09pMS9XbU9Xb1p6em1tSnMKLS0tIGJnUVUzb3pCWHlIZTVhOXlwekFR
            SEpMKzA2emR5eGZaaGdKdTNhdGg4Q0kKj09cPOtz9iNoT4xozv0hwThlL4cKt7AX
            XYGGu1ChmDcqUSaiDps4eSZ0x1umnHSiGDLIcKRkY+nQMndYjtS/cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T08:43:15Z"
    mac: ENC[AES256_GCM,data:OOsFh3ov1ed5hBGA0HzuTrqzHdmRURQAGUEGPVSUh4nXO8go38QDLZTXjbkhY8Wy4cfj6rM7OCiS/mUNRnONqGuJBwMkZthaZzEXgMs/9xBwaTSlZg5+lU/xsEL+4oPjBYh9V8UYdGishuSRRbJvL8oztMZfkl7BZerXz4Q3WP0=,iv:YnrHdNtWb58LM9fh7n7Yxi/IdU4Tj5Xu+OMwPhdUDRo=,tag:RbcOE7DTi+ub/1nL+IPuBw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
