apiVersion: v1
kind: Secret
metadata:
  name: agentmemory
type: Opaque
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:c9tDPLwJ4pI=,iv:Nr80EDWX5lh6fAMSqSeguTJ/VoyMEHjTZOE3dzn/EDk=,tag:eUfVC/UqkcybmPqGqGQkRA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczJPSkg4bjJDUGpVUkE5
        R3dEYlZnbDZ3YlZpUUVqRkY1bXhDL3c3d3kwCmdYMUY2bWFUd0N6UlFyZXp6MDBU
        TTR2ZXJjK09pMS9XbU9Xb1p6em1tSnMKLS0tIGJnUVUzb3pCWHlIZTVhOXlwekFR
        SEpMKzA2emR5eGZaaGdKdTNhdGg4Q0kKj09cPOtz9iNoT4xozv0hwThlL4cKt7AX
        XYGGu1ChmDcqUSaiDps4eSZ0x1umnHSiGDLIcKRkY+nQMndYjtS/cg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T01:12:00Z"
  mac: ENC[AES256_GCM,data:3+cj1yOKSnvm2rEPfBKdvFlINp95anyDbpo3GLsS69Wg0++B1xYOwWpHRDYE2Z4b7RlM9LTG70aiJ4LtlGFdfBgB/YZRfO2/4WBC3LrOtYg7ppiCpd+6Sqcbns4GJHvL/Vco2F81EwHK1zSvLOlNeul5oYYmznEXY3OCpBVylHk=,iv:6U2o1fYaIpePYwQLrwBarKB57/5uUSgBS8we+Mda3Qw=,tag:5K3kJYuA0vsTULlQdmKYXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
