---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 30m
  maxHistory: 2
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.6
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              JELLYFIN_PublishedServerUrl: https://jellyfin.rnatr.com
              TZ: America/New_York
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 1000Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30

    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: jellyfin

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.0.20.70
        ports:
          http:
            port: &port 8096
            protocol: TCP
            targetPort: *port
          discovery:
            port: &discoveryPort 7359
            protocol: UDP
            targetPort: *discoveryPort

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.rnatr.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      transcode:
        type: emptyDir
      data:
        type: nfs
        server: pve.jonathanrosshart.com
        path: /pool/share/fileshare
        globalMounts:
          - path: /share