apiVersion: v1
kind: Secret
metadata:
  name: litellm-s3-secret
type: Opaque
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:OYJ3r0QV3w==,iv:CHmX4PC74/JVVM+gIySSc7hUVOsxqiUwGn1x/TtFmZE=,tag:iCPV1jvCvlNSMUrnHF62/w==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:sAcVhG6BfJ+av++UMqIdEJpO+S1Tn21CMxC7fucHNwM=,iv:t5nEOi1EfDm02u+IClO699UywrojOPMG9gxpUBWzvxM=,tag:4UZ/YOgM5aFn7aet0iMqzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2JvdEhoRitML2E3WVFj
        U0tyWVlabEE4bDdlWFIzbk9nRk9ZQm1HMXlrCnRrM2VyVDFrL2FZekFsL1hwSERn
        WlB3MG8vNzNydFhYa0x2SE9qT1JvZmMKLS0tIHlDSW9aQUZINmRBazNoRHBMTTV4
        clowdTVPa3FuRjBpMG1Ua251MnNzUmMKwSYMVtBw7B+69daX5Hn6k6LKJx0dSBJ8
        2csuyhhO1sEzovjc9IHa1m4RM1dDVabArPvhO09V51f5vB6XQi36Hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T17:21:47Z"
  mac: ENC[AES256_GCM,data:TYA1Avgb/i9OhiXDbQdqKcOPVaiW3nV+CHuJ/K3LJ83ANQ+7atdpCwanRl2crQ2vJHpr63bKwYlzizpQe6WXjzqY9L3a//DFNHnTxJgoLcIofKe8TSkahgffrAqiEkzDBw+6IeZ1p9RhtVVdqrsMlPZr+q9XPZ8C84JDU3WkG58=,iv:/1Czh5iYuooGuewaiK06YwtzNgBJLnqjsYvWVW6q8ws=,tag:FWMQYHDYq6ST7f6zXlfrzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
