apiVersion: v1
kind: Secret
metadata:
    name: llama-cpp-secret
type: opaque
stringData:
    LLAMA_API_KEY: ENC[AES256_GCM,data:NJQuOf87xIQX36LJ1KdPcNO+qvJS0CIpkIqHi3QO4bUJHt9SO55J5Lf+7dS8KTgPhWR3V5uDS8X4kRXuBBfxOg==,iv:fl/oMTq5R0hObRNTmKYGx5CcTbcd6NXoaiuLrjG5tYA=,tag:vvjrZly175L7uL21JQgw8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dTZNT1FkWlgyR1dqeVJG
            RVFjM2Z5aUx3cVhuY2hsQURGbVkwVDV5TmxNCjFETXd1MVJyVXRGYzdCSUFNZXhz
            dlQzK2NXem55eFJVY1NwRTdsSGRYNDAKLS0tIEdHOHJoNk1Hc1VRNGMyV3cyMWZl
            ZE1SNjliUExlcFBCWXNqRlNJTWU1UUkKXhFC1eRtR1RvgusoEt3Cj6O6tsTQig3J
            aEQhOOrDOG82GNcsU8uPg3U+dvwXsEXn7HSPfknKc3FE1LVogNA4mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T13:31:23Z"
    mac: ENC[AES256_GCM,data:wQkdMDrhhmAoTcxJWNRcqaAbHbF5q7Qvbwo99NvntP09cJSUi1YTKT1taz1Lar8Cc3IDTkALwQo9ZbPLucrLpxTYPRN5jjIw95jLXODPCyM3JryjNiJQwCJHzreQ8Eu8uFZfJb+xZrbtG/zPj9tuqyMzqrr1CBRxilwl5f65np8=,iv:Z9E6jltQnX/2/kUWEC1+jDNTx5lnDUMG0MgdnH5C7Bs=,tag:QaSUmqlV+iWYuZTbXHCSpQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
