---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sensitive
  namespace: flux-system
spec:
  interval: 30m
  url: https://forgejo.jonathanrosshart.com/delf/sensitive.git
  ref:
    branch: main