apiVersion: v1
kind: Secret
metadata:
    name: forgejo-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LpHS8OcHaOwvdbahI2pGbVZCNOpACcqZwE3eaZzvBxcV7vPhReCRZA==,iv:XgYYwm+hUCtC0VQmC6wNt32cNQvKxXgjSXegHTxcQE4=,tag:ApPKBiu3ThslhG+X0+b9Zg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlBhUzBQVXhrQW8yeFl0
            NUg3WDltTFEzaUMxaTR0M0k1cll2V1VNRUg0CnZPbVBTWDQ3N1dhdGZGVXFNa2hq
            U2ZCMURaRlpOQStCRGR0Tlg4aWdKYjAKLS0tIGdLWTR5c2tyWEtlb3o2bXZYdnVj
            ZDdIMEtMS2c2ZGU2ZStDNUJiRi8zdEEKNjyFFdX51JcWGficVv3WUklBa5eVdyet
            2Be4lG4VpiqeM1SsTG1Wc4MIvv341EBH901x/4zSjM33UddamPWO6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T17:00:45Z"
    mac: ENC[AES256_GCM,data:Hm3cwpCo4MFjNI7sBxAkSHlUq2vritCvCOLgTgErEn6J65/wMhjecqc0b9p2tvP5byrNzooWeA4ElBcZUk/KObyXTKKpWQhKwKrZ+u5ZaEURbLtzjnIl+xcahvCWqoSoFLOSFjGLJEgWEa8yS7JuaQrC9EDFGfL5KxrT4wsRtRo=,iv:3YvDTXFx67pFDC5qDP4p5qjyIFYcUGtJSbXjye0UbBg=,tag:cJz3WwG3m/q5Zf2nAYk84Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
