---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: homeops-bot-auth-token
spec:
  appID: "3208447"
  installationID: "119621335"
  auth:
    privateKey:
      secretRef:
        name: github-app-private-key
        key: privateKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeops-bot-auth-token
spec:
  refreshInterval: "15m0s"
  secretStoreRef:
    name: github-app-store
    kind: SecretStore
  target:
    name: renovate-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: "amhhcnQ5OQo="
        GITHUB_COM_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: homeops-bot-auth-token