---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
spec:
  discoveryFilters:
    - "delf/*"
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_PLATFORM_COMMIT
      value: "enabled"
  image: ghcr.io/renovatebot/renovate:43.212.4
  provider:
    name: forgejo
    endpoint: https://forgejo.rnatr.com/api/v1
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: forgejo-renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: forgejo-apitoken-secret
        key: token

