apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: github
spec:
  discoveryFilter: ###GITHUB_USERNAME###/*
  extraEnv:
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
  image: ghcr.io/renovatebot/renovate:43.64.3
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: github-renovate-secret