apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: github
spec:
  discoveryFilters:
    - jhart99/home-ops
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_PLATFORM_COMMIT
      value: "enabled"
  image: ghcr.io/renovatebot/renovate:43.160.1
  parallelism: 5
  provider:
    name: github
    endpoint: https://api.github.com
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  skipForks: true
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: github-apitoken-secret
        key: token
