apiVersion: v1
kind: Secret
metadata:
    name: forgejo-renovate-secret
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:gNxr5VTx/LgIjDRjb9WPchIbe5DtTsMU+t9PiWD1e2boBMesZbodlVUuV8FRmYfu2XSRRNOW5yq91Bq9TOVzCQO8Ln5KpKoEWABD8e5+pJ7FrSZUc243FyHhg4/u,iv:83jhq4APLK/IPVKNYpRLyOHpCIGsAg7VjGMoWOQc5bM=,tag:yBKPRhz1PeyzsQtAA+AKmQ==,type:str]
    #ENC[AES256_GCM,data:C9gkzJEuV2y3LY8wQzX59ddJdHfKk/dtaWAH1S2l3heZysCwx4SkkPvWb7paQTg/b2fDRVH61rQ1NS50k7yM78i56I5hYAi/zPxac0DRDMSRo9CN0WySo2CN4DN5JnU=,iv:SpC9E3cG2mQABkpXdzMguivxxqLGr4hDlOXPguLDcwU=,tag:/KreMNRCpik/f5nkRlwz0w==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:zvoRUQ==,iv:Ftv/YhP91FN9SeNpTDasNMBy9+q8iEnfvi3r/8vJuKY=,tag:NsKa/5h0yrXA2sV/JujvVg==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:65uE8sILEl7G0/xC1NJ97hDHbqXkNTb1KCG0Yn7NIiI=,iv:pxKSXGwjt8tGZFtUze6EohvUjcy9VFv/XiZQebOZUR4=,tag:ealvWRKWlCy3MXg1dSaw4Q==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:p4fB+oN79q6Bxgeo75TQjHdk1Sg++4s1YiV6FZ1cLg==,iv:LmzDtE3tvhscs4J5T6htkPxTlAe1vIfGoBCdk/48K20=,tag:7/wH4bsAOp4tfaeBR3b2rQ==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:stK2u1BQ9w==,iv:+SB/TcFzqRlczBqFtBE259tUFWWwF2ogJDgTlA8oYxY=,tag:LvGMBs0YdgVxoE9agX9LhA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:IoollMCTU4xm5v0lbo9hHC3/IFHsXDe8bM/GzyyKTVRECeCHkLHNgg==,iv:glwkCgWmVcoImyxdBZVcX7RITY8dtxV1zOgedV81YC4=,tag:y2tpH66KbxYQnRM1YFKGfQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
            NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
            K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
            Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
            GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T09:53:33Z"
    mac: ENC[AES256_GCM,data:XKVU7HaWiQ3IDlhuVIw1qX9wIEN+cxpQmTi+v6ZkPFLD3C4s4+A5rzoV7WLiMekaXryL3xoD+FcC3owi5Nh8Y8e2eliwYEXoWZYKhIDZ+tPSCMVO6s+cY+Jgnwt/SvWauCOyFSNuLiK6WmcH+NxS2W3dOLGqnYLDxd/N79DCJ1o=,iv:F0/lRDV6wnwdT1MYIW8b8A9PETe9dxtRkVPsa2yTeY4=,tag:MrBMICGlwsWCuWFflhhCcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-apitoken-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:2tRA+BYA4yR2pTCxVKPu3xSqCj8PR6pN8zhOUSH7vRbphZ8IrJNZIZCzc32Q2tcFD7DiLy2mUr6XNMw/OoDh6g==,iv:3uEyqBpYIuJcfZjw8nM4/6t8T61YxLEA2lTq9biuzFY=,tag:8SWpvqpMEwNiP0KdVnS9DQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
            NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
            K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
            Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
            GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T09:53:33Z"
    mac: ENC[AES256_GCM,data:XKVU7HaWiQ3IDlhuVIw1qX9wIEN+cxpQmTi+v6ZkPFLD3C4s4+A5rzoV7WLiMekaXryL3xoD+FcC3owi5Nh8Y8e2eliwYEXoWZYKhIDZ+tPSCMVO6s+cY+Jgnwt/SvWauCOyFSNuLiK6WmcH+NxS2W3dOLGqnYLDxd/N79DCJ1o=,iv:F0/lRDV6wnwdT1MYIW8b8A9PETe9dxtRkVPsa2yTeY4=,tag:MrBMICGlwsWCuWFflhhCcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: github-app-private-key
type: Opaque
stringData:
    privateKey: ENC[AES256_GCM,data:vGp+WvrO9mbt+XfmJci0jdsPvR9/Hr6CHTHEy3/yfkuwrHYxRXCUNPtCmTeWtOE63+/mWW6bQ3NvgDmKjLhWVVWdabMXP9eISgfvJoqAhrdzQ6tn1MtWyd1u8eNAF2L70ZVQs6jber1LkguU1CrvxkO8v6F4qoSxR3FlTkGs1IkXhwSKVw2lcn3I68rr6SYpZsravNxw6/grZW3xML7GTpIqQNLfkm9FCwU5Y/bE7riBdsKpPQ8CJBy2yAmMAsOoz7OtRC20sMYUQQA19WbDs+sitwiZ9OlK4yV9yK9Ufz6s04wE8ln08LzOOa7G/q/VXstcWa6J6oRZBW6/Ge7LB1m2Il9FGI7N3YnvZqHgPwbu1SswYlJlMXW0oGhDowwnrK10igRLCZuhx53J6i7nT5GXX7qRG26AimvnhacI9c3IfkWdszh4LyGBUKtQY1tNvEOpxuELTerNGoxpC8RUAGSTVYXz39zHDBTnuownb1nrycHGY4flndwRHmWoZRPw6Cty/0lAJFL1Frlojx+rnPsf9FxSrBxFFPWylZhfs0KXgCAjtlMi4oYU6LDV8XBglc8P+je8Z9wc8LbCpYzMUZCEZCIJZMC9RdCSm1XoyfdSQcgWU08uTUv9L4bJffRtAWNi64ACrfKSAhMcMvLwHjZM5bRCUJfOl3T/wZO87l/DiAeUMz1oRORf1uY9os1jY1OMbnI9o2lEY+bJ1j5/bLc1buequ7o/j1dcJ0GD3rmGwKamlm6gK45BXL4FplHspLEWQjK6SUPmEmaz1ws9CEHE+AnyCXB6UKOR72Dd3xdq3Ovwk9rEfJzfPerrMl5aKoc5mjeLrovlVFGpZdIpHkkxXS7xxjB2fv7JmSuAlR9xgDhRNvGSRHUJStqH2+ifWv8Ha7lIEyGtldSDW+bzTPJYAva6lrhaHEtf8n1AiZ1WvpMsNeBZXHHBiJ2vDxlgW5NGRLSKUtYs5aODVJzSIG/lkL86XFMNfgISAh06Z/9TqCb6BeKPyYK+aXQ85QLdeeY0QS0+tnwQeQaOz8xyu2TDt0adsYL8sWMstYhenp+srFC7ZHI7UaxnYNxZqm8HO8iUvRM2jYmc/MBxooz5Z0UkONtPVXuRogoSo2DwPbdK3zjqfC6siy9WRrWjSdZIQllyLQRuI6OBnX7wBnv/t9/Woi/BoCxc31RKLx8LXpNQLTyJ2AI1wW0e1rlHa/SXByIGFee3ed3lw0u4DMOU5z40xYz+wMuVtpqDAQwQ57byRj5t1dUm2TR0k+yIrNleYPpX475nPc+BQc3MexeXLSPtwHcFyDCMKA+PrB8kzey99Z3VbinIcTsjNRTWCj8lyCPhjpYO1LZxbFnNg/ixABiXeNO/9HKVXqxEJfFbBFqqs4h0Ctu2bbsqrzLoVnvaRhWA7kvS/5bku47jEVEMB3ylJtd/64LIanG44r9M9KFo1ayZOV0+WUBgfOzNlmVOuZDyTIB/8xp5CuQVwzWVpzanNxZidC+XLKLwtxJk/YRI1GAfHs5HDZoeBzNlQmQtebOZC1okJkZtm/qMz6isERW7ijpaden91eCbVNVwr6SRZgqWsB0w9UrQTsS9NqXpShzmnsp+N/EbyLSeGPLT2j44vbaYvX1YL1RyJjzi+VgopozwZUVFPvjFIQxWrI2Me0oi90HBF02PQi0Un4hZLB/E8Ge4G4Cdui8KFAEI3GE0sObybf2+66BmtS9DhUqvbkacbcRR62dmQiKAji4LagpAmFFNG9yM3VETNRYZdujOouxBqw8oCt9fqiQuNNV0vD0ARbbchMCIqew+ZOybWtprynHQp3Y4I6D2ZKHoS/G7j5Q03XyHROxhMO6vkvE4Pw4PqhH5rgXuwVk6xPArbq6gF+qFjDypegxpT+J1CF//+TQBVOguUfR70upQVw8Jf1jHrkU3P0xz+wliW0g0jNQ6XpzyTl4/stH9nPb3clZXpQ9BCvsT58Z+ImWoPiM4QwflEdq3UxQJoYWaPHAnh8xvewEWyh3hFiar9+EcDMt5LX9yvUC7jHtRhqCn+K3yfecz4SwDCpyw2eVhVQh/uKAhl6Ysc+TYIRPX+mX18ZhwtPfIyto5yiJIVdOTvwezUIzETggLsvSeTiIQOb7unXzsoEUVNbKN88mY81g/1F2vm66AuLVM5hC9QuaxzxIEjnphUwCOypCzzzSOLL+fSV9L1jGOQWImHb0qfo32mAo2z07lctKAiMs9,iv:P5o51U39zRgMDeErc76rZe18BrHy3+bhbofOFlaxL/g=,tag:4624ekb9+pdstxUlTx1tdA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
            NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
            K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
            Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
            GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T09:53:33Z"
    mac: ENC[AES256_GCM,data:XKVU7HaWiQ3IDlhuVIw1qX9wIEN+cxpQmTi+v6ZkPFLD3C4s4+A5rzoV7WLiMekaXryL3xoD+FcC3owi5Nh8Y8e2eliwYEXoWZYKhIDZ+tPSCMVO6s+cY+Jgnwt/SvWauCOyFSNuLiK6WmcH+NxS2W3dOLGqnYLDxd/N79DCJ1o=,iv:F0/lRDV6wnwdT1MYIW8b8A9PETe9dxtRkVPsa2yTeY4=,tag:MrBMICGlwsWCuWFflhhCcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
