apiVersion: v1
kind: Secret
metadata:
    name: forgejo-renovate-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:C9gkzJEuV2y3LY8wQzX59ddJdHfKk/dtaWAH1S2l3heZysCwx4SkkPvWb7paQTg/b2fDRVH61rQ1NS50k7yM78i56I5hYAi/zPxac0DRDMSRo9CN0WySo2CN4DN5JnU=,iv:SpC9E3cG2mQABkpXdzMguivxxqLGr4hDlOXPguLDcwU=,tag:/KreMNRCpik/f5nkRlwz0w==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:zvoRUQ==,iv:Ftv/YhP91FN9SeNpTDasNMBy9+q8iEnfvi3r/8vJuKY=,tag:NsKa/5h0yrXA2sV/JujvVg==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:65uE8sILEl7G0/xC1NJ97hDHbqXkNTb1KCG0Yn7NIiI=,iv:pxKSXGwjt8tGZFtUze6EohvUjcy9VFv/XiZQebOZUR4=,tag:ealvWRKWlCy3MXg1dSaw4Q==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:p4fB+oN79q6Bxgeo75TQjHdk1Sg++4s1YiV6FZ1cLg==,iv:LmzDtE3tvhscs4J5T6htkPxTlAe1vIfGoBCdk/48K20=,tag:7/wH4bsAOp4tfaeBR3b2rQ==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:stK2u1BQ9w==,iv:+SB/TcFzqRlczBqFtBE259tUFWWwF2ogJDgTlA8oYxY=,tag:LvGMBs0YdgVxoE9agX9LhA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:IoollMCTU4xm5v0lbo9hHC3/IFHsXDe8bM/GzyyKTVRECeCHkLHNgg==,iv:glwkCgWmVcoImyxdBZVcX7RITY8dtxV1zOgedV81YC4=,tag:y2tpH66KbxYQnRM1YFKGfQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
            NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
            K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
            Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
            GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:46:39Z"
    mac: ENC[AES256_GCM,data:038vEeEwL0ToXdbbUEV9h0vl8TeI7E0eF713t9IlCGL4AxhRCjAm0xZs49tE+wkPfpaR7b2Vfh4fhCnKNgMTkRAfQGmosO+F+EnhBk9RIKn2PjtJq64O/k/JfcLXnuI3fz7hylc72Jvq13pebVUjC3I2h1Fomk4yL2R1LrCGI8M=,iv:tv+YvkZzQ6ubFEpmYnfAvdNVUw2OD1KsVNV2lvxKiic=,tag:KZIsDQNoJ+skDc2CEbT1Rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
