apiVersion: v1
kind: Secret
metadata:
    name: forgejo-renovate-secret
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:gNxr5VTx/LgIjDRjb9WPchIbe5DtTsMU+t9PiWD1e2boBMesZbodlVUuV8FRmYfu2XSRRNOW5yq91Bq9TOVzCQO8Ln5KpKoEWABD8e5+pJ7FrSZUc243FyHhg4/u,iv:83jhq4APLK/IPVKNYpRLyOHpCIGsAg7VjGMoWOQc5bM=,tag:yBKPRhz1PeyzsQtAA+AKmQ==,type:str]
    #ENC[AES256_GCM,data:C9gkzJEuV2y3LY8wQzX59ddJdHfKk/dtaWAH1S2l3heZysCwx4SkkPvWb7paQTg/b2fDRVH61rQ1NS50k7yM78i56I5hYAi/zPxac0DRDMSRo9CN0WySo2CN4DN5JnU=,iv:SpC9E3cG2mQABkpXdzMguivxxqLGr4hDlOXPguLDcwU=,tag:/KreMNRCpik/f5nkRlwz0w==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:zvoRUQ==,iv:Ftv/YhP91FN9SeNpTDasNMBy9+q8iEnfvi3r/8vJuKY=,tag:NsKa/5h0yrXA2sV/JujvVg==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:65uE8sILEl7G0/xC1NJ97hDHbqXkNTb1KCG0Yn7NIiI=,iv:pxKSXGwjt8tGZFtUze6EohvUjcy9VFv/XiZQebOZUR4=,tag:ealvWRKWlCy3MXg1dSaw4Q==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:p4fB+oN79q6Bxgeo75TQjHdk1Sg++4s1YiV6FZ1cLg==,iv:LmzDtE3tvhscs4J5T6htkPxTlAe1vIfGoBCdk/48K20=,tag:7/wH4bsAOp4tfaeBR3b2rQ==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:stK2u1BQ9w==,iv:+SB/TcFzqRlczBqFtBE259tUFWWwF2ogJDgTlA8oYxY=,tag:LvGMBs0YdgVxoE9agX9LhA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:IoollMCTU4xm5v0lbo9hHC3/IFHsXDe8bM/GzyyKTVRECeCHkLHNgg==,iv:glwkCgWmVcoImyxdBZVcX7RITY8dtxV1zOgedV81YC4=,tag:y2tpH66KbxYQnRM1YFKGfQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
            NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
            K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
            Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
            GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T01:01:17Z"
    mac: ENC[AES256_GCM,data:rRsW9I0LUL4awdvEs0NrDPn++GSS6tgIeAmxHcAD1aNUqW1HxkwE25nid/OBh47AKs+NezV/GLkUGRRXMXS8VyDeo9weoNINVup5uPWBsicC+W3SYwu0BzcKRjJriBkvP/C18zZrkud22WNMvf0EdnpVIUiR42OweZtsRTrXMCM=,iv:rTH2GRxWnNatMyc5+mOrwZG/LyAkuLHZTlu0wJRbHqI=,tag:XkoNa5W2Y0xZYYhu/NS/DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: github-renovate-secret
type: Opaque
stringData:
    GITHUB_COM_USER: ENC[AES256_GCM,data:QFIHrsfFap14Hv+etJdQhUNb1pxHngY=,iv:Rrx0Ts7aNbHQmwBtEuVWprHTbTlNS8VOfdl/wm5Mdhc=,tag:YoqMMD8Or+Tj1VW0N+Pr3Q==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:Or8dk8sV0FCOPfbLu62vPjfIxmH/r5bWECHJBgkaLbY2,iv:uLf8HlV/E8+DZcjs1fkX8YuNT4Xdc0YqGbOX7IdzOW4=,tag:LCmYmpGpC+j3y232kaXHvw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:5mOubBjH2RWaVh5BjlFrwjFuvIwKetP0S7adE8z6uI4utYc=,iv:4pUv3sGEB+wD5H4XiXLGDv2bLDhECduhrmxUGR8bgTI=,tag:d61OtA+RTcmnCwErltu03A==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:gNxr5VTx/LgIjDRjb9WPchIbe5DtTsMU+t9PiWD1e2boBMesZbodlVUuV8FRmYfu2XSRRNOW5yq91Bq9TOVzCQO8Ln5KpKoEWABD8e5+pJ7FrSZUc243FyHhg4/u,iv:83jhq4APLK/IPVKNYpRLyOHpCIGsAg7VjGMoWOQc5bM=,tag:yBKPRhz1PeyzsQtAA+AKmQ==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:QCaaGCXi+90SIaNO/ztEXabgT5SzKJs=,iv:PSBb/b+6n1h6NRg8MNqlqpk1YccwR+OTyfEJxc26F2g=,tag:/QJpRziKfQA7OwWcZufAcg==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:p4fB+oN79q6Bxgeo75TQjHdk1Sg++4s1YiV6FZ1cLg==,iv:LmzDtE3tvhscs4J5T6htkPxTlAe1vIfGoBCdk/48K20=,tag:7/wH4bsAOp4tfaeBR3b2rQ==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:RwaBaUCM,iv:qpu/Ufedpu69hDUBNNfphqWNDFPiJhrzwm99TWaLQVc=,tag:wBSEZjj1ECE2Fg8sz5WKBw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
            NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
            K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
            Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
            GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T01:01:17Z"
    mac: ENC[AES256_GCM,data:rRsW9I0LUL4awdvEs0NrDPn++GSS6tgIeAmxHcAD1aNUqW1HxkwE25nid/OBh47AKs+NezV/GLkUGRRXMXS8VyDeo9weoNINVup5uPWBsicC+W3SYwu0BzcKRjJriBkvP/C18zZrkud22WNMvf0EdnpVIUiR42OweZtsRTrXMCM=,iv:rTH2GRxWnNatMyc5+mOrwZG/LyAkuLHZTlu0wJRbHqI=,tag:XkoNa5W2Y0xZYYhu/NS/DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-webhook-secret
type: Opaque
stringData:
    GITHUB_COM_USER: ENC[AES256_GCM,data:EX4E0erB6rd8nrkak+312BwTDaHa8EI=,iv:WAoQlce5s7QTmzwDNlmuAcAc8iCkLHtVTLJQYf5LPiQ=,tag:2CfgVfSQf4vBOMjdY2tKKA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
            NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
            K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
            Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
            GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T01:01:17Z"
    mac: ENC[AES256_GCM,data:rRsW9I0LUL4awdvEs0NrDPn++GSS6tgIeAmxHcAD1aNUqW1HxkwE25nid/OBh47AKs+NezV/GLkUGRRXMXS8VyDeo9weoNINVup5uPWBsicC+W3SYwu0BzcKRjJriBkvP/C18zZrkud22WNMvf0EdnpVIUiR42OweZtsRTrXMCM=,iv:rTH2GRxWnNatMyc5+mOrwZG/LyAkuLHZTlu0wJRbHqI=,tag:XkoNa5W2Y0xZYYhu/NS/DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
