apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: opaque
stringData:
    BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:hWcTJdkvUA==,iv:Jd6K8pIFjPJp6J9P/7xo5SN5f53Yij/N1qkMAMUFzGg=,tag:xYtIERcglNVsv58wn8XVQg==,type:str]
    BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:OkBsbWBkrQ==,iv:c9b9mrbpUYieEMA4U5KQbFbv3v1SoVkBgnU0pE0gfQI=,tag:rqe1Cvk7dbGsJxIXP0F/nw==,type:str]
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:J1EyvzJyocublUqeKR18EwmC95bvcRaAEBudAY4o,iv:tGofbJpGAFIokwwhux3CVhMZXtAe6qlq+oFVuToWJFc=,tag:407ojlWsWO64TDVKztfDQw==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:lgmXDriTVVRx5nE0L8jZ4OBvg9/TJ9GYOnxlkEEh,iv:gckKrDbIBJMWJMYazC7u4h1ooTSwLpspfpg9uSumTBI=,tag:kGKYxvuNHJDTYzi7IGPbhQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbXVqR2JhSFJYNVgySU11
            WnZTTWw5eXdLUEdKMlU0c0U4NURicmQ4OXpRCnZwZlAvQUpGeHNGK1lEUmFKbGdE
            K3hscnN5K0llSE8yb2FzOVQ0MUoxNWMKLS0tIGhpbzloMCtEOWtqSUVlV1huUmZP
            NVlMMlZacWN5THZQN3licXlLTUVEN3cKY9RfA/7Mn+kldqIH88IFe/fX6bvl+rl3
            nG98e7yecKdR4yNNtWHnufb8GgFjfrrcWETGWH8zOV2SgFMbaoGO0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T08:45:40Z"
    mac: ENC[AES256_GCM,data:YfOzMB9ahhr2vfFdpbcX39tbI6d9iWiLF/Ln9cWeclA6vQa3dYAszExgVZujbfFVVW59xuXfLL5stCpLMaA2svQjXE2xKlV7Q4Ddi6KPHSaK8eQ8t6SXxs2Ae8hMS7wNEZDGb+6uoa43tP3RCMBQlvaIIkyka1N4KdILXPAsPVU=,iv:HPRaljeseArsKHHZaRTNCFDFYfYEVPPsqKiUKEaK+B4=,tag:7uxoZdFa/T+4cPZ3Df7p1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
