apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: opaque
stringData:
  BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:+SqgRg==,iv:j4CvHQ+0WR5YeVXXa0sWNeiLT/lPW4DANStF4Sq1SBU=,tag:n7Fj84zinkeqdycb3efCIA==,type:int]
  BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:Zg9gNQ==,iv:HdWfqm80Mwhqw/xjVszBgM2SchfW49xBm3PIFGm7BzE=,tag:fjyTLCwVzNE9hdj9ayTl6Q==,type:int]
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:2wpgqA==,iv:lE0t8BTr1tefi+cmHRIcjy8KeFI83ctJ/gfPYQoZkvs=,tag:r3ePA1liG+GgwVR917cOBw==,type:int]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Mkv3mA==,iv:+mWR4MCh8JYLi559PGxb4TiopadjDZ2cjU09M8UqwkM=,tag:MC87BeYmOiEKRDpUU9VpAQ==,type:int]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbXVqR2JhSFJYNVgySU11
        WnZTTWw5eXdLUEdKMlU0c0U4NURicmQ4OXpRCnZwZlAvQUpGeHNGK1lEUmFKbGdE
        K3hscnN5K0llSE8yb2FzOVQ0MUoxNWMKLS0tIGhpbzloMCtEOWtqSUVlV1huUmZP
        NVlMMlZacWN5THZQN3licXlLTUVEN3cKY9RfA/7Mn+kldqIH88IFe/fX6bvl+rl3
        nG98e7yecKdR4yNNtWHnufb8GgFjfrrcWETGWH8zOV2SgFMbaoGO0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T02:13:27Z"
  mac: ENC[AES256_GCM,data:Rafj+y+6ItedmUWps8jdw5vzvxbeymgQ2Z3x+cRlUoaHsMr0AQEBQmu+ZdUqBxank5yKJLm8U7PkEgB89lJxA0VUaCMxAWMgbqcW13Zxw2DZscUyEGKDYuB8QC2JGoHo0vBhGC+wG2Z0XndqJ9wq+5BMsGmyiY/UbIvjBbQNc/4=,iv:RqwTbYRtAJS0gSBv7ZwPIcnztCP/P0nnSZeSUyalm6w=,tag:5VIlQAlGIuXFm7AFmtWU2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
