apiVersion: v1
kind: Secret
metadata:
    name: tuwunel-secret
type: Opaque
stringData:
    CONDUWUIT_REGISTRATION_TOKEN: ENC[AES256_GCM,data:DJC6jUKp2Ypx+qjWh200LRO8C0QalOqU2700j27VtuSuqspgIvYereM0B9+BOyIGDdy/0PJgTBXg6iEv3H8ZPw==,iv:+FmEP4IMADOGzXbc8OfxbZLmw8+fAW3KWG2gtnqHmHA=,tag:SuOzXDSrU55/ZYSe3XfyFA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T10:47:36Z"
    mac: ENC[AES256_GCM,data:wmqrcE1vMuPHDoBV8z124NLUOcW/f5QBAR6U6N39TlWK9H3+JK4UsOhK5Igm4h8JflI8xWLXR7+dVqC+c7xMgJQbv8PiB8BDLFOWwGAeiLZovp7O5bLtsJ9IZELjxt2rNQPJYN+f5H9Fc0+bf19y3VnZeH/Quik2gJ+r7/DLo6k=,iv:0h5ZmsDg7al8TxVXhYT2zDhfVo0LMVAyRO6ZI2Qh9PQ=,tag:AsPnQbMsE8nnTfEykvazMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
