---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
spec:
  chartRef:
    kind: OCIRepository
    name: backstage
  interval: 30m
  valuesFrom:
    - kind: Secret
      name: backstage-secret # The name of your secret
      valuesKey: AUTH_OIDC_CLIENT_SECRET # The key inside the secret
      targetPath: backstage.appConfig.auth.providers.oidc.clientSecret # The path in the Helm chart's values.yaml you want to overwrit
    - kind: Secret
      name: backstage-secret # The name of your secret
      valuesKey: AUTH_OIDC_CLIENT_ID # The key inside the secret
      targetPath: backstage.appConfig.auth.providers.oidc.clientId # The path in the Helm chart's values.yaml you want to overwrit
    - kind: Secret
      name: backstage-db-app # The name of your secret
      valuesKey: host # The key inside the secret
      targetPath: backstage.appConfig.backend.database.connection.host # The path in the Helm chart's values.yaml you want to overwrit
    - kind: Secret
      name: backstage-db-app # The name of your secret
      valuesKey: user # The key inside the secret
      targetPath: backstage.appConfig.backend.database.connection.user # The path in the Helm chart's values.yaml you want to overwrit
    - kind: Secret
      name: backstage-db-app # The name of your secret
      valuesKey: password # The key inside the secret
      targetPath: backstage.appConfig.backend.database.connection.password
  values:
    replicas: 1
    backstage:
      image:
        repository: ghcr.io/backstage/backstage
        tag: 1.53.0@sha256:ce21057f17a41243c842af1ad0e43beb4748e590c8c1210ddc98c5dcff36e737
        pullPolicy: IfNotPresent
      containerPorts:
        backend: 7007
      appConfig:
        app:
          baseUrl: https://backstage.${SECRET_DOMAIN}
          title: "My Developer Portal"
        auth:
          environment: production
          providers:
            oidc:
              production:
                metadataUrl: https://auth.${SECRET_DOMAIN}/application/o/backstage/.well-known/openid-configuration
                prompt: auto
                signIn:
                  resolvers:
                    - resolver: emailMatchingUserEntityProfileEmail
        backend:
          baseUrl: https://backstage.${SECRET_DOMAIN}
          csp:
            connect-src: ["'self'", "http:", "https:"]
            img-src: ["'self'", "storage.googleapis.com"]
          # psql database configuration
          database:
            client: pg
            connection:
              port: "5432"
            plugin:
              app:
                connection:
                  database: backstage_plugin_app
              auth:
                connection:
                  database: backstage_plugin_auth
              catalog:
                connection:
                  database: backstage_plugin_catalog
              kubernetes:
                connection:
                  database: backstage_plugin_kubernetes
              notifications:
                connection:
                  database: backstage_plugin_notifications
              permission:
                connection:
                  database: backstage_plugin_permission
              proxy:
                connection:
                  database: backstage_plugin_proxy
              scaffolder:
                connection:
                  database: backstage_plugin_scaffolder
              search:
                connection:
                  database: backstage_plugin_search
              signals:
                connection:
                  database: backstage_plugin_signals
              techdocs:
                connection:
                  database: backstage_plugin_techdocs
          ssl:
            require: false
        techdocs:
          builder: "local" # Alternatives - 'external'
        generator:
          runIn: "local" # Alternatives - 'local'
        publisher:
          type: "local" # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
        catalog:
          # Overrides the default list locations from app-config.yaml as these contain example data.
          # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
          # on how to get entities into the catalog.
          import:
            entityFilename: catalog-info.yaml
            pullRequestBranchName: backstage-integration
          rules:
            - allow: [Component, System, API, Resource, Location, User, Group, Domain]
          locations:
            - type: url
              target: https://github.com/tyriis/home-ops/blob/main/.backstage/catalog-info.yaml
            - type: url
              target: https://github.com/techtales-io/backstage-docs/blob/main/knowledge/catalog-info.yaml
            - type: file
              target: /.backstage/catalog-info.yaml
              rules:
                - allow: [User, Group]
    postgresql:
      enabled: false
    ingress:
      enabled: false
    tls:
      enabled: false
    serviceAccount:
      create: true
    metrics:
      serviceMonitor:
        enabled: true
        path: /metrics