apiVersion: v1
kind: Secret
metadata:
    name: backstage-secret
type: Opaque
stringData:
    AUTH_OIDC_CLIENT_ID: ENC[AES256_GCM,data:DZSZXL+z3pJaRV6CTztAmxYPcjyLNPyORll3QvF8BgAsVFaoO8r+tA==,iv:NwrkoL44m1wPtgRP7RRSQTrP2ISWb87jzwE+yNQ2wvs=,tag:KWZeX8lo+qC2migdJNVfqw==,type:str]
    AUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:KNC2JPPdYUjsTs12CPfZdALLo+sxHs4S8qNMuhYFZ0cA8TBu2yJHfk8AQcKGhqrGtcYMTTbhWUBmZ3168ysZ/k5dFFzQPbRXkvJzVEoW/i+DKPBpOYVB5VBUODUvZiQe7td3hhdIjy8BsFE6c1RpJOiot+hLvchLTaXwMeDmEGQ=,iv:/SD7vGM9Het9QsMp0XMjfnbuZxqyhLStMUaAC0N2WGM=,tag:1efzg2pz0O4GwAzgL741/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T12:33:33Z"
    mac: ENC[AES256_GCM,data:KRKM4a9NdlbfFXcQym0BNZblM8AuK1XBZHiAaRMiUWlyfBLQpHXrRisotWo7KOYMOV3fxwE2ruUZpxZObnNXlEFjq6sGc3uze3GRT7mrlPSYRbCIxzyyuSHsnEwbu/XQHaSI3TSUzmD5XgFyWwcygtWoDX2vX9GbpZvrxOiwH3A=,iv:4l2sAObOa6QDk1h/oKb2jbxQj8K5PQO+NtC63c87qTw=,tag:2y65wiLeiRa9fRkeEdi5gA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
