---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name jupyterhub
spec:
  interval: 30m
  chart:
    spec:
      chart: jupyterhub
      version: 4.3.3-0.dev.git.7285.h2e426380
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
      interval: 30m
  values:
    debug:
      enabled: true
    hub:
      networkPolicy:
        enabled: false
    proxy:
      chp:
        networkPolicy:
          enabled: false
    singleuser:
      cloudMetadata:
        blockWithIptables: false
      networkPolicy:
        enabled: false
      storage:
        type: none
        extraVolumes:
          - name: jupyter-pvc
            persistentVolumeClaim:
              claimName: jupyterhub
        extraVolumeMounts:
          - name: jupyter-pvc
            mountPath: /home/shared

    httpRoute:
      enabled: true
      hostnames:
        - jupyterhub.rnatr.com
      gateway:
        name: envoy-internal
        namespace: network