apiVersion: v1
kind: Secret
metadata:
    name: openwrt-dns-secret
    namespace: network
type: Opaque
stringData:
    PROVIDER_OPENWRT_LUCIRPC_HOSTNAME: ENC[AES256_GCM,data:6CIRJHvSGngZY7/DfUlvQo8ZddR73HfXCOEPsg==,iv:0aeWl0VKiHOk/UEN4OfboJOzbeZwRLzcZBtfCGFAW9w=,tag:6C41Gm/prTabIRcrtCAgPw==,type:str]
    PROVIDER_OPENWRT_LUCIRPC_AUTH_USERNAME: ENC[AES256_GCM,data:imM19w==,iv:KB+FDw2aGvb7QzXgSy+CY3ETLJQ6X9qYMz54hwdUAXo=,tag:5YfoB7Kd0oLoUlXYt7qOnQ==,type:str]
    PROVIDER_OPENWRT_LUCIRPC_AUTH_PASSWORD: ENC[AES256_GCM,data:p+c6TITdcOw=,iv:y+xZcmAVcMZezfJBFVRadNQNmmLErugEwHLETYLT2gg=,tag:hbZyufEK7kBbodin35FfBw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZTBrSmJxd2h6TGMwRzdw
            MjVXNHRNaE5wdThScUMyb3JkZjFOT0UwdlJZCnc0dXR5M1pBYS9BWjJaMW01RGpo
            T2xIc2pVbFEwdEE5d05mVjk0NWNkSE0KLS0tIDI0bFd5Z0RGaFBBZXl1K2NabFQv
            VGlsNEw2bUxLSlpocytwUUdWMkVoWkEKOTt9imCFDxJLhvPjPGmGCkMBbOK+gFz+
            9LMhASZ0W2KKFRy0i9Tl3xDBx9pTa4WxDHLmlZk7aIzdoyLtXuyYlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T01:51:36Z"
    mac: ENC[AES256_GCM,data:Fje9gddwzmXL249G17bORxtgU1niMicuZCTKJEFEbEyRlIziPAh5wYZGqBjroTOxd82gW76idcGFzZzgO55yT2YmGHIVSWPKRxgtBme65XJT6ZMeTNvTs/O9gWCl7PkrNWG8qnQ4gxo0UNb3TTjtqIgpf34ksXQC5TnuiGD8kMg=,iv:qfCRCMUIBmc96vo+xz0OjmrBli5Vt87JTqA3YL+K/yI=,tag:u+rn6GX8xIm1kNWO6r1BGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
