apiVersion: v1
kind: Secret
metadata:
  name: openwrt-dns-secret
  namespace: network
type: Opaque
stringData:
  OPENWRT_HOSTNAME: ENC[AES256_GCM,data:gBmuvbrBPouS6ecxPgy2OCAHvc3ExYNfZEXLFg==,iv:Ql1OTDVnAdU4toE3OYj4c9qEdwGo2dsczYXca4K5sxo=,tag:AlkZsn7CvufhcGb9n6n4ig==,type:str]
  OPENWRT_USERNAME: ENC[AES256_GCM,data:qEjNXg==,iv:E9CIhff8hg+wemIb+Y+DLQI0T1LferkmnuFNqbDw5HI=,tag:L6YEUGmXT7j96pomaQ7e/w==,type:str]
  OPENWRT_PASSWORD: ENC[AES256_GCM,data:+mAh0R6vGmc=,iv:jiEatFf03o1o8+EZOaK9K6qD2uT7ikts2NwgJynXfbA=,tag:49MThCGroNErqVwmQMvYkg==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZTBrSmJxd2h6TGMwRzdw
        MjVXNHRNaE5wdThScUMyb3JkZjFOT0UwdlJZCnc0dXR5M1pBYS9BWjJaMW01RGpo
        T2xIc2pVbFEwdEE5d05mVjk0NWNkSE0KLS0tIDI0bFd5Z0RGaFBBZXl1K2NabFQv
        VGlsNEw2bUxLSlpocytwUUdWMkVoWkEKOTt9imCFDxJLhvPjPGmGCkMBbOK+gFz+
        9LMhASZ0W2KKFRy0i9Tl3xDBx9pTa4WxDHLmlZk7aIzdoyLtXuyYlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T22:23:02Z"
  mac: ENC[AES256_GCM,data:ccqIs+2PDhDiz8dB3sPC+mL6nGuQzPPX9yiYqBFwbH8hSaTKuTX7R63BX482X3RGUoOij9JgiwlcpygyvtB5gqmteIuDBw7L8/Tn5yxqCDY92J0cZBmXPIxtX/A6ZKIZQPZ4rFwxUYPHndVcLmE1BMnVzHoyFEAbcb107xVT+iM=,iv:wZPXOQpEZXVxK5i/7RxkJTFFWNAeg95b25yUvyX0iEE=,tag:pV7SVW6js4fNOEBoVOUOzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
