---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: coder
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: coder-secret
    coder:
      env:
        # App
        - name: CODER_ACCESS_URL
          value: https://coder.${SECRET_DOMAIN}
        # DB
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-app
              key: uri
      envFrom:
        - secretRef:
            name: coder-secret