apiVersion: v1
kind: Secret
metadata:
    name: coder-secret
type: Opaque
stringData:
    CODER_OIDC_ISSUER_URL: ENC[AES256_GCM,data:NNBL84Ixky1zjZiH3HmVI3t9dFYRLLqpAOKtUTgtuU3kbghEif4LbofkGw==,iv:HbBmNX4bqn9ctZSiPZYIf3Rw0jca/M3qajelacgx9NE=,tag:LnS68yZztVhG8yjx8sqP5A==,type:str]
    CODER_OIDC_EMAIL_DOMAIN: ENC[AES256_GCM,data:NHa+xLkgD62y,iv:DjjGq4kyV+3b+/BF89pnEUuMNYiZzRZlroyCAscDb3A=,tag:rTSXsEYJ4g5AUGYimuYB7Q==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:B2LcOW8cN4MXQvobFPJsb2X7G0pC4qG6lsjVP1Rvyhl6b177zGGUTg==,iv:RYRvJrTp4dr2z3KK4f2WFvLoNY2AtWgwRrUpnz/UN7I=,tag:4SWLz/GHPySPo4qSlAuUFw==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:QS9pFDdZav8vNIPsJLr88EbG+K/9MSiHmYXFNC6rfwCrN+F8AnUcJBPDu26fMhirbJYcAxQ1yK4sbkWjGjHk6lv/zWCTDSK32T+m0uWHj6HxvJu1zIelwiC4RiyW03fP8eqRAGQS1MQS3sIXgRqs07yeTXW+4OV0Bigj0rALx60=,iv:6k6qzPcs44yuFrYN9InZ4Pa2UNgaggL6Zcw2mSnfEPY=,tag:/sFf0e7Iom00NfoTy6rv7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T22:27:49Z"
    mac: ENC[AES256_GCM,data:ywJ+BWtfH2Br9kPXqiOv9AJq546qfk1C/fdcSYs92bmnd7qljh4gU0CdeWUT7V/rwXDHF3VUD3mSQo7UtJjSxKwhsdq4X5/vDRFuHPvGYWGFMPvq9hAd0aX3TpjrnxrJpxcfM9PY0uL5e9YvFcDWO5FhRZPaCbr8s+snrwf3onQ=,iv:xbXaGq/0XXPB9dGtpMi0IZL1mIjb2AEcjhuZWatn+Lg=,tag:GnlZFcoZS09owHSlzxP1Gw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
