---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: ublox-gps-rule
spec:
  rules:
    - name: "ublox-gps"
      labels:
        feature.node.kubernetes.io/ublox-gps: "true"
      matchFeatures:
        - feature: "usb"
          matchExpressions:
            vendor: { op: In, value: ["1546"] }
            device: { op: In, value: ["01a8"] }