apiVersion: nfd.k8s.io/v1
kind: NodeFeatureRule
metadata:
  name: ublox-gps-rule
spec:
  rules:
    - # This rule matches a USB device with vendor ID 1d6b and device ID 0003
      name: "ublox-gps"
      matchFeatures:
        - feature: "usb"
          matchExpressions:
            vendor: { operator: In, value: ["1546"] }
            device: { operator: In, value: ["01a8"] }