---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: detect-vlan100
spec:
  rules:
    - name: "vlan100.available"
      labels:
        # This is the label your pod's nodeSelector will look for
        "network.jhart99.com/vlan10": "true"
      matchFeatures:
        - feature: network.device
          matchExpressions:
            # Modify this to match the actual interface name or pattern on your nodes
            name: { op: In, value: ["net0.10"] }