---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zigbee-rule
spec:
  rules:
    - # This rule matches a USB device with vendor ID 1d6b and device ID 0003
      name: "sonoff-zigbee"
      matchFeatures:
        - feature: "usb"
          matchExpressions:
            vendor: { operator: In, value: ["10c4"] }
            device: { operator: In, value: ["ea60"] }