---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zooz-zwave-rule
spec:
  rules:
    - name: "zooz-zwave"
      labels:
        feature.node.kubernetes.io/zooz-zwave: "true"
      matchFeatures:
        - feature: "usb.device"
          matchExpressions:
            vendor: { op: In, value: ["1a86"] }
            device: { op: In, value: ["55d4"] }