---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
spec:
  dependsOn:
    - name: litellm-db
      namespace: ai
  targetNamespace: ai
  interval: 1h
  path: ./kubernetes/apps/ai/litellm/app
  postBuild:
    substitute:
      APP: litellm
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm-db
spec:
  dependsOn:
    - name: cnpg-operator
      namespace: database
    - name: rustfs
      namespace: rustfs
  targetNamespace: ai
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  path: ./kubernetes/apps/ai/litellm/database
  postBuild:
    substitute:
      APP: litellm-db
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  timeout: 5m
  wait: true