apiVersion: v1
kind: Secret
metadata:
    name: toolhive-github
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:R5YmEJIy6JmLPiBrvkM6zeNhLRfymMELLiz+Yub/QpETlvKNDE8QXQ==,iv:8PlGy19DTDrSL7KCoLsHKt15ZFUcP+E/w9NfLAgv540=,tag:1nfVLeXM4r0pIMMn+1xRCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczJPSkg4bjJDUGpVUkE5
            R3dEYlZnbDZ3YlZpUUVqRkY1bXhDL3c3d3kwCmdYMUY2bWFUd0N6UlFyZXp6MDBU
            TTR2ZXJjK09pMS9XbU9Xb1p6em1tSnMKLS0tIGJnUVUzb3pCWHlIZTVhOXlwekFR
            SEpMKzA2emR5eGZaaGdKdTNhdGg4Q0kKj09cPOtz9iNoT4xozv0hwThlL4cKt7AX
            XYGGu1ChmDcqUSaiDps4eSZ0x1umnHSiGDLIcKRkY+nQMndYjtS/cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T10:24:16Z"
    mac: ENC[AES256_GCM,data:JM7QUpr+JHZufY+WYOlfMomfyLoKIfanPu+UPFUVTuLNkZ5QpyGVjT0Un66bLv25qmOTfD6VP04NfFFHqtpPDVmR/z5cx8lyau7lQogouU3AN2iMgu+NLHuEoFEXIiZKa1LHEKWpdgVsx3RZXmudVMMqOU7K+lpx0TRTm4phzzM=,iv:DcNbRheKuWk7XExw5dJQ5Y9jWsP27rI6dyd80AnpjQY=,tag:nM4x1tlocb0u6gKo1sga4A==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
