apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:evrLUsrZR0UVdcDR88Y4cUNfVW4z5cXlLAVKAm2yTPaGddclEHxzsYLV6wSl+6Bfmmkua8/gRvoBnqUIrvWAAQk53nFYrwvxslxNMA1k73iyYW4GzVE0wxdDEkdG,iv:L6XqGTOZ7gS4QSUDZBHTPHM01LUJ/bluwkvZrZnNXec=,tag:VriqM5+X5+3VE+MM6MfBDg==,type:str]
  #ENC[AES256_GCM,data:C9gkzJEuV2y3LY8wQzX59ddJdHfKk/dtaWAH1S2l3heZysCwx4SkkPvWb7paQTg/b2fDRVH61rQ1NS50k7yM78i56I5hYAi/zPxac0DRDMSRo9CN0WySo2CN4DN5JnU=,iv:SpC9E3cG2mQABkpXdzMguivxxqLGr4hDlOXPguLDcwU=,tag:/KreMNRCpik/f5nkRlwz0w==,type:comment]
  RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:zvoRUQ==,iv:Ftv/YhP91FN9SeNpTDasNMBy9+q8iEnfvi3r/8vJuKY=,tag:NsKa/5h0yrXA2sV/JujvVg==,type:str]
  RENOVATE_ENDPOINT: ENC[AES256_GCM,data:/3uO8rNrEm+toH6KRURHPHh0z8tjrVT7S2VBz32si/v0gPbfL/dfao3E1A==,iv:VvL0+k8if+e4T4+avLglJkDJnOAFghvfTjT2314YIfQ=,tag:OGdAHQL0jdiZ5awN4Zc1Yw==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:L5r0fFYzuYUEqlGMzmbyRtmA2UNmJVjkq8/a0ZwzKQ3Y,iv:lZCJHIdCvU5VXFBfLmAkiVKKBzjHEtj173jZgyrMxRQ=,tag:KP/NffWrGuoiEw2c7Th3BQ==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:stK2u1BQ9w==,iv:+SB/TcFzqRlczBqFtBE259tUFWWwF2ogJDgTlA8oYxY=,tag:LvGMBs0YdgVxoE9agX9LhA==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:o6Odh6h/AeU7MlFFgH3Y0nBVroLGPbS+Bb4on6iWSwAdwK0nJYi/Pg==,iv:90ZtvbRXhAIfmPskhOMp8DBWo4VlG7UcnhR0aLurEpw=,tag:8STTHfps4TZ4CuHmyboJMQ==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUZDbXZxR0lGbTdXZkNm
        NDltaCtVaGhhaURkVEV6a0FhM3Urc0gzTXdRCkdnNjhRaU5GaXdBb21GQzZ5NWRP
        K2lUY3hSWFlLbHFpc3FxdTdrRTVZQU0KLS0tIHIrcWlmNlNzWDBoVmg5bGdONTdr
        Uks4K0JFb0k2SllmcjdWZzhiZ29mVWsKo7qLGn5TfmYtcnSIo5O3v0B+C00UZYa3
        GOnqpibkIdDEdT0nQ7Kyf2ZsZKgOgq2W21M3/tyDu+cua/3nZeLCsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T16:04:37Z"
  mac: ENC[AES256_GCM,data:wlD1XYjp0Q6aEiWFsuRKkWhsX3sSW+9IxKMl36qOimH/+eyYNyuphmzUxFEUoO8eepo/nsWOLHASF59uipM+0K3E2L+aa18n1cBguwq7cepi9BioWh/ckhmXkUu9oYWQICHZpV+uIkKqBfvRRiI6gYIqbx2ss9Hr7+SM55Fr1xw=,iv:0cgFCSHw/rh1SYBM+9FpnSs3BSG6ywfNGajnGIawNWE=,tag:5uoVwcp97g+KEFQZVPBeXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
