apiVersion: v1
kind: Secret
metadata:
    name: context7-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:JaRY+tfgSJepD3I5gQWbpVTgcy0SMEK1vuY4paGT82nNoeXxK1a1k9oTZA==,iv:QBHSfcurYt9NRYn/Nihk74lGkuxajdeyJnRe+VgQlQs=,tag:c8aYZ/Xv6kwmUoNVAdQM5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczJPSkg4bjJDUGpVUkE5
            R3dEYlZnbDZ3YlZpUUVqRkY1bXhDL3c3d3kwCmdYMUY2bWFUd0N6UlFyZXp6MDBU
            TTR2ZXJjK09pMS9XbU9Xb1p6em1tSnMKLS0tIGJnUVUzb3pCWHlIZTVhOXlwekFR
            SEpMKzA2emR5eGZaaGdKdTNhdGg4Q0kKj09cPOtz9iNoT4xozv0hwThlL4cKt7AX
            XYGGu1ChmDcqUSaiDps4eSZ0x1umnHSiGDLIcKRkY+nQMndYjtS/cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T10:26:55Z"
    mac: ENC[AES256_GCM,data:FtPppuDnTRTSNQHsjCv3Cx2PU36RqPVDj1tZfjN32iM3be4g/qD6hPjSu6bceJjUDp2t/Ru1VeiHTbh8QDRRjK2NcGNX31R3z1pJHJJ3fqD/ixqaOAQJo+GAweL7CxJSmD0xS/RYcGOIMqyTjRks1BAdYs/QAcwuNUxVW6RNFR8=,iv:vlwT3lqcePB6w0YdgFvUwaKl0u821wDYb6G2ik6Zfkg=,tag:PcFu20VTecXQdI5EZx8Muw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
