apiVersion: v1
kind: Secret
metadata:
    name: zigbee-secret
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:sbLm+x9ZQoiG9dVnhofAZgtxWV/+It434CbFn6lEsQzrHFmEhWM/YvMZVUQ3xFGv,iv:9OeBkJUuQZ7kUke86jO58t/8+YHFfLrXyzmh159JpBw=,tag:nnB78szU2BalMLyX8TfX/w==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:70LirPcX,iv:nXYKG4insEOhpQoVI6/YRG6lFpNsi3byPqQzhgcut9A=,tag:AFuGJeEROTM7xgRTFSD5hw==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:bqY+15vgwU1BXvqYNvfApyl8GgkNPRbkCGgwvRzoYqwgI99RPQ3PlUgD9Ew6q3un,iv:jFJuzp4CugTJ7w2WL1Rg5gF8kont/jS0eoiXUEYYWTI=,tag:OOSMak7qbthXbkkSrg4g5A==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T01:14:00Z"
    mac: ENC[AES256_GCM,data:cXXe1fCxijXs0Rf1cVTQXmLp0HmA1KNi07IFRTQlS8Zi3+SfO5ZOePt5Zr2KMCnKEE7zoxrqvmemZmSInGRNci7HkR4ertBmF+6m+z2kzrpfoRWzao3SFAYyR1L2HyU3TETXrXd7lrhHU3fUfXsbPUaS0N+OHvuIi8ClAQigvUw=,iv:FANUikRDztgbrdRyJ44/gxOAaIj+XGHQkBl+XR2DnxU=,tag:kKJpwdrknX1xPG3OPjpZBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
