apiVersion: v1
kind: Secret
metadata:
    name: zigbee-secret
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:jgJ15akoThToO+yrlgy+ANfTTbAA1zTWgj5bAe5+EREBCmA2CKO+TL4B10o1lAUX,iv:Yw5wB/NnYEtGuBq+KIA9SvNS3gRvVFvmRfZzHvHH5hs=,tag:18lx+aZbfUirkiqiOGxcfQ==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:dSBV49P4,iv:HJRzPLbwUoGCbJlvmGb+UFI77iXxlq4Sf8n0DeTYaRw=,tag:au12DA9jQM2rt1LQTaVebw==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:IfL69KQYbNZ5BaAI9aMr6DBfaPJsZtFRXX4crSfAuX285bppyRM+GgJL3cfN5uAxXa6Uewl+,iv:aj/A6c/hv5Bng7R+llMWQ37jLDygWSS8ktGcvpokj4s=,tag:+arFYPIUpL2FXa22TDfDIw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T00:51:59Z"
    mac: ENC[AES256_GCM,data:4TNt33q7omSTkzZo3ZXYW4Dizifa4oj957HI0xHAsydW3eMo+ezWjmkHkxM8/yvZjc3wo1K2gPwEyiNDA2Rl4Pu3ay1HdRsjoi+mjz3+Rf4zrqUwCibyksvB5SlcWLaXDtAbemMaslGzlSXJwglllsJBvAAI/+aN5vz5ySbikjY=,iv:wTdLfJbHn6qpUs46KYe7yI1hmutRTykSOgmwOJfksIM=,tag:Be9mailDGQUZuh5LQa8F8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
