apiVersion: v1
kind: Secret
metadata:
    name: zigbee-secret
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:hfD0PFb8lRg=,iv:T0jPWilIgLGZaGygglyJu8LdlsxP/+StaaprGO/bzUY=,tag:HpIWgclJYBb4cQ4ekMeW1w==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:byItSEI/Pk0=,iv:RCxt6LyCW1BaUIIrs9k5ezHq/hrVbBwjOoHlPrOHQ10=,tag:cLt5743EbCGpuesuhRMd2g==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:iMurPNninX0=,iv:Gr4aWAFB/vMTkZJxQFfvqSRiRN30rjO9mLuBvEGadcA=,tag:FPnEtyQ7grmWn/L0n4dRew==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T00:54:34Z"
    mac: ENC[AES256_GCM,data:UOtL7SFLzfF3WRbn78gfhxDt74Wb2GFwLM0n+pywX8tOimKn/KtEZFJAyK1mnugezFkLqC7SyWNJk8HZ0XDjVKE7F2T2rEmuGbZrZenPsjg9ETS9R3iqrKHn9NXrydwzm7kVssB+q+BHQtXsh+5Vm0fr19PgBDm4SJWyh04a9nY=,iv:slTrBVxhXTlajArwt4P4cvjRizZRPr47aR+XAtzCt0g=,tag:PE99d9BTdFAk+wpxV0m0JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
