apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fisrxRIP4Id3cXPjrPHZtX+PYbVvkbArCpRrC4n0iYqmMxvtdA14gg==,iv:LPIa46xh6d+w3zgz6MNmH3GhEg7JcRwIBhSzysr1OcQ=,tag:R8S1ecLXo/JlqF9/F7BAGQ==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR09nY2NORXpSOUNpUHBv
        RGZEV0t6SzNJMXNnQUJvR2Rmc0JqZXRBQUZVCnhaZGJ4TFJ1aUU2N1pCbDBUS3hG
        Q0xGZlF1THhGRkU3SllKVkdVa1NNYWsKLS0tIEl3emJ4OFoyazVqSFJROUFiVysw
        VUlCUUQ3a1F2aUJMT2xSUXJaQk9LVUUKMJSx+sJXMTiBY8Iyf9Y9ErnLt3qTF94Y
        vBrpS4rGuUbQb0sYDAEwC2VLKNZgu7pjjnnGYy/upCBef86TpkH9rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T17:22:15Z"
  mac: ENC[AES256_GCM,data:JxMvnr8CwzabflcEefqhC3zfNLECS2rOfYHDS0tAQOaDF+je8J5BJL5ntQRPQtL5TDtcFUk09HRUdFP0ZT5D9L3SErf+MUhBTxV8NtJTphgXgx5D7JYGAO4rbZFxS8uPmfAYPPhJ649EQEitrNj5j3+dy/mMRAS62/aXIUxm0GY=,iv:9GU47P9q93ew0EQxjzV25xzZouhf9s4ks5WRi1xp07s=,tag:RmyJLUfzFQS2m/Vw5sIsoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
