apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Nhry7I44hrSj3o5M7T2aWzECjboxnW9m4e8ow0FoG5rGR+JfOmT7Xw==,iv:FBkNS4sDx/WWy2PfSm8pGu1bkqBGdFfjt1f3IU7gai4=,tag:3iy7ClYIt4JfU6K12aGGeg==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b1hvVmdsODUwa2RiMzI5
        QUY4eDRxRnpnUGVkWUcyb1N6dlZ0ekFqbEdFCnVSVmM2aTVlSlJKa3A1cjNONjJn
        MFU3NzY0ZkFLd3lEQ1dzNlFQcmUyZWcKLS0tIHFzc0tHQ251Z0lsdHFYZ1NOQWZP
        NkdxS1R6OUhoK2Y3aU1uenFwdDVyOTAKvAHu6SP++c+N+aQgAco2ackvN6F5kUmZ
        Mn4UfmTihBFNfAVgEimWjS/bLklRi9E4QEYnpms3W/RELgX+4iwftw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T02:18:09Z"
  mac: ENC[AES256_GCM,data:Meu0XMX0r+5Dpo14b0dxTeqvnx/uIpJrXAdngFOfujgmL/mCFh0pNydnjxQV9q8BlGX553Rko1mTlZdilZDomFvQBg8TsEauxJzIzlDVkkmcpuVl63cWpChPfjm29Wc4ac6Q0aBumj1gf68M4yMqABwhVvzgswk1r4e1FpNDna0=,iv:Iaa5v4j5p8r4qD08W9ENDx2/XM1cTyP4AxQi4VXOxsI=,tag:y90znD0pcDGQR4YyplXLhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
