apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:vwDtETTP3ufJZ10khkF0Antzqn5IUFDuhF5vf9p4cxz11ye9Qr+Mmr3zbI3DnJEPN/iHit0=,iv:tS1A262NhsphZB2XGTobzxM81XpKo3QZn8eG8s2KV6A=,tag:4SNXscUK+9DdYXdtv+a4xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR09nY2NORXpSOUNpUHBv
            RGZEV0t6SzNJMXNnQUJvR2Rmc0JqZXRBQUZVCnhaZGJ4TFJ1aUU2N1pCbDBUS3hG
            Q0xGZlF1THhGRkU3SllKVkdVa1NNYWsKLS0tIEl3emJ4OFoyazVqSFJROUFiVysw
            VUlCUUQ3a1F2aUJMT2xSUXJaQk9LVUUKMJSx+sJXMTiBY8Iyf9Y9ErnLt3qTF94Y
            vBrpS4rGuUbQb0sYDAEwC2VLKNZgu7pjjnnGYy/upCBef86TpkH9rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T13:07:36Z"
    mac: ENC[AES256_GCM,data:lFRohEWgFIX8TwfL9dPhimZnst7mGlGy48BBUsfi4609Bz4mu3z4OYGCrrqAyYLStodEyEhO+HaDKEK80SVLp3JXbPy2RsuL91PSqsNG32q+3kgXcyi9tt3P+7gSucjnC7z/vnWnA8TLl1JOQoGUF4yunWrvzaeNrIBeapTAZYM=,iv:P11nNpIwpGSKyo4q5ZxvkfkBTK96sbEkl8OOzvFK/Tc=,tag:C4nAdUib10A/hZC2wZ/K4Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
