apiVersion: v1
kind: Secret
metadata:
    name: ollama-apikey
type: opaque
stringData:
    users: ENC[AES256_GCM,data:1AZbrJmNHfPYAtwxKGug36Ze5fuJFf47UVnFvFkpIXDIRWgr6Z6r7dyA6KB+ZjaOPmEzkIs1ReuGkvf33m+6AQ==,iv:2QcfwhNPfw8ncE1fVcizbukBt6ALAiRrUh6BgXxGuKU=,tag:Kpxh5XhtE/Xj3VaE4N1Wsg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dTZNT1FkWlgyR1dqeVJG
            RVFjM2Z5aUx3cVhuY2hsQURGbVkwVDV5TmxNCjFETXd1MVJyVXRGYzdCSUFNZXhz
            dlQzK2NXem55eFJVY1NwRTdsSGRYNDAKLS0tIEdHOHJoNk1Hc1VRNGMyV3cyMWZl
            ZE1SNjliUExlcFBCWXNqRlNJTWU1UUkKXhFC1eRtR1RvgusoEt3Cj6O6tsTQig3J
            aEQhOOrDOG82GNcsU8uPg3U+dvwXsEXn7HSPfknKc3FE1LVogNA4mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T20:26:52Z"
    mac: ENC[AES256_GCM,data:Mm9iQAwywpP6kP+IO+W6OewUXhM6MNzSvcR5x1arw7r4PBP9tS74AhP6HD615TkmI+jY9F1h0fcA06buEHcPLWLfcJuEuiJ198PhAs1ksaMu4bvx8HNY7Pm8hlZn0FHoz/Ft4Kb3R4xji+DKJGJYh1nf07t4MX5JCKSpAKcpHjo=,iv:hYb03voV3Ed/6uuni0HdKBhhGOMqRbq6g/S5pq8rR5Y=,tag:Ltw9bkkMu+lrzaSIWfD6Xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
