apiVersion: v1
kind: Secret
metadata:
    name: toolhive-embed
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:rLaWt75h/cGctQWv8V6wnAIDrsy9NJ68MA==,iv:3NIfe0Y4b2yStsCcwPcQRhWNGIaDj5Nkfv6WrP7mqlI=,tag:xy8IIvxRPNKsLJCKguPiXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczJPSkg4bjJDUGpVUkE5
            R3dEYlZnbDZ3YlZpUUVqRkY1bXhDL3c3d3kwCmdYMUY2bWFUd0N6UlFyZXp6MDBU
            TTR2ZXJjK09pMS9XbU9Xb1p6em1tSnMKLS0tIGJnUVUzb3pCWHlIZTVhOXlwekFR
            SEpMKzA2emR5eGZaaGdKdTNhdGg4Q0kKj09cPOtz9iNoT4xozv0hwThlL4cKt7AX
            XYGGu1ChmDcqUSaiDps4eSZ0x1umnHSiGDLIcKRkY+nQMndYjtS/cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T00:41:23Z"
    mac: ENC[AES256_GCM,data:LMTGtHxLEL5q5J5CG4QxbmLd6PfRNiv7Ye/0dkBCq4UwkShrWkZI3u5InhrV8rBtLMV9KMAIpJxFfpe1VGprZ3JJnq/BaqqcJKzYiXfIcqoutJD6ENw8FSPD8Elzwf1Knk5eVmKQa7FD1zo/xTyiQz1pDXuPsXsstAzcy6yAoxo=,iv:OZQ0FOR3I5PE92ShEVOgnNE58q8zORgvbXPe2NAQUDI=,tag:3Md6ZwmqqIDkosfwWWQSag==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
