apiVersion: v1
kind: Secret
metadata:
    name: toolhive-app
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:rLaWt75h/cGctQWv8V6wnAIDrsy9NJ68MA==,iv:3NIfe0Y4b2yStsCcwPcQRhWNGIaDj5Nkfv6WrP7mqlI=,tag:xy8IIvxRPNKsLJCKguPiXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczJPSkg4bjJDUGpVUkE5
            R3dEYlZnbDZ3YlZpUUVqRkY1bXhDL3c3d3kwCmdYMUY2bWFUd0N6UlFyZXp6MDBU
            TTR2ZXJjK09pMS9XbU9Xb1p6em1tSnMKLS0tIGJnUVUzb3pCWHlIZTVhOXlwekFR
            SEpMKzA2emR5eGZaaGdKdTNhdGg4Q0kKj09cPOtz9iNoT4xozv0hwThlL4cKt7AX
            XYGGu1ChmDcqUSaiDps4eSZ0x1umnHSiGDLIcKRkY+nQMndYjtS/cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T00:37:20Z"
    mac: ENC[AES256_GCM,data:aua+9NiMjac48R9u2dYhJg3zG94eHNx9MIiF24DR0cTH1187ISVaNOSRvtMCY56jQUAeE6es+0lFPcA1zEpec6hlYLnWogxX4Ot43GBN6ygNddamEsKVqNpVqfpv02X63NoBJNLksGtL4MZ3oUj0lh9CDv2Ku82s69DxRceF3U4=,iv:HxBGG4z0ltFuIm7EfWSsgTH++Hk0OpbRvPxnE3tCvwc=,tag:qKCrh46E4V/4dUzdl+cing==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
