apiVersion: v1
kind: Secret
metadata:
    name: basic-auth-users
    namespace: default
type: Opaque
stringData:
    .htpasswd: ENC[AES256_GCM,data:M3lKlZ2Xvp9IiV9L9Di3Cu+Sds7KEsTINSb+jznh2eioQH/NRe6yXg==,iv:9KwdakJiBC4Xjr64MNrxlQw2olt/Yy+/P+LJLXQaFSw=,tag:Ub+ro7gN+x45iwoCzSJigg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T00:29:49Z"
    mac: ENC[AES256_GCM,data:3o9D5oV4hW9aW5ScEdkvh9Yry1UqxVgHeWYxGgkkcsruBjDQeDdygePb/hO+hkbw3jOJQTq5pFBA6d/fJ45TEqoM24hKhRWPnmrgNgicsJfAf3td4YH5ayLBIh6kCrpCeHT7RRos8pBQwVjPJZ0B26GuUrWPIQglT7tkr4ey4go=,iv:FiWXihXjb55qETkkCUxB3JcHTd2l+GiUXa9KrEEGYwE=,tag:XNHhYjErQ3JJLdQcft4BbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
