apiVersion: v1
kind: Secret
metadata:
    name: basic-auth-users
    namespace: default
type: Opaque
stringData:
    .htpasswd: ENC[AES256_GCM,data:Pu3RHp3Ria2uQvPRwrZ0G40qiu+EtJlfunUJXXDiOIF0tPwIsEllEH5Gae1sQxJTFtus0gOPd2So5iny7z1TJ3qzYSFFHQ==,iv:pMCNHyPOmccDg6ev0A97OKrmyKC6v3WzYDNHsov+VKY=,tag:IfcSW9tVD04okkciZ+IshQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T00:23:18Z"
    mac: ENC[AES256_GCM,data:KkCETS3lu6TiQSQkCIe8zyKUuHBbTjkgQnh7HhgNlK2NVzl6QhIU5qDKr41yWBRuSSIxM3FueMgq2eFcXaPyJvM3VtQNIO/oaQNVH3S96CZ7KM7V2ZP76lQM5J29be9NVyrQj4Nzx7xHYBc2Vgykc8HXV50T5H0XXoWcar3Us38=,iv:8GXQkenLZ/0EDz48F8eF/Qodd0P2moVN0QKhXBkDco0=,tag:Y9CuGCD5fbYt51yKgzJssA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
