apiVersion: v1
kind: Secret
metadata:
    name: basic-auth-users
    namespace: default
type: Opaque
stringData:
    .htpasswd: ENC[AES256_GCM,data:C0E7f2LFUlBMMqO5YKigkZtmSeSV5OkeXLwPNhfXIBPeGvoLC2lUiRA6XC7XfV2n2MgcLWwIsS2MXTcDb+FwQLLTgmkce5+06rhRmbEw4sApH2cc8jCqIdxgkMBDFPLQ2U3WUXKWTLBz7o5tuXYiFvo=,iv:AA2EG9X2bN09p7piBQ5hCklgy+IaKYuU9HUBeIhqIas=,tag:Y/ET4m6SvsTsvCOFr/jN3A==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T00:07:02Z"
    mac: ENC[AES256_GCM,data:TnZ3gpE13sATIxyxXNrA1Q6xDwz6r2QGOw+g+SQGCKGpdXfuPcB9/KMmilb/q2CmJ5ip+wXKEgz7enV70CAS4B/zEVEZ0/wxlS71pDQz6EQkMvjMYAuO09N2Pe4potSsJdBGOTip1RufgebEy6FdLYB5Ah2YZYwBXBA9PhQVUgE=,iv:BkOrPXmZrrSBYzxq+xzgWfNVI9zDuK1kGWoy/5nsKVo=,tag:h/KCBA4k8ZW3hMR+mmpZkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
