# github fine-grained PAT flux-notifications
apiVersion: v1
kind: Secret
metadata:
    name: github-status-token-secret
type: opaque
stringData:
    token: ENC[AES256_GCM,data:ZIzrwz1WQKaOuRWHdpGPIe8vr70rj+ntlPkNsFO0C/kxQdmeG/2prURSQFwx97IQNOr6LajCw6BRKqp/aejNR1eQ7OP3+AF6+2dnW2TP9JkTaL76Vgfzp8hPo6+H,iv:il1DHEg9SMlwIe3F5IuAVd+N2YRcUzhl0szwSZP+pSs=,tag:8QExw7d+zZ7h2XhruSIqaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMnQ0VjdzcTYrUzdRTzFs
            Tm9YL3oyUy82RklySVdHUzN5b3RVSE1zNm1vCnhaL25tL0c2Q0V0RThQU0NMTUlu
            S2t5RTRzdExtbDJGWEFBdU9XbHdKVWMKLS0tIHJWVnhFMlg0a0N1cU9ZdDQ0R3dK
            SXYvL0ZKZTBheW5oZzZoa2JETU1URUEKtp3xO7HRZ1Vwg9hUcMS6+lso/yNHFPWa
            GsS80pY88TFnytB9+B29jVbYU0d8dJX4zIDc2udFSnt13jilHoMunA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T00:28:27Z"
    mac: ENC[AES256_GCM,data:hNRmxz7TvEyXpbIuV4Tdy9hk/oJwQFSfbnVPrjR01uguIZIKrVqKXZ2+4s8sVSDlbc8fU21lZIIWKDp58N4FbmtJO0aAnjj5hplzNFym3lLvJ96rtbgwfcY4a3OW7oGOqVzfbTWHbb9IJthMtqTp6OoAeYrbvsTyjfx++752d7w=,iv:HuQWPgFNZzaEaYyir27wkLTYfX9o3d46NC8JqwRZ1Ys=,tag:YxVmJQGk3WEv6gy2xcvsuQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
