apiVersion: v1
kind: Secret
metadata:
  name: github-status-token-secret
type: opaque
stringData:
  token: ENC[AES256_GCM,data:6btPZS9DXcfJrAP8bYjE9DkQOxrUue7MUkMEUEAZlRGD3fsajrX7uA==,iv:Da9Kpc8K+/scXiKsvlpldia8To0Oj0bGJ3YP1L6JsVk=,tag:UVqbPNfANh6TA7hI/qEMxA==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMnQ0VjdzcTYrUzdRTzFs
        Tm9YL3oyUy82RklySVdHUzN5b3RVSE1zNm1vCnhaL25tL0c2Q0V0RThQU0NMTUlu
        S2t5RTRzdExtbDJGWEFBdU9XbHdKVWMKLS0tIHJWVnhFMlg0a0N1cU9ZdDQ0R3dK
        SXYvL0ZKZTBheW5oZzZoa2JETU1URUEKtp3xO7HRZ1Vwg9hUcMS6+lso/yNHFPWa
        GsS80pY88TFnytB9+B29jVbYU0d8dJX4zIDc2udFSnt13jilHoMunA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T02:29:07Z"
  mac: ENC[AES256_GCM,data:jBn6TI3+Cm+YJn3OMv1i8ofALMtzD9tFtQkIpFyzUOHhrX7sOQkQ080E2Ui+I0xzwQkCKnrn1o1FFXyPEfhJpQjDwMYvZcNfvwlEMg2NR4ktsbmNXaZ3xYH14EggczxawR2FeJaNdG7Ow18H+A7UtYf+XI9s8Obx999njDDXeBc=,iv:OBTwpHTPHfB6+YIkvBzVBlyaYfloOVUDxMi2J3CanjU=,tag:2xMqTpphwG97LV2O5YzbiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
