apiVersion: v1
kind: Secret
metadata:
    name: github-status-token-secret
type: opaque
stringData:
    token: ENC[AES256_GCM,data:/hBGN6nnCTtUoH1pG/pbXf2PnJzlXdYWllPcuSdcm5dIZ0CEQIM6X0e1VYyrRZX1U0vZJxY4JD2pLx+fpm7VAh2uPlqW7AhcpDb60pax+D1sIxwG+kCSDFekM4qI,iv:s6wRDC5av4y3TQHJPzuUM91imxY7POeTRgiNdW0sRaE=,tag:TRuoJlba4L5L8VI+VALyTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMnQ0VjdzcTYrUzdRTzFs
            Tm9YL3oyUy82RklySVdHUzN5b3RVSE1zNm1vCnhaL25tL0c2Q0V0RThQU0NMTUlu
            S2t5RTRzdExtbDJGWEFBdU9XbHdKVWMKLS0tIHJWVnhFMlg0a0N1cU9ZdDQ0R3dK
            SXYvL0ZKZTBheW5oZzZoa2JETU1URUEKtp3xO7HRZ1Vwg9hUcMS6+lso/yNHFPWa
            GsS80pY88TFnytB9+B29jVbYU0d8dJX4zIDc2udFSnt13jilHoMunA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T15:24:12Z"
    mac: ENC[AES256_GCM,data:vtTPJXKUQ2lBOjfuAlHc50JMTqnJp2F1hL7PZadxPxZPqDek6AWdbJRugCQOyg6K/6DNRBiH4UnRbmXGPqVo8D/OjUG+af1JRoFV/UjmJFa2g1CR0+CVTVInXdeQDMgiHeRdKIrPtIeHt0ZAN6w1QZBkCuFm6BH4gdmuLeuArDM=,iv:CSDsTwqzTXH9/h5eT3Fvwj6BzYYa/4NPfRcilmxhY9Y=,tag:IiHVKgNwxUs3XBklQXi6SQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
