apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:LeEvP0SPmHew,iv:lekUDA5pjHJ5H9JstnR0q8A/ng4+E/M/WPiA+CkHq9k=,tag:F2kKHygGgb51VJqCYFrNHw==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y3FqTjAwSFpUWGxZUVo0
        dSt0T3Evakp4bW9oSkVKWUJNcTJSMjgxeWljCm9UU0ZEeVdTSU5EVWRwK2ZPMW1J
        YlBBVnZLSWc4dTd5Q0UrM1JEaTFYVDAKLS0tIGJ3clBsdkpzbitIbTFmTW51NHJB
        eWFiZldVYVc3NFBrNmo4V1dzUENVOVEKTkNk9gS8hTXorBPHYmigj8P+B3hGop03
        XaiSzig2wlzTEcgK0ILDC5RNh3wNAL6lwyYk3dtubBPvUASLWkT44g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T17:22:15Z"
  mac: ENC[AES256_GCM,data:7cLRzBaBEPc15nPLW5L5Y75hSpXuaVGaQM6AF4R7tYrzj8FycwxoNX5TJbJMa5fFFxqueWsUhqntp/2UyjMWkl9LksnXaJFrzLS/bFQBJjS3tIEohX8afazVwr5noayKtNZGMT1J7DQPZHgRjLPjQXplU2atTE5kmCP+HVU/yMM=,iv:/OMhrcHkRJnP0SBRbHZB/rGfKEEaFRVwLqoomiIx5Z4=,tag:pr29eY13lRuIUiZKNZgbVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
