apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:zjt7mnm7L6YE,iv:pZjkRmKiOjJcFd+RynJ1cixGZPxMGx4IflmCGH7kNnA=,tag:k8aMnTgqLLxe8PWZfBLgsA==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRkQ1cHJoWUc1SGxtYlJS
        eDRsaHQwUjlkaTNyN3IyQmZjVDMrclI4R1JFClgzUm1SQ2kwTm5RN0s1QnNxTS81
        U0x4Z3FQaDQwN1NBd0p1WjlQakRTM0EKLS0tIFluSmdDeVVxVUZiK1Q2K1JTbjdD
        QVhBdXpMSkZua3hCL3hHK2ZNYTFhOU0KolfjY/ltMqbJCn+F/fnLie/w4ONUxQQP
        3DzARX5UFg1GyE7LjigtgQPH1xs1iiD8dOYB7ZV5BKF0wc9tJPhN3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T02:18:10Z"
  mac: ENC[AES256_GCM,data:i/NVZVdNCtvKtWvcM5wDJAmFCb2YfnQy8xr89RZ9ugn4o5aqXn4vpJoVPqErXguVvRJV4o6s4W+iAxmrk54l+sgAnGs1iJ0II1vwed3+7+1N2Dn8qv2za8pmLkHWrTfLCKBraP65PVASRZb3GtwSIGLpDwELCpdc7k3zY62pkxQ=,iv:fCCZfWQtfeVmyoPkgvOLRAh7IOAWTFE4PxLg0R81ix8=,tag:8mGdmv4X+tBa830C8nRwdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
