apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LeEvP0SPmHew,iv:lekUDA5pjHJ5H9JstnR0q8A/ng4+E/M/WPiA+CkHq9k=,tag:F2kKHygGgb51VJqCYFrNHw==,type:str]
    SECRET_ACCOUNT: ENC[AES256_GCM,data:490l4g==,iv:izhm0ft/nWoDhn++53ppEB4r90ju5ZlgalziKqXkTBU=,tag:aHIVETUtxd7pbSiEtxPS/g==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y3FqTjAwSFpUWGxZUVo0
            dSt0T3Evakp4bW9oSkVKWUJNcTJSMjgxeWljCm9UU0ZEeVdTSU5EVWRwK2ZPMW1J
            YlBBVnZLSWc4dTd5Q0UrM1JEaTFYVDAKLS0tIGJ3clBsdkpzbitIbTFmTW51NHJB
            eWFiZldVYVc3NFBrNmo4V1dzUENVOVEKTkNk9gS8hTXorBPHYmigj8P+B3hGop03
            XaiSzig2wlzTEcgK0ILDC5RNh3wNAL6lwyYk3dtubBPvUASLWkT44g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T00:05:42Z"
    mac: ENC[AES256_GCM,data:x/jhDHrtza013/K7HrFi2H8i7IDKOQCFcIhGNPJaVcskI6wDvnMMEE8sxhxh4hsUguKG/nNdgR+rZDcRo5Xb2fhTXIFUYdqVZtF9MkuDaXsMKt2hqyBoagC/exjJlRtnw42iis+kkJba4zFdpjH9vvIOZFyxGf/otwk5yJ//zzM=,iv:hKOifcgSUdV5QKWWIfd7iQrKiqwE3P3VS2Ji7HAV6Ho=,tag:zumRyp8vuFHz+Y40KtXtXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
