apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:Rn9/lrmrAQ7IGNAe/c7WMHNMIeIBcwSF8X0O0juMdoKuf+NwtZYQIP8DtI9uAjzYx7AG3nWpYA8mBVXxXU7grA==,iv:z8uHLy4U0uXizB3rOivkl/ySL5HGeiDF2Y+I3Hc3Pq0=,tag:B6SObp5p2nnXp/aIAGwX4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWm9xM2ViN1ZNaDNuenFq
        QVFka1pjMXdvSlVxWS9TVTlBaFFJSkE3aFNjCnIvL0tpQVpaRjNheGVOM2p6Q2tv
        THg5bDUxZVhHSnhGdE4raGs5RUNPd3MKLS0tIDlBSWlpZmJ0T1B2YlMzd3UxZ1Fh
        YnplN2t0RXBsZTJTWHg3OVBQZHdTK1UKP9bHSkrpkizRu8Il31XQilcHaYdNNONn
        oXSbiX5zpTRtUdg9BOlxq4dg/6AUD9qZXs7BZPGkG2tKoG+Ivtc2+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T17:01:53Z"
  mac: ENC[AES256_GCM,data:Dr600hgNJORB/K6Ny22vU7f2CqwuJ0ey+FXNYiL30Q5ZaAIJUPuNiiCmlViOU2GkBx58jR/wzCY5tQhLRLoejAvykydjlSoJSRaU6ejMVi1NWX7ikk6mKTJo3EPTTYc5Q9vV/rkhschVX9UJCAxjcVHjrwGPtxRRP4E6yiv2E9Y=,iv:NDI3o9pEMFuP1Si3iFQBsf0nU1kdBdwo6ZPWp3KjBHE=,tag:67jM/M52zdifXzhnsQCI7Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
