apiVersion: v1
kind: Secret
metadata:
    name: hf-token
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:Z/YG4Bd/+hq+n97Xs2c/RZE47t0dV1NfXnhTPFc+ruiOvNJAag==,iv:B9UnxxIiRA7EbJP7iGZk4WfKshEiB1cpK69qF7MCuMI=,tag:ba9YBaU/1CTmrRYJ8JRRaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWm9xM2ViN1ZNaDNuenFq
            QVFka1pjMXdvSlVxWS9TVTlBaFFJSkE3aFNjCnIvL0tpQVpaRjNheGVOM2p6Q2tv
            THg5bDUxZVhHSnhGdE4raGs5RUNPd3MKLS0tIDlBSWlpZmJ0T1B2YlMzd3UxZ1Fh
            YnplN2t0RXBsZTJTWHg3OVBQZHdTK1UKP9bHSkrpkizRu8Il31XQilcHaYdNNONn
            oXSbiX5zpTRtUdg9BOlxq4dg/6AUD9qZXs7BZPGkG2tKoG+Ivtc2+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T20:07:31Z"
    mac: ENC[AES256_GCM,data:U/zCvVTj5Wu/1a/1axndy9i9SIG+1RdAgvj0HH21qufl/RceesbTBDL/wvRczGmjOgJuI4Nz29Oj/+PnyHcehRCc2PIGu5mOUx+v6JpdbNab8bqBGRwVaSivvDy1kqh54wT7S4ePzyR5rXDDL/RvX2lTaYpX4fetinrvWNIKcMU=,iv:JUvS0hSzjMaX6LPD6vCav/3ROytwkzGpt7Uod6lArt0=,tag:tgBF96qIfbAn9Z1HVg7Nhg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
