apiVersion: v1
kind: Secret
metadata:
    name: ht-token
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:Z/YG4Bd/+hq+n97Xs2c/RZE47t0dV1NfXnhTPFc+ruiOvNJAag==,iv:B9UnxxIiRA7EbJP7iGZk4WfKshEiB1cpK69qF7MCuMI=,tag:ba9YBaU/1CTmrRYJ8JRRaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWm9xM2ViN1ZNaDNuenFq
            QVFka1pjMXdvSlVxWS9TVTlBaFFJSkE3aFNjCnIvL0tpQVpaRjNheGVOM2p6Q2tv
            THg5bDUxZVhHSnhGdE4raGs5RUNPd3MKLS0tIDlBSWlpZmJ0T1B2YlMzd3UxZ1Fh
            YnplN2t0RXBsZTJTWHg3OVBQZHdTK1UKP9bHSkrpkizRu8Il31XQilcHaYdNNONn
            oXSbiX5zpTRtUdg9BOlxq4dg/6AUD9qZXs7BZPGkG2tKoG+Ivtc2+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T20:00:45Z"
    mac: ENC[AES256_GCM,data:Un7jsHjD9viwRa3ES5BcgsvPZRphXSMS74ayJFx8v7paFvGcvMt0wZu6QVLzI1ITLHEMmwFBocv3IiBakogfvm0di9JGO/INFi8hY/QiWHBU2N2KIi5UsazTBwKnlZiHJ90lEj0pTbWF8vFsLmKpyImyxqwdIynoxnHfv6cWbVg=,iv:tRYeDVy/g4pZj6itSlItsdgNwfkRb/+Ew7kKMF78x5Y=,tag:2dlI79kZmM8W2O6JggP5zw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
