apiVersion: v1
kind: Secret
metadata:
    name: backstage-s3-secret
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:5TCIuqi4mkr/vsY8AB920bYd/5E=,iv:NPNo1bGJ9UcnbamWpmYXBy2EFaakFPGoW4vnjlEfe4U=,tag:mIRG/AczWzKACZC7C9GdOw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:+4r6swZ5Phff/WxzfXbj5ekEESYSl/qWoGWTh9ZnKmQFxcjBSfwl9w==,iv:nhJBC6luODrkPMAN7BQwNaks/x8IBQ0J7r9Irzoi9L4=,tag:uVn7JFwrUHE8AjwHZrNV3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2JvdEhoRitML2E3WVFj
            U0tyWVlabEE4bDdlWFIzbk9nRk9ZQm1HMXlrCnRrM2VyVDFrL2FZekFsL1hwSERn
            WlB3MG8vNzNydFhYa0x2SE9qT1JvZmMKLS0tIHlDSW9aQUZINmRBazNoRHBMTTV4
            clowdTVPa3FuRjBpMG1Ua251MnNzUmMKwSYMVtBw7B+69daX5Hn6k6LKJx0dSBJ8
            2csuyhhO1sEzovjc9IHa1m4RM1dDVabArPvhO09V51f5vB6XQi36Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T12:11:07Z"
    mac: ENC[AES256_GCM,data:lE3G1ZEsZcKBnIgr3qzOOvyakXUQSQei1rcI9UqIEbO1ZXRL8q7aNKxG6rDGpHZhV/nn+WOKOUozXcvxpSjaComHYs+90Oysk3ASlRLYjpnd7JZx0sJ06MVu2F/bQunv+AvA2wOW37WkJfEFyXahOjem9gddJvwz84ha03+2R0g=,iv:ECWThH7t2xYDdsLuwQiBasirx3NnE86A7bKlvavi1xE=,tag:q9h3KKXPNfSig59yGYwpvg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
