apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:AvHNa68TjJzg6XuMTe9X9KBeJLWnZ0ZZ7to2i3JUGj8=,iv:JYJoso21gw9ZliOawqxxq5srIu7OWD15lN8rtss6SGE=,tag:Xes7EK/95dOlqdrYM/Qczg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobFZzU2RvaFpOWjhSYm85
            REtmenhmL0dXTlJnTEtVRmRjV3FoK094MDNZClI5Zk5QQmxPYk1ycm9WVkY2bWtt
            VmxDSzc4djhSaUxsdy8xOUFkYWZ6ZTQKLS0tIFRDVy9VY2l4Yk9FSS90U1ljcklJ
            cDRlb1hWSTJ5c0VYdElTV3VUdGFLUlkKd4juVnwWq3HL5ByRBH7Q6332Id+dya0V
            fk9Paj5z+Yh8/U8y6Fbb5HMURJt4/XkaX14F0VQ9SfK6r0p2VUP3ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T14:44:22Z"
    mac: ENC[AES256_GCM,data:YZgfZPC9Mtqs1CC/vSDtAmXN7WdacAkmuIo7TS0nnKuzqh+SBC6fBu+NXIosK1zUfw4ZbI7O5DkPiUKOHKkjXFXUpWuRkCfK+nUXOWjQa/69v75CFgxqiKOeiw2RyjBxy9ar0neTatefjSEFNgkunxIkh1DvrxN6aa7tsQMXtOw=,iv:e2MbqX4+lEdhkC3Rifz1znDS9WSjTvOTCxMJQ+up4ew=,tag:1HxgFW2EaddhbMMDBvykgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:qjVi0Akheiztpm0PVvkfsHhgELlfXTeaInBuqUOg13MlnzE5sFs1SA==,iv:q1k/fbp3+mDJmzo/1NHnzErwOnFLV8K2dsPYxDDcFkU=,tag:Fwk8oWC5bVHGKQ/EwVbqqw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobFZzU2RvaFpOWjhSYm85
            REtmenhmL0dXTlJnTEtVRmRjV3FoK094MDNZClI5Zk5QQmxPYk1ycm9WVkY2bWtt
            VmxDSzc4djhSaUxsdy8xOUFkYWZ6ZTQKLS0tIFRDVy9VY2l4Yk9FSS90U1ljcklJ
            cDRlb1hWSTJ5c0VYdElTV3VUdGFLUlkKd4juVnwWq3HL5ByRBH7Q6332Id+dya0V
            fk9Paj5z+Yh8/U8y6Fbb5HMURJt4/XkaX14F0VQ9SfK6r0p2VUP3ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T14:44:22Z"
    mac: ENC[AES256_GCM,data:YZgfZPC9Mtqs1CC/vSDtAmXN7WdacAkmuIo7TS0nnKuzqh+SBC6fBu+NXIosK1zUfw4ZbI7O5DkPiUKOHKkjXFXUpWuRkCfK+nUXOWjQa/69v75CFgxqiKOeiw2RyjBxy9ar0neTatefjSEFNgkunxIkh1DvrxN6aa7tsQMXtOw=,iv:e2MbqX4+lEdhkC3Rifz1znDS9WSjTvOTCxMJQ+up4ew=,tag:1HxgFW2EaddhbMMDBvykgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
