apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:AvHNa68TjJzg6XuMTe9X9KBeJLWnZ0ZZ7to2i3JUGj8=,iv:JYJoso21gw9ZliOawqxxq5srIu7OWD15lN8rtss6SGE=,tag:Xes7EK/95dOlqdrYM/Qczg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobFZzU2RvaFpOWjhSYm85
            REtmenhmL0dXTlJnTEtVRmRjV3FoK094MDNZClI5Zk5QQmxPYk1ycm9WVkY2bWtt
            VmxDSzc4djhSaUxsdy8xOUFkYWZ6ZTQKLS0tIFRDVy9VY2l4Yk9FSS90U1ljcklJ
            cDRlb1hWSTJ5c0VYdElTV3VUdGFLUlkKd4juVnwWq3HL5ByRBH7Q6332Id+dya0V
            fk9Paj5z+Yh8/U8y6Fbb5HMURJt4/XkaX14F0VQ9SfK6r0p2VUP3ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T17:02:27Z"
    mac: ENC[AES256_GCM,data:FlJMeKlHcJ/Gs5eyhBOxrSgUYJrOF+33a8jN8nXCLAUmoeWy2/F8aM7hVf0LizKsOPUGlD+hC7J0Kugxdn9OYy62fkWgahXio8zvt1SXtBfqTixFebLdq3B6VCt03Ih10BCxsyxxSWSdae2QMp+x+ETD+aSmub0AbypIj5vT48E=,iv:phCwU4uFeZeqHLGs3AVuVjXLAH9ZHgmd8uC1huvn+JY=,tag:1YNPq/b1o5gTGKAcuJBHSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
