apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AvHNa68TjJzg6XuMTe9X9KBeJLWnZ0ZZ7to2i3JUGj8=,iv:JYJoso21gw9ZliOawqxxq5srIu7OWD15lN8rtss6SGE=,tag:Xes7EK/95dOlqdrYM/Qczg==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobFZzU2RvaFpOWjhSYm85
        REtmenhmL0dXTlJnTEtVRmRjV3FoK094MDNZClI5Zk5QQmxPYk1ycm9WVkY2bWtt
        VmxDSzc4djhSaUxsdy8xOUFkYWZ6ZTQKLS0tIFRDVy9VY2l4Yk9FSS90U1ljcklJ
        cDRlb1hWSTJ5c0VYdElTV3VUdGFLUlkKd4juVnwWq3HL5ByRBH7Q6332Id+dya0V
        fk9Paj5z+Yh8/U8y6Fbb5HMURJt4/XkaX14F0VQ9SfK6r0p2VUP3ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T17:22:15Z"
  mac: ENC[AES256_GCM,data:HAGOlxe1S2xE6dCBdyqE/FsDyCZZhp0QEpiflnb7matbEMY9WbFnpkK45me9/2gZVFc9a3VmN2JjzYrKHhavReCDGlmm0RubW9vbhUHUbavozrDSgzKn+qiJZrrBzFwWJHl6Iv4eqNy+En1DXV3+oxKv06T7vKHbUG0m/6TftPE=,iv:ddS5QoS1Ajd4rmgJTA0W8x86omjZDdO15OuTBFSbWDs=,tag:TMhn6SJRG9HA4aMY44NTgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
