apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
spec:
  dependsOn:
    - name: authentik-db
      namespace: security
  targetNamespace: security
  path: ./kubernetes/apps/security/authentik/app
  postBuild:
    substitute:
      APP: authentik
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-db
spec:
  dependsOn:
    - name: cnpg-operator
      namespace: database
    - name: rustfs
      namespace: rustfs
  targetNamespace: security
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  path: ./kubernetes/apps/security/authentik/database
  postBuild:
    substitute:
      APP: authentik-db
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  timeout: 5m
  wait: true