---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2proxy
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: oauth2proxy
  values:
    config:
      existingSecret: oauth2proxy-secret
      configFile: |-
        email_domains = [ "*" ]
        oidc_issuer_url="https://auth.rnatr.com/application/o/echo-auth/"
        whitelist_domains=[".rnatr.com"]
        upstreams="static://202"
        skip_provider_button="true"
        set_authorization_header="true"
        pass_access_token="true"
        set_xauthrequest="true"

    replicaCount: 1

    extraArgs:
      upstream: "static://200"
      provider: oidc
      reverse-proxy: true
