---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2proxy
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: oauth2proxy
  values:
    config:
      existingSecret: oauth2proxy-secret

    replicaCount: 1

    extraArgs:
      upstream: "static://200"
      provider: oidc
      reverse-proxy: true
