apiVersion: v1
kind: Secret
metadata:
    name: oauth2proxy-secret
type: opaque
stringData:
    client-id: ENC[AES256_GCM,data:mFEurJSIBADMYMW7i6gPISdU09+No/1pfZ3cAADiBAloSRzOH5iRxw==,iv:U7MAuIOc05pTZY/TwZpvwpJsUAX11c6NHyphrhYd0Og=,tag:lMbe3t0JVUPeBxa4oSXK3Q==,type:str]
    client-secret: ENC[AES256_GCM,data:E0+dvYgH9jUdL3BurIcDZxtV1Qy+whuYNzzRxGik6u0hOVmr8gyUeXXv8P7puDVJ55gPsvWmdHeUkaPnjD/ZG4QKfUrVFznnAFjXU0Ofpvzf7uZCAslMQOJ0/ibCUOYcGjVoi3fVMT81HLkDzcVJdlO7HF1hw65TsOnyReBFQC0=,iv:SZ3c843Tag6660GuIAnLPSIDagaiYDjIMW/WI5hN9ls=,tag:bppDpQM0DvcaikHbISkWLg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:y0CLAL8nfkMbAc8p8R1q0jffmpD2mQY4GraAKXUMFNsDW3CxGDRuomjzzPI=,iv:57Nb7gJDstb+0HiTQ1VXZQZJXr7+XcYiLcI3s/neMDY=,tag:zeHOGA4kWbZZZIsQZYaz3Q==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T23:33:29Z"
    mac: ENC[AES256_GCM,data:XXi64JZmeiHkkpEeFVJkO84yOH0N/tcJa833ZN6v0+A4x94m/4uVptWcj/h+V543moeI0l5yZcyyg+YOhHRqRZMQ5++iVDDosjjAweZXjnWp8dltEItGJAWDwCS1vQwFI9vSusrstnAB1rvAa/NNB83+zTeXmqmhN/q7q1nr5ck=,iv:yqIo1MXlChb2KbwMfRcqgPo0lvf0t3GYzzoTMmatjF8=,tag:pDskABdZuMDXc6meM0Io7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
