apiVersion: v1
kind: Secret
metadata:
    name: home-ops-runner-secret
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:e6aZycxOgQ==,iv:CUK6imod7q8W4heRoJXkiS4e7r8JvhjNky72lJCy8+I=,tag:TNAzw1fHkUWxWq4S69dBmA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:kmOSCgzZgsEtQBxfCv3tY/d7iSk=,iv:MbK6og/zLBpiAnnZmnLForyyG7KPP1ITItXlg709sjc=,tag:5epjuhqoFZNmFtlDMLcIgg==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:Q+4qHdE2d61aEyLEIbLUNuhaqj3slulXkHrCMRqGBgwYaVsxt4vrAw==,iv:wCUIc5x0wIln/Kss/GFRdcVu7BbIK3ve38zbeGRyPeo=,tag:kvquTG9JagNN1j8utcwVjQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:40:53Z"
    mac: ENC[AES256_GCM,data:w6D4P9x36tpMia+uNjtUi+LrvHksTWkhywrPav+5+8rW9ybx8pJ6bhSQD+uYE2/eqtfoxJu0+jAD+9lOVRe2xcO/cU2m0dkdGyzSvc2AmvXmYM6bHSqbr2gYBlRWscwH2HLNmFUtUpetUaW3vbWG4OK7/FwKToSbc8l+ZZrQUMo=,iv:jJzqPxogh9/X44clDfqKb/ndPBFL/NAsDc9/fMVf2MA=,tag:ArAYVfmlhtrBhP4SC4S7Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
