apiVersion: v1
kind: Secret
metadata:
    name: forgejo-blog-key
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:BWI/vnwSH5y4WeOH2vdKdPKo+o56DbV2nP1JrUWytnkluZ9pNUQncubraNpuXiKeY3yhRZFXbAb/fh5eC6V10ocnQ7Dx/p6R+GG8UbQROn4OxAK51x8XUBoLbQ0EeF3K8a3sOang5zvNU2yQiluiYJQ0BFJ+ezcpRAuvZQRDklNsyTzfx9mBrCehIo3KSwSAl0tI2VARLbqT16t+jZPjqDROf9I=,iv:70eqq7mwsqfD+RcH8aPDc+puGjapUf/1sh+j7UTRbOM=,tag:7xOIIet7BHpVBlSnv3+tdA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:28:19Z"
    mac: ENC[AES256_GCM,data:pVl3i4fHWYwPrakz/LO7OvwjnhMYbSUIh5VpxXTz1IzW0t7AOM4qwbY5YHd3WAmAM6Y+AI4AB7Lw/Un7yO5vcNllomQkcc6rRmg52F4cBkDoq1FlHdIJhvzS/mkIMY1o3vIrX3ZHE8Iume9QMdG+yJgdkJveWnvbZvGGfkqSw4c=,iv:60h1SaLoJsnxDaMkNw3n3eE1gwesAXGdMhfrfDbS75s=,tag:1Qo+80piYJOiE+R5sjd0Ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
