apiVersion: v1
kind: Secret
metadata:
    name: forgejo-blog-key
type: kubernetes.io/dockerconfigjson
stringData:
    docker-server: ENC[AES256_GCM,data:v8eTs78wZ40d+HGXsiKeLrk=,iv:MpkLXLjgG628ynjFuNvxh/tsrMG1NjMbHEHdVIylKiQ=,tag:WBGg7VTEyR51c/iqq4PDVA==,type:str]
    docker-username: ENC[AES256_GCM,data:E3EQjw==,iv:7cMB/OLeBnSeZbXlBI7l85GKNuSHRxvU+aIly7z9d4M=,tag:TLkrjpgq8oBXJagWtSE9FQ==,type:str]
    docker-password: ENC[AES256_GCM,data:7yuC1fboNYT8IwGoPgRRyXnj+FjC8cLP8zqQdiF5kleHHwD42dFfqw==,iv:XhkbFf10z1P1l4j+vzV/faneoov5eFvN4SHVU4M+pLg=,tag:+y6rTBKW0080eiB/jk2uMA==,type:str]
    docker-email: ENC[AES256_GCM,data:TQUL2YAq8TP++oRinAY=,iv:RsfCxxryTFJztjk5x/CS8qFFRHv5A5ZMu+Sb9vdWr4Y=,tag:EShUCyGP7U9/hrAmvFwnOA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:07:26Z"
    mac: ENC[AES256_GCM,data:QkGJkoXiMMAMR/ixQMO0rb8lqRiE5Yh48T/TQCkb5hYCXLf9j24BD8gCXfSVGIUVrBSJVBvoJTshuW1Z9xTKGHdyRoaurcuU+N9b4vDWZPzAnNhDXvhVuhA0LYNWQZMZmKCxad8+HkRGw9yOBln0asuugCMQAymdZNjifGP1SpY=,iv:kvaywdKqoQQ8A+LnZryYk6VevCzf/8eH4GqW6lcSP4E=,tag:3suC5PXMgBKcS4eN4qIloA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
