apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:g249TbZC7KmZxdg=,iv:uSKISe+lECFJGvLGgcj8ymw022kTdpdwKIOz1IcHCQo=,tag:xXJMkQ3fbxSTtsydCiJfDQ==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadTl0R1Z6eW1CTHRmMk5B
        SlNTQS8rSXhHZVpZaVJYWlRkZzBQM0hTRXhBClhySUp0UTRyR05pVnVMZS9vT3J5
        c3FGUHovUk91Yld2dDUreXovOWN1WUUKLS0tIEZOL2JsclIzMUxiM3FIYUhrZjZO
        WFQxdzRVQ09zSVVQRUVDNUgyM0IwbTgKKh40hmguQNCfKmU/3LbaoROVCK/Su4f0
        XUYdkx9vsTMLWrkUUxm3Zc3Zr9G5LkPheJn34l24Rue5HH7SDpOEeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T02:05:45Z"
  mac: ENC[AES256_GCM,data:kHUGASWOkracDiYsqzi5nWh7axga+PMMi31et3ZKrkK2ajGjdn2ejuoX8OjdUiY7ertYvGzY/jD3few/0y3qh3bd8lDjwaBAGNFDNqD/ccdq3tjj7Hl29FnANIGqGLvMKKtHUKe817MVGq89DN8gZSkhXJiWzXf1tsSOLGVs4SU=,iv:3CFyQLOpudWBdk6aY0VPSUhIAazK+k+saWnzLM1stYo=,tag:VDAH6dxJHqPdDJCkyLWVig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
