apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    RUNNER_NAME: ENC[AES256_GCM,data:b+zcD9fegQZFB9/E,iv:sDjQvUzRQ6K/cvU/F5AYXN7r2Va+EcnKGAXZmipAStI=,tag:T+MbGovOxKIlGxpp2r7Snw==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:Vgcvkg0vgiOuTiV6qYraWPpNqdmfCXFOqbRsW61/82NfVaNcr/hdoKZ9Qg==,iv:aP18VD5brecbNLveJAIZJTF5mosNTITcB93H//L3ZII=,tag:7bQjyQQoZdC+P6uXleVftw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T21:52:29Z"
    mac: ENC[AES256_GCM,data:ASfsQO7CbmVlwfLwKECRpUwFr9A1akE1tj0T3BgBY5t5g2VU9WrzAQ7GXYagBrqaM4CYvzdraBdpJhstn71g1SoAbooKq5Qk5z7s6VyQgWEPaMtjKwOZokIS5dBz7sxjfBMjNFmogi55SmZAdrAvNHV6MAojFQmsAU5J09vr6f4=,iv:Ynfn51i985WxaOx4QIknekZse+BQK1i3k9C80Tja9Mk=,tag:+znU4HwNfqGry53xOVYHfQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
