apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    RUNNER_NAME: ENC[AES256_GCM,data:b+zcD9fegQZFB9/E,iv:sDjQvUzRQ6K/cvU/F5AYXN7r2Va+EcnKGAXZmipAStI=,tag:T+MbGovOxKIlGxpp2r7Snw==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:nIvsN2zQfR80XGHBC0wKUpqJOrXbK3iIJXY0WVp2tuhc+KVxHVZce3AVdQ==,iv:Zu7xDmJnkbhCuHbIh9ZruOGUscTHeqFcBWG5/JCYUm4=,tag:Y3O9Lm9tKOPpyWYBvE4zGw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:49:07Z"
    mac: ENC[AES256_GCM,data:NjCqRGxJT5v9Cb6pZi5RpV1ozJP5v0OpZUe5Ol+7ktX1Z3fz4hSgdRoUdBNB52BBpf6HK6B1PfYaxZoVJ3QKia0kVVls1JYnaR8f+0zkUy+eaM9LfjbI6jb86XpzzkUGxMxiHclUkRvbQp8NI374ygfMQAdfdwBZAeagTH/kEEg=,iv:NjWpnAdDZWuOJmUf3f0LeDwwSLRN7OBsICTnR1KmvEo=,tag:tQZAdP/m+uukekY0NgI6sQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
