apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    RUNNER_NAME: ENC[AES256_GCM,data:eKV4yQ==,iv:+otV0aKZjV8p8bAOtUaXUFO6q7Fh6fjkAnS31YtshDw=,tag:PFpNVVOatTZu3saCj4cs5g==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:daVwsiQxqaY85rHj2Q==,iv:r5GfcghvNh+qqvYfslzxqm1Iz4o8AR/yJDiuPRsMmL8=,tag:6+NezFAfLpakE6IsE3lofg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T19:28:44Z"
    mac: ENC[AES256_GCM,data:ZYlYBukowXFBQySy12Z+/c5hu52q+Xxp6DVstFtAy8s7qT4PiDkiJl1cb/m13E51LUaB391yHywZPEP7+FS3NAgwGxJ1kwZVT/ePV3MUcWtpChVplLuHB2TSoHNUqd+yIA2bQShkHOkLWmi3xJHjQNfq+S2uf5deQy8E8nDMwiA=,iv:gTiWDndPxZlfNWdYAsI/hUgP17Yo1Zlsw/ypjGAbfMs=,tag:S9lXqGe3vvqPYTqA6vLy8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
