apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 2

  storage:
    storageClass: ceph-block
    size: 5Gi
  walStorage:
    storageClass: ceph-block
    size: 1Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  monitoring:
    enablePodMonitor: true
  backup:
    # Volume snapshot backups
    volumeSnapshot:
       className: csi-ceph-blockpool
