---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 2

  storage:
    storageClass: ceph-block
    size: 5Gi
  walStorage:
    storageClass: ceph-block
    size: 1Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-cnpg-s3
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  monitoring:
    enablePodMonitor: true