---
# 1. Bootstrap Issuer (SelfSigned)
# This allows us to generate a root CA locally in the namespace.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: security
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: authentik-db-issuer
spec:
  ca:
    secretName: authentik-db-ca