apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./db.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./objectstore.yaml
  - ./ocirepository.yaml
  - ./scheduledbackup.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: authentik-blueprints
    files:
      - brand.yaml=./blueprints/brand.yaml