apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: opaque
stringData:
    authentik.secretKey: ENC[AES256_GCM,data:QB+zChGrVEGMPattv0VXG5dAWgK1fEdCpY+vTGQs6dZYnK0gXt0FWwxH3JAulx56q+Ms3rAikFWH2fjM3i3rOAewVyrLdUHqJPsjecH7ooE=,iv:FuritzArTqO6KS+dZXtR4hVi11TIcJ30RJJB/K2p2Tk=,tag:f5RPLixR4l0f2Eur4WYdyg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T01:24:58Z"
    mac: ENC[AES256_GCM,data:lR5d1UN7mFnvWIn/pCCmFZ/GK0XqYc1CEMh31CZiUKQrA3BZnAqmAKNc1zRYT2knbGCM7COb3JtXH7EcuSu701URI73Z4uIwYRmgzPAoxU3hRM+CPcfzIRJA5kG5uBXTpWhT7w5Vnt6f479smMClTR55fLXsDvwKIMYkhSkint4=,iv:/QeVRVdImbYL5h+Gdqc7zD2vjjYMU3Sk3W9b4vsKdu8=,tag:vq36WbzvRJV/lxJJhU60PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
