apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: opaque
stringData:
    #ENC[AES256_GCM,data:kdxhkR1bUSEIRrlouDaeoa8mm55pEF+YcimUZa+u4LkyM0PCPnpyoAOvTymEn0CJWyxS/Ayygg==,iv:KLQ2jevvL0wL/9vFIYoD1KGPyMJobaobpOFPMHnVcvc=,tag:BlVFCzrsYrrQb+DHVEQNbQ==,type:comment]
    #ENC[AES256_GCM,data:RtajqMSN20AkGQARz8VgG/TPfZMr45OWAw9X6SaYD9zD,iv:JQZHwGqYjeYSlArPWN5d8IYE/d6iq0TMupmvtqCER98=,tag:jMrJ7O1PwuICJHr5DG02CQ==,type:comment]
    values.yaml: ENC[AES256_GCM,data:zIgBrzpr13WPS548Cb/WDPjzZWOliE6O4BLdD3CnWkjzMurVZMpZz0IoIF6Vst9ucQX8EP5l48lrp4TPcWZAkMVIma1OGBAEsJmU5wL37N7yS0mGYpbkpqcdM9QVVs+xB4tmCmbew89XVAqP4Om3Rj6Lz3ZM+Fm480iE/VHIq/mfA2cEWzozOFpJrHmxYOD3crC4wLFXAH4=,iv:urr7qvHlHwfbkQJOqrLTSM26junRUZQKaAWFLPypYrE=,tag:hI9Z5cn4gck4q6NsqNV2lQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T01:43:28Z"
    mac: ENC[AES256_GCM,data:pMPqnNaghIgYNzpBtZDVa+JMNuVIZPJmXRdfi+IAF9TFRNqLUKKng0h7UAokbKb5wUu0Zx+dETCzwoALsDK2PAQSCykQ+GswltjTEl2AAM8y237tMGEI6R5X16lAvLf6IOkP0VpMO/Gelt9FhdVlUMGpRlbT0a8cmrFeFPkZ/IY=,iv:iyvJpBb4x2gCOvpEpk6+H7Dm7/g1QTuEHZH1V1+8Q/A=,tag:7flBCKbFkXfhpmW2U4s4cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
