apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: opaque
stringData:
    secretKey: ENC[AES256_GCM,data:QrO317/FPIc2wfa0yKPuIBSsqJAd0cgGRFSrVliZL8rdCjeTbwWJfpsxb2kzswmHA1mWpQDLFB8HaJH9NiknDRU+AX06drGqX1rdGjjynjQ=,iv:F9dP69PBEUdvWAyBoXE54jiE9E4YrkBpGW/QzXN9mZU=,tag:rnPLkJ8VcoNMUTmV88LNug==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T01:56:22Z"
    mac: ENC[AES256_GCM,data:H6xjRKJQ6xLq0gAhtIpr0OPg5sOG/+ERZB0MJoxfi4+rNHTfYlRy9wqKVSGMruCTCmyMQkaqBBykAzPvOEuIumyg9QTeNs1t2DjkvRNjNx4ieBbI1i3mSqRWQbAix1s1Vl1tarUEXMtlvUW/F4LsPMZbxJ2XPEZgBl67fNy6YYw=,iv:J+zAXWdbViRylOYu29T1doSWLnjtbqHiBmLuFKZ2PCY=,tag:Kz03gWQySEXrg7RgdkOEFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
