apiVersion: v1
kind: Secret
metadata:
    name: echo-auth-client-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:XKWs4CVpRaa5Am4kBx187Ffnu8JLwv7DkUsZqsyIfeEzWUDBbduQyI/UcCF4TtnAbRhUGiYhVCUV4n5WJBBmPVWbN1DHrKQTh8yWAq0oKagX5h/1P/+WG2/350YUxxMeQ2BiVKnM13bOxNSbuYcUCWC/CbrLAGWOGRYahbMfwFQ=,iv:auqHqTSq2QbTbJDQ2Sj7ihWAdHxj1x8MffCbp+aSCFg=,tag:CjkNx4TftYz0ydwv/As6Pg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T10:29:28Z"
    mac: ENC[AES256_GCM,data:V2kKp+hTcoK5pIUGtwC/7l1bIObkDWjNbojtc1d+1K/ugepTwgWBdsAgJ9siTg5UhKulgl5G6G+yCDG2zT977Eba6hzqwTyS9Z5XZ7wuu2DdcNYcDLNnmoAlIUf4DD66alOvTgDfJ6qADcJ1sSaXgc+FbI90fk7R1rNLxMgQuMI=,iv:g+Gq52eJJ6YHUdlgNEHYhR+gsj8FcHFxLAM7j3dDgTM=,tag:Eqg3ZwniiSuOEntiPlk+Lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
