---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: echo-oidcauth-oauth-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo-oidcauth
  oidc:
    provider:
      issuer: "https://auth.rnatr.com/application/o/echo-oidcauth"
    clientID: "zervQZYSRM5uyYvSwnscHaQLQdFFz7NRLiHFxpIx"
    clientSecret:
      name: echo-auth-client-secret
    redirectURL: "https://echo-oidcauth.rnatr.com/oauth2/callback"
    cookieDomain: "rnatr.com"
    cookieNames:
      accessToken: "access-token"
    scopes:
      - "openid"
      - "email"
      - "profile"
      - "offline_access"
  jwt:
    providers:
      - name: authentik
        issuer: https://auth.rnatr.com/application/o/echo-oidcauth/
        remoteJWKS:
          uri: https://auth.rnatr.com/application/o/echo-oidcauth/jwks/
        extractFrom:
          cookies:
            - "access-token"
        claimToHeaders:
          - claim: email
            header: X-User-Email
          - claim: name
            header: X-User-Name
          - claim: preferred_username
            header: X-User-ID
