apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:2do7wb/K4I8ibZDLqacnnfGf3Us=,iv:jMg1LOQke897UiKlnOz09uHIi1qfdzpIL2YNeFlNA3c=,tag:h53NcjSC70f+xtWrTBvs4A==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:1KE6uDhdXGjzEtCzxu4aFx0W7fM0t4UHygWBw/A1/p0=,iv:q4XOnMleo9W7tdDXroFEfDza0tWZ9Y8MCP8dreRRocw=,tag:GE9NsW3GGjy6ZBAvJJ1MAw==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:D4ZAE4mKBLj87KQAczuZyzs=,iv:LQtNIrNZ1eH27IOTSJ7qnVWmHRzLU3kVH2lgK0eMROM=,tag:dAftyr24QvX/M5L+UBWo6Q==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:QWbo55qyWd1htyI/Ufgre7mzWrqKKblQ2b3qr/oi4hQ=,iv:1cdrHxhGziIikkJHLcSUkfCT8VAc5EM0/gXUARFmF2U=,tag:7n5xVznY8UkkKpXeDOvVeg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T21:08:04Z"
    mac: ENC[AES256_GCM,data:EOTz3VNU4HCxA7Snx/RWiXllz9CzrjGtIurXKwm4UAZ2ILqp3KlOdeuPTOHPbxNIcTgW/TwV9sDycr7zsvI1TYoiJxLVZ0vTUOE6RdvNXlB8EAVY+XbLpoiHi+bTXDW9kqe74J8eMrB84BcRR4J1UNj//m+K9NVjzI7sAFgk82A=,iv:+4a1xnh+6fme8I6hZDt3guINRUxFRQb1KvBMPacE/J8=,tag:1AsRppRqOoZWLf6hJRgXYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
