---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
  interval: 1h
  values:
    image:
      repository: ghcr.io/home-operations/tuppr
      tag: 0.2.7@sha256:bca79f9cfc4a75b318e160bd811948fa513327f178c32cf85713833be7a480e2
    replicaCount: 2
    monitoring:
      serviceMonitor:
        enabled: true
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
