---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
  interval: 1h
  values:
    image:
      repository: ghcr.io/home-operations/tuppr
      tag: 0.1.28@sha256:314a9b0875e3cecb41420b5f73d1217d14635671e3a1022f831d35e81d810871
    replicaCount: 2
    monitoring:
      serviceMonitor:
        enabled: true
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
