---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
  interval: 1h
  values:
    image:
      repository: ghcr.io/home-operations/tuppr
      tag: 0.1.24@sha256:3dba49be238394193c35fa0a3322c4222e21e643aaccb495ecea5423271a9a38
    replicaCount: 2
    monitoring:
      serviceMonitor:
        enabled: true
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
