---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./echo-basicauth/ks.yaml
  - ./echo-oidcauth/ks.yaml
  - ./forgejo/ks.yaml
  - ./pihole/ks.yaml
  - ./renovate/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./wg-easy/ks.yaml
  - ./whoami/ks.yaml
