---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./blog/ks.yaml
  - ./echo/ks.yaml
  - ./echo-basicauth/ks.yaml
  - ./echo-oidcauth/ks.yaml
  - ./forgejo/ks.yaml
  - ./forgejo-runner/ks.yaml
  - ./freshrss/ks.yaml
  - ./home-assistant/ks.yaml
  - ./immich/ks.yaml
  - ./mosquitto/ks.yaml
  - ./paperless/ks.yaml
  - ./pihole/ks.yaml
  - ./renovate/ks.yaml
  - ./wg-easy/ks.yaml
  - ./whoami/ks.yaml
  - ./zigbee/ks.yaml
  - ./zwave/ks.yaml
