---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  interval: 1h
  # All values at https://code.forgejo.org/forgejo-helm/forgejo-helm
  values:
    service:
      ssh:
        type: LoadBalancer
        port: 2222
        annotations:
          external-dns.alpha.kubernetes.io/hostname: git.rnatr.com
          lbipam.cilium.io/ips: 192.168.30.22
        externalTrafficPolicy: Local

    persistence:
      enabled: true
      claimName: forgejo

    # databases
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: false

    gitea:
      admin:
        existingSecret: forgejo-admin-secret
        email: "forgejo@rnatr.com"

      # See https://forgejo.org/docs/latest/admin/config-cheat-sheet/
      config:
        APP_NAME: "Forgejo for rnatr.com"
        config:
          server:
            ENABLE_PPROF: true
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        security:
          PASSWORD_COMPLEXITY: spec
        server:
          SSH_PORT : 2222
          SSH_LISTEN_PORT : 2222
        service:
          REQUIRE_SIGNIN_VIEW: true
          DISABLE_REGISTRATION: true
          ENABLE_NOTIFY_MAIL: true
    httpRoute:
      enabled: true
      hostnames: [ "forgejo.rnatr.com" ]
      parentRefs:
        - name: envoy-internal
          namespace: network