---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  interval: 1h
  # All values at https://code.forgejo.org/forgejo-helm/forgejo-helm
  values:
    image:
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 14.0.4-rootless
      digest: sha256:bca6943cdd8a50f5befaf1d654bec32c9a3b6da400d23a77a829bd41f88a7263
      rootless: true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities: { drop: ["ALL"] }
      seccompProfile:
        type: RuntimeDefault
    service:
      ssh:
        type: LoadBalancer
        port: 2222
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "git.${SECRET_DOMAIN}"
          lbipam.cilium.io/ips: 192.168.30.22
        externalTrafficPolicy: Local
    persistence:
      enabled: true
      claimName: forgejo
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    gitea:
      admin:
        existingSecret: forgejo-admin-secret
        email: "forgejo@${SECRET_DOMAIN}"

      # See https://forgejo.org/docs/latest/admin/config-cheat-sheet/
      config:
        APP_NAME: "Forgejo for ${SECRET_DOMAIN}"
        migrations:
          ALLOW_DOMAINS: "github.com, *.github.com, *.${SECRET_DOMAIN}, *.jonathanrosshart.com, gitlab.com, *.gitlab.com"
          MAX_ATTEMPTS: 3
          RETRY_BACKOFF: 3
        security:
          PASSWORD_COMPLEXITY: spec
        server:
          DOMAIN: forgejo.${SECRET_DOMAIN}
          ENABLE_PPROF: false
          LANDING_PAGE: explore
          ROOT_URL: https://forgejo.${SECRET_DOMAIN}
          SSH_DOMAIN: git.${SECRET_DOMAIN}
          SSH_LISTEN_PORT : 2222
          SSH_PORT : 2222
        service:
          DISABLE_REGISTRATION: true
          ENABLE_NOTIFY_MAIL: true
          REQUIRE_SIGNIN_VIEW: true
        webhook:
          ALLOWED_HOST_LIST: "*.${SECRET_DOMAIN}, *.cluster.local"
      queue:
        TYPE: redis
        CONN_STR: redis://forgejo-dragonfly:6379/0?
      cache:
        ADAPTER: redis
        HOST: redis://forgejo-dragonfly:6379/1
      session:
        PROVIDER: redis
        PROVIDER_CONFIG: redis://forgejo-dragonfly:6379/2

    httpRoute:
      enabled: true
      hostnames: [ "forgejo.${SECRET_DOMAIN}" ]
      parentRefs:
        - name: envoy-internal
          namespace: network