apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SU+EXA==,iv:UtIBnHH/0AubhqSFtlfG5tx9RT3lez90+mqE6yx8PlE=,tag:an0aMqf3qBS9Yg8A9xZH7g==,type:str]
    password: ENC[AES256_GCM,data:St2E2npvUQqL54249Q==,iv:QG5kaZYnFhvUb/uG+3nNbpP0hVruwzro95WrGpfXHWo=,tag:sC/x3R90wn1zP0M5d7qGdg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:22:03Z"
    mac: ENC[AES256_GCM,data:V9ySbYwo93laQhfvkrHBXsPF1clhXgBdwjaKJihzJ1hBiM9neN7ZigIsroMHqAFD11CFxtS7YsnKXEh8Q0BlXPBv3xP+PuDHcl/M1Ao/Zp8l3/tMxI+s4Fo5OkwyiF3ZVfUVn2ZiM0RaWAKci52DWjwvV0twajgO/3vc5ci3bxc=,iv:282ZcJoZ5akbVmpZzZRYqXWAjdKue3S+wqj85u3l5Wo=,tag:M3Oktlb7K28gZEeTEXroJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-signing-secret
type: Opaque
data:
    privateKey: ENC[AES256_GCM,data:ov5I6Irk64LATxl4uQBEDkAtmls8Y+so3f84WIwyxa+Hbe7tmUFvZhAEXMOXSHuA9naHynl42YF1tLkg8ysbKQrLnfgyMgzfyuDRtmHhWg9AaI+A379BGdiZHwDHueNpbWP/J5fDwv4xqozi8M7Ge9mDogV8PdOTuDOpF/JJ0tC4nmK16YLh8AaTUGHgqlYMAWH4IBVWFBEa55h+1xSgv+3lAH7EETAZzlAITI9Bsl5f4xBK4CDwBS84Fkz/UH9NBfz/CyawJBut83RAkMk+IPZCDXUxkssB73iJSfMWMiKwxUkAx65eQm1D3Mram1Y2dhwZteRtSp2g+A2jzC/A3R5qnvxqRoEBjr3z8U8M0KvFQnFpSPKwA+DfJViD7dzoc7vLjqxX/xj0CvdLSA3VVoQ30//WCyuhg2tocuMWlyq5Bhpck2LAOQkfQtbX0zc0c7uhtk2P+tjqCoOG6fgEfWB1aRuSs7deG/77aYV4I+1plx0C93U9UDvYuolTcv8ukj4PETEdm9En8x3dwMSq8TliOx83jzt2yePBJBwmafzVdLg0/7xkXFlLVCcCsob0JK/Dqk+VNd9g6K6nieRxcPaz9dAYo7sweucmWpmFWIs953MBz1a2Lc7SDLoJdl8AhFJZ+ATt2Gb4gIbswWF3hzcy3ikB3FOy7iwRan21BrReVBpO8SL4X8FMNv2BkpGzXwLQXR11hatlOq7Q2MznCFyjsRFP4Xcso2tld+89owc=,iv:mF/NvF1QEpPqUX7XORrlvjazWlqZRRv9JdF18QrDK9Y=,tag:FeIUaSaJPpC4ER3hivZXeQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:22:03Z"
    mac: ENC[AES256_GCM,data:V9ySbYwo93laQhfvkrHBXsPF1clhXgBdwjaKJihzJ1hBiM9neN7ZigIsroMHqAFD11CFxtS7YsnKXEh8Q0BlXPBv3xP+PuDHcl/M1Ao/Zp8l3/tMxI+s4Fo5OkwyiF3ZVfUVn2ZiM0RaWAKci52DWjwvV0twajgO/3vc5ci3bxc=,iv:282ZcJoZ5akbVmpZzZRYqXWAjdKue3S+wqj85u3l5Wo=,tag:M3Oktlb7K28gZEeTEXroJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
