apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:iYTaAUY4po8xTLoK,iv:Gcs6W6NcVSiRdcYOEwvbqUsKfLPCn54gdQ3yo0yXbLs=,tag:ZwMB3N+x3EtALR1rZFZoGA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T12:08:33Z"
    mac: ENC[AES256_GCM,data:otyP4puA3M+FKSbhZlSDSf20pnaR2dyGH9Ml1kms8DEGim04bT8SLWidP7CAyVHWEzgarzslAAEVa53WanMyuwf1Y5nPOTu1BlrKvU28J/xmhsQIaMmCM15N6QcejJeOJcEGTYNPxNeXTSrY1nwsf5tkdwmeuin+lJP4onlpadk=,iv:49ZBD6ZvadzWl7Pp0qEOLwE9dmXkLKruV3PJdqSsvQA=,tag:r1+LneS6TQGgAf51Gtrh7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
