apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SU+EXA==,iv:UtIBnHH/0AubhqSFtlfG5tx9RT3lez90+mqE6yx8PlE=,tag:an0aMqf3qBS9Yg8A9xZH7g==,type:str]
    password: ENC[AES256_GCM,data:St2E2npvUQqL54249Q==,iv:QG5kaZYnFhvUb/uG+3nNbpP0hVruwzro95WrGpfXHWo=,tag:sC/x3R90wn1zP0M5d7qGdg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:13:26Z"
    mac: ENC[AES256_GCM,data:tVZUA5h+LoweR+ikpsaLusz83QhbLwECU5D4iFnx1L1tLGCS+3Cc/WGmE7+ZCdd3vd1d0ccBsYGAwTM4XWwH016id8BcMxwekcVp/TjJRy7/R6QU0+ImHoKV4T39CzrG87P/k3/yoCMqR7Wq0sE/6k9Bd0uvABN/WjD0h0DJbNc=,iv:80UBSDnCRARCQF78Du4Jo9dBgRReKclxEL1qivtbopE=,tag:u4olhZEqB+v8Cp8q5JjknA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-signing-secret
type: Opaque
stringData:
    privateKey: ENC[AES256_GCM,data:6NIMzPclcPscrrxQuannmP+M4km+aqaBaS4JFGew1bX7NLdEz8jHg6wg1YI3gAGTTK3VvlNengfM9KxndMPsqZhTNBIBlevNMFsDxhBuQcjzmR6N9EB1x/gQt7tQjQTBJisuxQMx7y1gaLYAwh2CiPcW+V2sOJekckjfutJ+U3aaWtboFbB/4Wm3+yDVgXyZkZax9OMWfr0j7tzvPmUD1PwKXC2C+psWbHYdNUwn048wS/pMFXHWqmhP6+BeXVEkvtbiISdO71+ZTZPxvqHnkZ0Bw1dt+RnB5b/EUbexKJYYl+Dn05kLL8Ivlv5KYUy0rxGmgV0VnDcPg7CizU67ex89J96NR3d/Luancyv+IT40wNFk8DE/ixXLY1ibUyfknw2iRjKVc3fos7J9bFo9Y1f/k3OQD1Pa9WGXaNhuY0gJP4V7nDdGYsXc6YcX2rmm4IoCqhpM2miAHxm3IK4f1w3fMqTcKX+eGrRRCavjvY2NE2I3hwTtxunenrsURWJ7w2MUzp9VWrms41SyIhWaT5sRjAaeEiupTKGPenOK9xgL4Q==,iv:ApvVBqli4gxzjXDx4KRc9Efixm+WzqEOv+PQ5gN3qBY=,tag:QeXxYVIWlecyqhVotQUbyQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:13:26Z"
    mac: ENC[AES256_GCM,data:tVZUA5h+LoweR+ikpsaLusz83QhbLwECU5D4iFnx1L1tLGCS+3Cc/WGmE7+ZCdd3vd1d0ccBsYGAwTM4XWwH016id8BcMxwekcVp/TjJRy7/R6QU0+ImHoKV4T39CzrG87P/k3/yoCMqR7Wq0sE/6k9Bd0uvABN/WjD0h0DJbNc=,iv:80UBSDnCRARCQF78Du4Jo9dBgRReKclxEL1qivtbopE=,tag:u4olhZEqB+v8Cp8q5JjknA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
