apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:E/LYFiRYnXBV9GNDX7GwiV+9+mJ/6e6ZRd2YAlsvhndI7m6j2VsYKZ/uiy8Vt8JCp7wzAbiUx3ogD5puUVfUM5vpzeFBCtdlYGtYckAlnMd2NuhKcrDURvw21XKJF7Jodk7SexqmK3EDA2DNGW0bsXmEKJQJJbubx0aBH+RQ33nAnbgbI0oV5TY4IH5bdcRJMgkZur518p+nB5PPW9FfZ4StNIAb4G235s7L+HU403gu6xwl,iv:Po1ysr4y7BmHFMIsDyzQpI+dMtFcJUaFUCe8ZwQ8S/o=,tag:0TNY4Sid3vRg8TUMMAU55A==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWFUdmNBS01BU2FtWmk5
        Z3E2SUVxL3N2YzdzQ0pYbkhGTnVpODFETkNFCm1vdC9TUnhMczdjdGtHMVExcXMx
        elBoTXdjYTZ2dlB4RkhRVjZOd1dacG8KLS0tIC9oNzh0V3Q0dUdCMzdGRGJTYUtQ
        M3AyU3JQSkxTMDZmWTJzMUswUUh0NFkKyMz/DFlPBzMWqNzWo/IiQDdRZ4IHRC0J
        1loK/Y97gXBY0DruGqAhuTtaWE8kA7iS6Y7ExX3qaR7bk0Fsth+7VA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T17:22:15Z"
  mac: ENC[AES256_GCM,data:pNLeFsICLnaYpyO4APwvO5jHEEWzPN+FCwYPo7MFg9ZBDP7ch28AjbR+DFDIxAyQlI0EhLQg0rELYx0jvAQN/cHUZDGvc5yqNKo6q1QEIZyjXWRtUQd+/zu9k+hNYRQERRkbHkEs7MS1VGwVq4DMN58CD6UDhUUpb7Mcv69Yb7U=,iv:EpC5GMDSBjygS91hGmS7af7+CwI+1NORVsmD+u1g24I=,tag:dfJqSaLNocoYzn5ZryqjtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
