apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cpwO1YO0yBaw1ivG5rmCa8C/FEqZZtF+wecLCMRIapHwcf1kp3XaKOWYha78Pl6qQDyOGuSiJ/bk9RU0nQtilApVilkNUprmKkC7gevesHcDRczSjUm2WXguf+VBdhnpGJzhePthfZUROWQ40N31q2PyAPrc7paz87sq50UZCJgJhViGutGJqg4Nd9yg+3zvGiV/SV0KO/bCFVciE465ZtOY+kfiU3IE26v7jo+l351oEOzE,iv:QcfVR7MKmq1SLh9pIZKi0EySYNiQ9fmSMPwGX7DoDM8=,tag:GluBY6Pt2aiKUSY1jjKPCA==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aTJNd0s3dkhOeURRT09M
        cDZ2b215emViTkh5YWRhSmhGaExEVUs4Y2xZCmZVdDYzK3d4bHJ3cm9EV3h2dmI1
        MUxPQXUyMllhMmRSZDlXZUtzUjdRemsKLS0tIFdpeUhtNDBxSG9jWGxQV1M0dVNh
        NXN6Wi9sRk1KVkVkYWRlUnV6Y0o2dTQK9Wg9n0o4s8mLzEoVyzarlPWCkt1vMaQc
        FvKXpVMsk+KygQR14RN9zDtyR5v0cn1l1bN+id5JoRXvohj8ivj/tQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T02:18:10Z"
  mac: ENC[AES256_GCM,data:3mnfR4ijOq6m8IufS99UTV0f3SXXB2s33cqOOk3sozl0OcMTohgn1yRNnAh+njcQRpFwehcDu/1x4KmAbUvA5+SWcxpWiSwdYoSMppc9v0IiyhdKe6/6CPTr/6ZfDkyYEm6RGs7A5j/WQBrIBKpkqZl/r1BGnFbN5xhz46u6CjA=,iv:HErwCwzFQ/UoSdE7AClZYkPV2ZecGxQgmjPQc+fYwrI=,tag:IbNcDhNqdIghBSrTx0bW8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
