apiVersion: v1
kind: Secret
metadata:
    name: signal-cli-secret
type: Opaque
stringData:
    SIGNAL_ACCOUNT: ENC[AES256_GCM,data:Q7iNdQsEb0mYMjkd,iv:lVS3b6IOWEhHFMtmvIvSOIUpDdYxCrye3JG0g8uyiNU=,tag:8cuTXv+xYtt9SZft4TaSgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T14:04:19Z"
    mac: ENC[AES256_GCM,data:q7Z9w0TpoIUyx+RJJDTqFvcfnlKwJZUJJ1gU8IwuB3gv48Ee1oy3MvgAPnxqeaC96ThS+QMbDlbg0V4PIojl0MheLy/GstKJRrESdTTioN01guYxGNaYXwxH2D8/o5je3ZikayD1xWpdEkaG10fyfpnFHOgfImj+bAgDidHR8TI=,iv:Nj7qyg9BN2wSmHvsyKDR8vXtzsyVxYrpaKUqiSs4gwk=,tag:7wgvdFQ0Lm66d88STyMm0Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
