---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./hermes/ks.yaml
  - ./agentmemory/ks.yaml
  - ./openvino-qwen3-embedding/ks.yaml
  - ./llama-cpp/ks.yaml
  - ./litellm/ks.yaml
  # - ./ollama/ks.yaml
  - ./open-webui/ks.yaml
  - ./searxng/ks.yaml
