---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./agentmemory/ks.yaml
  - ./comfyui/ks.yaml
  - ./dgx-resource-claim/ks.yaml
  - ./flux-mcp/ks.yaml
  - ./github-mcp/ks.yaml
  - ./grafana-mcp/ks.yaml
  - ./hermes/ks.yaml
  - ./litellm/ks.yaml
  - ./llmkube/ks.yaml
  - ./kubectl-mcp/ks.yaml
  - ./kubesearch-mcp/ks.yaml
  - ./open-webui/ks.yaml
  - ./searxng/ks.yaml
  - ./talos-mcp/ks.yaml
  - ./toolhive/ks.yaml
  - ./victorialogs/ks.yaml
  - ./yardstick/ks.yaml
