apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
type: opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:h6DyrJhnNHR+WkQmyMqz+jrkcbum79q3anA0o5v+NSY=,iv:X1oxlT4EB60CKtmCj/Tmi31xubRPsx4R0ujIVKDMcDs=,tag:cGOTSWIyDzL4gxc00UGo0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q2ptNXhYSGNTY3VFamsw
            UkMyb1dRQXdEK0VVeU9mMmlYUkhMZkxjb0FJClFDWUFmOFRWV0k0YmJ2Mk5TaDdu
            aUhEZEpTTVozYVFTeCsydmo0RmhRd2sKLS0tIDJsaVBiUFNheDE0clcxU1dRZEVI
            TzM3TCtvdVkyNE5mYjhUL1BqSytxN0kKOT3XT0wWcG6tXTY85yMxf4MeE4yqtDyY
            7J3zfnFOFZwdhOzmTxRu6UC6ShG4suPW3hMU1UH6PJ+Cx0+xykQMAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T20:57:19Z"
    mac: ENC[AES256_GCM,data:f24k8J2BFACGZXPrxuVDgmNpcwTbGWeFqxd1XDyzMcRIue84FRFJoT7Oc9PqyDOgbfHLqAX5nwutvZliqRF81s8vlomNCTLiWA0E3mSTx5JFXjZ1KlMWRTv+emlo68R6cHeRj4tCzROtn/enY4/2FFFqvtDjCmy/WXxD3vbJgcM=,iv:C1EUwXWhi10az+Mtm2YbBinZibQ7R2/JPvSq/yWSZ9U=,tag:CwDujHZ3EzY9ToJImY/c0A==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
