apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
type: opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:g3wMmz/7gRMUna2vnNDuUg9KXY1gRsOK8/61L7iIzc0=,iv:EwdFocM8GjBLyQPKfOztuJTP5doUgloXKgFqNlbfAA8=,tag:uZHol59dMzsae/QWBbo/mQ==,type:str]
    UNIFI_CONSOLE_ID: ENC[AES256_GCM,data:aslaXgcf9bH1e5AQ5i/iNBo9A8srKsapGK3cSSaM0pfUy77zCrflLONT8ympNRbzYGJk7tsUsn34sRG4RTTgCYhCtQnNReY=,iv:PJ/Sg001x9DRQVMkWN5BMFfQ3JVq/yGnJcL1htVeJ/Q=,tag:Lf5ZqXjtqRs4rrbYsb5d9g==,type:str]
    UNIFI_CONSOLE_API_KEY: ENC[AES256_GCM,data:6kadnT0jRL14NE4TRK6R54SI3YUqxugP9hMrE6RoRjc=,iv:/rsxnBTwEZNcd0oz8CIrkOWhrsEeSy1QPSUMtJUStTc=,tag:CvTUi6XpWwRm6nE4ZoL2lQ==,type:str]
    UP_API_KEY: ENC[AES256_GCM,data:73+iEW4zacGhI7eXAxmsfdE6qdctEsNH3Zp5cy6tqUo=,iv:CMJ2PLBnSceOegAhSlMq+99duR3ly/FqzrJmAPPQ6xo=,tag:raH+WMJgj80SW63eYWc5nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q2ptNXhYSGNTY3VFamsw
            UkMyb1dRQXdEK0VVeU9mMmlYUkhMZkxjb0FJClFDWUFmOFRWV0k0YmJ2Mk5TaDdu
            aUhEZEpTTVozYVFTeCsydmo0RmhRd2sKLS0tIDJsaVBiUFNheDE0clcxU1dRZEVI
            TzM3TCtvdVkyNE5mYjhUL1BqSytxN0kKOT3XT0wWcG6tXTY85yMxf4MeE4yqtDyY
            7J3zfnFOFZwdhOzmTxRu6UC6ShG4suPW3hMU1UH6PJ+Cx0+xykQMAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T09:30:07Z"
    mac: ENC[AES256_GCM,data:eeO88LXdAKflbbz04k9+0v2+ga9oy0IC8T8GgdLxtWC0IP+g48gv/x3E3+DnggEUb/QsnsHTrHh8uLYTZYEEaE4XB+cpxq3DOC9VVQJhTmzzqAH43wqxYmnFOwxfd57ZhHJ3759Wrck6hYOfGu86doDhk+MdSUa9fis5bAB00bw=,iv:KOx6gQjrrdYWGYKqx+4mPEVa0ZsyNcx1oW4xzXnDKIo=,tag:mw8nq0li89UdOeuMMQZvNQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
