apiVersion: v1
kind: Secret
metadata:
    name: renovate-operator-secret
type: Opaque
stringData:
    dragonfly_password: ENC[AES256_GCM,data:eqQ2/v8+baECLBfCD5Gnx8/5QNmUec46a7TG1Y37JlU=,iv:sEhac4nsbNBEG6Et0GvijgMt+8wqSP6A1Yt3VB2E7iw=,tag:EERqQYPH0rJWCx7sx5zwOg==,type:str]
    dragonfly_url: ENC[AES256_GCM,data:Bmqfi2Cv6qVW/EN9UAt3S2LujFML6MPYT5woI29JBsmfH3At9jx4CNtePmYmnOJIjNOXTrAN55s0OrDC4BB88O+mXw==,iv:UR0kfkJr02xIw7Kd92an5BakPLHMmNjWjAjPRBl6XcI=,tag:K8pMbm8/jaTpYLbogukP1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T01:23:23Z"
    mac: ENC[AES256_GCM,data:cJ5g+6tmzxJf6WuQ54H9FzVxfeU4I7mtIqgUosHxpdbleFv2HIVnMTswUcU29wVvO2C1/Etk31SgERWnjMUdvn9dg7b4cbwEo0ewq3BTrzapiWRtRmwPaqxLd400E31g6Czpfl9EvNkRgNpQOnvt13kL8IEyXIY8Wjk/vtKPW9k=,iv:wR7kvPIj96/WGeTMAmWAwzOEbZCvfw6MHiKsFswJaNI=,tag:hMUPWM3mK7hgsFq8GsEswA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
