apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
type: Opaque
stringData:
    dragonfly_password: ENC[AES256_GCM,data:eqQ2/v8+baECLBfCD5Gnx8/5QNmUec46a7TG1Y37JlU=,iv:sEhac4nsbNBEG6Et0GvijgMt+8wqSP6A1Yt3VB2E7iw=,tag:EERqQYPH0rJWCx7sx5zwOg==,type:str]
    dragonfly_url: ENC[AES256_GCM,data:Bmqfi2Cv6qVW/EN9UAt3S2LujFML6MPYT5woI29JBsmfH3At9jx4CNtePmYmnOJIjNOXTrAN55s0OrDC4BB88O+mXw==,iv:UR0kfkJr02xIw7Kd92an5BakPLHMmNjWjAjPRBl6XcI=,tag:K8pMbm8/jaTpYLbogukP1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T01:08:57Z"
    mac: ENC[AES256_GCM,data:RSvrgb1lbC7CSTT5cEKY4Z6yOYs8Kq976ErZkHAOnoq/48+a9nSJU/v4EtljMwq9ez8AaA+FA26PwamgKr1NCH+BhIPXjHha4cnzL7XZNratBoRVwVJCuSrW30f8N4nf/hwHyby10YqOlQ+/G2PjLYlu5irvgiDttUq+4/wVq6c=,iv:5tK+qSOmL2UYgQh0jOON5gFDAlnrLfUZhvyX8p5GV/8=,tag:1BtO1KKTCrN4zyoDosJ9Pw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
