apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:LyGRY6h+1tHDCwJVUTm61FKglNgOBg421SbcbrSKI7c5dwvQ0PpuJA==,iv:YNFJuV+efDsey3MLnpfbvBkDQJIAmaARXfXcQI8zz+0=,tag:pFY6aM6r++JF1V0jDaeNww==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRFloM3BxUGVQQ0FLVjlo
        YlIyR0pBQ1BLRVZZSWFhOU5lcjN2b0ZWWUV3Cm04MVd0ekVXL3dDRDZCdlZscGo1
        d0JPM0NodTk2Y1lkdHZ0VVdrdDRNZ2sKLS0tIHdLcTFTa3JLcEZyMFc5UzBBYWtM
        WDJNWmVhMFRsTGZMR08xdmVZZ01xQ1EK5Tz7DWt13ROP8iy8H3eVzV6k+CLbqj2a
        Hwsiq7h3WzwZXlTj7GJo951HasFS8UZ4Ay1uDz7+M4MO3xuurljslA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T17:22:15Z"
  mac: ENC[AES256_GCM,data:YfBshH2HO9CycXoAotyfTREPHrSW2lCb+b4BccvI7992kZH5fQsGVCR+B3lrBVCQS2phSpe8Nz8hieANeP9mydCjgdmd9Ie87+iA/fD7crjxUZtyblAHKxucRmfUOxcXqUW5M1c/sA0k++LKSStBdvUIG7Lfw8SlV+YHEsyKCsM=,iv:8lgQGlPcPqxiA6mxczcDM5NiUjWk6nhtipEuAJxX8VQ=,tag:njr84V11pAtlmYZycl/s4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
