apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NDBTbK6KsUnCiEMOBokXK9RbHHvtk3ZfmvOcddO0ePS3Jx9kBsmc/A==,iv:C0TtqReAHnvqLLecLSc2OJmbKNsFrGYwW5W6vg9GjqA=,tag:lAS4Lc2qy/CzYe1IXwj/Ug==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QldESllKQjh3TnVTOVBw
        Nko0ZDRwYlE1ZU15Wkk2UFR0c1BPS0V6WFJJCmNDTktPRHBmcDdxSm80NVFvemFy
        eUhlRytXU3NBdjBLSGlCTlEyM0dPaG8KLS0tIHF3OTR6cjNTWGVRNkNyOUFCbis5
        dnJKQnkrdTdMVG13dm52Vm85anR0SDgKgxLHhR0fuMabX1zv8JlQeJD45FXEqdn3
        g9yzRdJqizQ1TjFH4JGcOKWSnkXIPlbNEopbmJt9jKx52UKXGo23xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T02:18:09Z"
  mac: ENC[AES256_GCM,data:vq5QJv/ZB9YDAqBtnYGOiWqMz1RlRQ0RtNFC4BbnBLTU5+eSBVzHuTRgJZ4a0udJFSEPRcfpv+hDiv8VQv8Qw9IFR6RNSwLW7aP16UBy2YPYD4uqTSRpKSzab3+TUgLP5F8iQudck0EPVXD/MLptWaDGAIwhfqFBZ6rCDR20lLU=,iv:LBCD8DL7muAPKHhvvVZ3v9SOdpJE777KTYUVrNFXYzY=,tag:Sp9QALlAHTGhmPvegCFgPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
