apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: opaque
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:wvLm2+H+Mxw7jxw=,iv:KqS3DgA/mDHR5+upg9BF+b14HJID/G0Kxxp33oGGXv4=,tag:C0IEEii3NkfkRuENVgpZfQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:SL56Xlw3f2lQaaY=,iv:EOyYMNbbtyKTP+luI3kfdWfq07PD79Ts7S6Dkm66R4M=,tag:DHvlV2e96cX6lwgV2luP8g==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:834xE4rR0mmQdALpgi4xfcEERBq9yA36,iv:Hv7P0bBC2JK7tbvibo5+7Oag2AK7xI3PEINpgA1adYc=,tag:2OD+LCUwGqCFShPlOppSaQ==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUW5ySFNFMGhJNG9JbVNj
        dXN6RFBuelRhcFdaY3Q5dlIzNkk4dFIrRWlZCjZKR2xhQXBFWklqUUFPNDRRek9a
        bFdlQjYydDdhakJCaGsyaXJRZE11NzgKLS0tIHVRU0NjS0xUNHhoVnlYTTMydFRF
        cnU3bXBrNjFobXpVdkVmNGV4cy9rdTQKAFQUbMNUPZbcK1XrS7/u/2x2cjPYllAt
        SQ+3wepxW5/pt1G2rRYqn2/U9CgYPnikK4Y5z2tR7/JL/aRSPMKnrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T01:05:03Z"
  mac: ENC[AES256_GCM,data:rm8VFG09MIsgI2XLAMnfPVEhQZjr49JcdKehzVlPpxdlI4znGidMIriMVSA5oe7mZYFB+GLy086V1fJ5gPF6+YGurLRGMvlB4cNNl8pYSd/Mwtc9wcmVKCYwx/iAXJ06+NhNG0Do+mcx4wjxz5pvQAa+wvwQPF5Mtj7TXtoDUQw=,iv:cSNhSR2UTII8G7sFRECKDb37FPk7PykD4QPBPXOECnk=,tag:zwnEZ37x2dejpyzMYDsGuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
