---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.5:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.5"
  - "kube.rnatr.com"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-cp-1"
    ipAddress: "192.168.1.11"
    installDisk: "/dev/disk/by-id/nvme-eui.0025388c91511427"
    talosImageURL: factory.talos.dev/installer/c3ff19ffec90f9ce45a8b80807b0e7614f94142f9959aabdecb7956024da9f2b
    controlPlane: true
    patches:
      - "@./patches/global/machine-time.yaml"
      - # Load kernel modules
        |-
        machine:
          kernel:
            modules:
              - name: mlx5-core
      - # Network configuration
        |-
        ---
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: net0  # <--- This is the common name Multus will look for
        selector:
          # Match this specific node's hardware by MAC
          match: "mac(link.permanent_addr) == '1c:34:da:6a:fc:56'"
        ---
        apiVersion: v1alpha1
        kind: Layer2VIPConfig
        name: 192.168.1.5
        link: net0
        ---
        apiVersion: v1alpha1
        kind: LinkConfig
        name: net0
        addresses:
          - address: 192.168.1.11/24
        mtu: 9000
        routes:
          - gateway: 192.168.1.1
        up: true
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.10
        vlanID: 10
        parent: net0
        addresses:
          - address: 192.168.2.11/24
        routes:
          - gateway: 192.168.2.1
            metric: 2000
        mtu: 9000
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.100
        vlanID: 100
        parent: net0
        addresses:
          - address: 192.168.100.11/24
        routes:
          - gateway: 192.168.100.1
            metric: 3000
        mtu: 9000

  - hostname: "talos-cp-2"
    ipAddress: "192.168.1.12"
    installDisk: "/dev/disk/by-id/nvme-eui.002538d921a1a1e3"
    talosImageURL: factory.talos.dev/installer/c3ff19ffec90f9ce45a8b80807b0e7614f94142f9959aabdecb7956024da9f2b
    controlPlane: true
    patches:
      - "@./patches/global/machine-time.yaml"
      - # Load kernel modules
        |-
        machine:
          kernel:
            modules:
              - name: mlx5-core
      - # Network configuration
        |-
        ---
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: net0  # <--- This is the common name Multus will look for
        selector:
          # Match this specific node's hardware by MAC
          match: "mac(link.permanent_addr) == '1c:34:da:6b:22:1a'"
        ---
        apiVersion: v1alpha1
        kind: Layer2VIPConfig
        name: 192.168.1.5
        link: net0
        ---
        apiVersion: v1alpha1
        kind: LinkConfig
        name: net0
        addresses:
          - address: 192.168.1.12/24
        mtu: 9000
        routes:
          - gateway: 192.168.1.1
        up: true
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.10
        vlanID: 10
        parent: net0
        addresses:
          - address: 192.168.2.12/24
        routes:
          - gateway: 192.168.2.1
            metric: 2000
        mtu: 9000
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.100
        vlanID: 100
        parent: net0
        addresses:
          - address: 192.168.100.12/24
        routes:
          - gateway: 192.168.100.1
            metric: 3000
        mtu: 9000
  - hostname: "talos-cp-3"
    ipAddress: "192.168.1.13"
    installDisk: "/dev/disk/by-id/nvme-eui.001b448b4679b087"
    talosImageURL: factory.talos.dev/installer/c3ff19ffec90f9ce45a8b80807b0e7614f94142f9959aabdecb7956024da9f2b
    controlPlane: true
    patches:
      - # Load kernel modules
        |-
        machine:
          kernel:
            modules:
              - name: mlx5-core
      - # Network configuration
        |-
        ---
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: net0  # <--- This is the common name Multus will look for
        selector:
          # Match this specific node's hardware by MAC
          match: "mac(link.permanent_addr) == '24:8a:07:5a:cd:9c'"
        ---
        apiVersion: v1alpha1
        kind: Layer2VIPConfig
        name: 192.168.1.5
        link: net0
        ---
        apiVersion: v1alpha1
        kind: LinkConfig
        name: net0
        addresses:
          - address: 192.168.1.13/24
        mtu: 9000
        routes:
          - gateway: 192.168.1.1
        up: true
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.10
        vlanID: 10
        parent: net0
        addresses:
          - address: 192.168.2.13/24
        routes:
          - gateway: 192.168.2.1
            metric: 2000
        mtu: 9000
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.100
        vlanID: 100
        parent: net0
        addresses:
          - address: 192.168.100.13/24
        routes:
          - gateway: 192.168.100.1
            metric: 3000
        mtu: 9000
  - hostname: "talos-worker-5"
    ipAddress: "192.168.1.18"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/d7ace2998426c6b73fe450e0166c49d8b8870aff89cb41cf7687635836149cb7
    controlPlane: false
    kernelModules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
      - name: mlx5-core
    patches:
      - "@./patches/global/machine-time.yaml"
      - # Network configuration
        |-
        ---
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: net0  # <--- This is the common name Multus will look for
        selector:
          # Match this specific node's hardware by MAC
          match: "mac(link.permanent_addr) == '4c:bb:47:2d:23:ff'"
        ---
        apiVersion: v1alpha1
        kind: LinkConfig
        name: net0
        addresses:
          - address: 192.168.1.18/24
        mtu: 9000
        routes:
          - gateway: 192.168.1.1
        up: true
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.10
        vlanID: 10
        parent: net0
        addresses:
          - address: 192.168.2.18/24
        routes:
          - gateway: 192.168.2.1
            metric: 2000
        mtu: 9000
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.100
        vlanID: 100
        parent: net0
        addresses:
          - address: 192.168.100.18/24
        routes:
          - gateway: 192.168.100.1
            metric: 3000
        mtu: 9000
  - hostname: "talos-worker-6"
    ipAddress: "192.168.1.19"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c3ff19ffec90f9ce45a8b80807b0e7614f94142f9959aabdecb7956024da9f2b
    controlPlane: false
    patches:
      - # Network configuration
        |-
        ---
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: net0  # <--- This is the common name Multus will look for
        selector:
          # Match this specific node's hardware by MAC
          match: "mac(link.permanent_addr) == 'bc:24:11:9d:08:34'"
        ---
        apiVersion: v1alpha1
        kind: LinkConfig
        name: net0
        addresses:
          - address: 192.168.1.19/24
        mtu: 9000
        routes:
          - gateway: 192.168.1.1
        up: true
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.10
        vlanID: 10
        parent: net0
        addresses:
          - address: 192.168.2.19/24
        routes:
          - gateway: 192.168.2.1
            metric: 2000
        mtu: 9000
        ---
        apiVersion: v1alpha1
        kind: VLANConfig
        name: net0.100
        vlanID: 100
        parent: net0
        addresses:
          - address: 192.168.100.19/24
        routes:
          - gateway: 192.168.100.1
            metric: 3000
        mtu: 9000

# Global patches
patches:
  - "@./patches/global/cluster.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-features.yaml"
    # - "@./patches/controller/machine-diskencryption.yaml"
