apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: opaque
stringData:
    #ENC[AES256_GCM,data:3kJvcjmZ1Zn9Z5CW/eUtzr/CmFNtw2jt25Jl+7ZR/Dv2vvwkeOVpJOps1xkdNByOVoUNscaXp51Uka4=,iv:LxQ4PWgwUWbaSM89m/Ndd5Ebf2Z3igAAL1Ntu/eJOtI=,tag:8M4w7glcuhP9A0QJS68J7A==,type:comment]
    UP_UNIFI_DEFAULTI_USER: ENC[AES256_GCM,data:/AgA/MFJVgSkhV6VTPbn8agS,iv:bXk6M9ijfxg64rb48CWIc34lor2kSJdLHyvwx9+sjPU=,tag:V3acAD0fWljQoDV+UR4wyg==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:1nzMaYyHEy0F1o6L/oo=,iv:Axeo1qAcQoISkIDtxk7OhFStarFU32YgqpIu7TA8FG8=,tag:C6fr3XhPJNGGavOuQ1zmGw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q2ptNXhYSGNTY3VFamsw
            UkMyb1dRQXdEK0VVeU9mMmlYUkhMZkxjb0FJClFDWUFmOFRWV0k0YmJ2Mk5TaDdu
            aUhEZEpTTVozYVFTeCsydmo0RmhRd2sKLS0tIDJsaVBiUFNheDE0clcxU1dRZEVI
            TzM3TCtvdVkyNE5mYjhUL1BqSytxN0kKOT3XT0wWcG6tXTY85yMxf4MeE4yqtDyY
            7J3zfnFOFZwdhOzmTxRu6UC6ShG4suPW3hMU1UH6PJ+Cx0+xykQMAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:56:48Z"
    mac: ENC[AES256_GCM,data:6v3edl4OfaxIPfKaU0LKTswFL34mGptCBU9YsSbj3axgnbfSPYc2wizrknneEMHDmOri1UQq/QQnXHQduXLctji6mEaIGKMK2J996PDqTy/wpQ49HqCmt3hpAvKVhO/5suoBzYvFhkEyrO836OIg0rBtsXZq36lboqfcLtf4JbQ=,iv:Xz2zjO++7topM6xU45T+wGLn/O9UXq2BaJd6Zd+O+VU=,tag:/jR2X19XFOm5mwxiUy9brw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
