apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: opaque
stringData:
    #ENC[AES256_GCM,data:3kJvcjmZ1Zn9Z5CW/eUtzr/CmFNtw2jt25Jl+7ZR/Dv2vvwkeOVpJOps1xkdNByOVoUNscaXp51Uka4=,iv:LxQ4PWgwUWbaSM89m/Ndd5Ebf2Z3igAAL1Ntu/eJOtI=,tag:8M4w7glcuhP9A0QJS68J7A==,type:comment]
    UP_UNIFI_DEFAULTI_USER: ENC[AES256_GCM,data:ZhpWRyubWQmaH01CleOgX/ZP,iv:1COMT5o8VgpSFNIPcEQzkeGNswRd9Z3KoS8BH+WB9Kk=,tag:vb/lXHD/ekNDhnDoEh0nOA==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:1nzMaYyHEy0F1o6L/oo=,iv:Axeo1qAcQoISkIDtxk7OhFStarFU32YgqpIu7TA8FG8=,tag:C6fr3XhPJNGGavOuQ1zmGw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q2ptNXhYSGNTY3VFamsw
            UkMyb1dRQXdEK0VVeU9mMmlYUkhMZkxjb0FJClFDWUFmOFRWV0k0YmJ2Mk5TaDdu
            aUhEZEpTTVozYVFTeCsydmo0RmhRd2sKLS0tIDJsaVBiUFNheDE0clcxU1dRZEVI
            TzM3TCtvdVkyNE5mYjhUL1BqSytxN0kKOT3XT0wWcG6tXTY85yMxf4MeE4yqtDyY
            7J3zfnFOFZwdhOzmTxRu6UC6ShG4suPW3hMU1UH6PJ+Cx0+xykQMAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T02:21:09Z"
    mac: ENC[AES256_GCM,data:YbFvgzwlRNLzLQwOIbzAjMDtbg76XJPWZ2YdbXkLMQ0KSN3ewZn6UR5sVx6R+46GFyzsVjY81nLvvMsDbSmFCP81bGxkz6qxacP08qgPWRzJXIBZutaGJw/vd+Gf7CHM4trZoi0N7L68nO7GvAzZP3i+7YtCj9qcoUlDCOGe9ts=,iv:f0EVIMGPUV66YNI2mZySLc/Qiug9F74jppsMlbWgpRg=,tag:XgbQoPNVtcnBKxv+33yEqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
