apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: opaque
stringData:
    UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:saziE9ioRphSf01touA68WdEX+6MQQu5TL3tmOgSRuk=,iv:ca0/zth4UrpqLlPDiYDEO47Qst1dIPIJTLJ6err5wzg=,tag:JA7XD9b6E3c2qKyO0d+JYg==,type:str]
    #ENC[AES256_GCM,data:aSVQtlzyZITqeDWSS3zuiXvJroDTsv5rsSE3cj8zGM6YMbjR7LqmDHBH,iv:SWKH1i5WQYkwK/7lb/ff0vIihdVvWtOizJLQcrOPP9s=,tag:nR00avEWLAhQGDviXQs8MA==,type:comment]
    #ENC[AES256_GCM,data:ZxPxjYn/bxPpEeuTCl7wBF+q0vdQJky0rX4Bdxq61tC0pHfq6uM=,iv:GzKFAdxsj3YgHTTSl9pTwjjfKxaL7nRy3ecpfDvPmGQ=,tag:bhLiqX/T41LdcL5qX+vm1A==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q2ptNXhYSGNTY3VFamsw
            UkMyb1dRQXdEK0VVeU9mMmlYUkhMZkxjb0FJClFDWUFmOFRWV0k0YmJ2Mk5TaDdu
            aUhEZEpTTVozYVFTeCsydmo0RmhRd2sKLS0tIDJsaVBiUFNheDE0clcxU1dRZEVI
            TzM3TCtvdVkyNE5mYjhUL1BqSytxN0kKOT3XT0wWcG6tXTY85yMxf4MeE4yqtDyY
            7J3zfnFOFZwdhOzmTxRu6UC6ShG4suPW3hMU1UH6PJ+Cx0+xykQMAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T20:59:54Z"
    mac: ENC[AES256_GCM,data:o4ya1emTeTFoHuyD9y/1pIGSTjw9eHOKoCXuhn+QecNEa3CJuK1cHLjiBLAt7gjKZrWT+6/YngYha4R5Kpx2FTvleVh2FQT6z3HHJKQJxxSIeAL3aRf/yItSBavV4tqM+sWanogknjsVx/UyPk95OpQWxd3yPAZe06F83e16S4k=,iv:EEsmBa3oXdd16x6jwTZlM/Ktk7qRz1vkpkJ+qYF/YlE=,tag:3K8HqQUFeUaJkXMbXx9pVw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
