---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hermes
spec:
  chartRef:
    kind: OCIRepository
    name: hermes
  interval: 1h
  values:
    controllers:
      hermes:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        type: deployment
        initContainers:
          init:
            image:
              repository: docker.io/library/alpine
              tag: "3.23"
            command:
              - sh
              - -c
              - |
                set -euo pipefail
                mkdir -p /opt/data
                cp /run/config/config.yaml /opt/data/config.yaml
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              runAsGroup: 10000
              runAsUser: 10000
          # install-tools:
          #   image:
          #     repository: nousresearch/hermes-agent
          #     tag: v2026.5.16@sha256:b6e41c155d6bfce5ad83c5d0fec670086db8a43250e4511c9474134be5482d33
          #   command:
          #     - /bin/sh
          #     - -c
          #     - |
          #       set -e
          #       mkdir -p /opt/data/.local/bin /opt/data/.local/go

          #       if [ ! -L /opt/data/.local/bin/hermes ]; then
          #         ln -sf /opt/hermes/.venv/bin/hermes /opt/data/.local/bin/hermes
          #       fi

          #       if [ ! -f /opt/data/.local/bin/gh ]; then
          #         cd /tmp
          #         curl -fsSL https://github.com/cli/cli/releases/download/v2.61.0/gh_2.61.0_linux_amd64.tar.gz -o gh.tar.gz
          #         tar xzf gh.tar.gz
          #         cp gh_2.61.0_linux_amd64/bin/gh /opt/data/.local/bin/
          #         rm -rf gh.tar.gz gh_2.61.0_linux_amd64
          #       fi

          #       if [ ! -f /opt/data/.local/bin/docker ]; then
          #         cd /tmp
          #         curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-29.4.0.tgz -o docker.tgz
          #         tar xzf docker.tgz --strip-components=1 -C /opt/data/.local/bin/ docker/docker
          #         rm -f docker.tgz
          #       fi

          #       if [ ! -f /opt/data/.local/go/bin/go ]; then
          #         cd /tmp
          #         curl -fsSL https://go.dev/dl/go1.23.5.linux-amd64.tar.gz -o go.tar.gz
          #         tar xzf go.tar.gz
          #         mv go /opt/data/.local/
          #         rm -rf go.tar.gz
          #       fi

          #       if [ ! -f /opt/data/.local/homebrew/bin/brew ]; then
          #         export HOMEBREW_PREFIX=/opt/data/.local/homebrew
          #         mkdir -p $HOMEBREW_PREFIX
          #         git clone --depth 1 https://github.com/Homebrew/brew $HOMEBREW_PREFIX
          #       fi
          #   securityContext:
          #     allowPrivilegeEscalation: false
          #     capabilities:
          #       drop:
          #         - ALL
          #     runAsGroup: 10000
          #     runAsUser: 10000
          daemon:
            image:
              repository: docker
              tag: 29.5.0-dind@sha256:8e3fae900cbfbdc14e8abca89a9e44363065cb535f34a09283c59cc0dde2de20
            restartPolicy: Always
            env:
              DOCKER_TLS_CERTDIR: /certs
            securityContext:
              allowPrivilegeEscalation: true
              privileged: true
              runAsGroup: 0
              runAsUser: 0
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - "docker"
                      - "info"
                  failureThreshold: 3
                  periodSeconds: 20
                  timeoutSeconds: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - "docker"
                      - "info"
                  failureThreshold: 3
                  periodSeconds: 5
                  timeoutSeconds: 3
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - "docker"
                      - "info"
                  failureThreshold: 60
                  periodSeconds: 2
                  timeoutSeconds: 3
        containers:
          app:
            image:
              repository: ghcr.io/jhart99/jhart99-hermes-agent
              tag: latest
              digest: sha256:690e5ea9020ff1ea79a5f9ca2951a3b8735f33b59008a95f007965e6c14dcc1b
            args:
              - gateway
              - run
            env:
              API_SERVER_ENABLED: "true"
              API_SERVER_HOST: 0.0.0.0
              DOCKER_CERT_PATH: /certs/client
              DOCKER_HOST: tcp://localhost:2376
              DOCKER_TLS_VERIFY: "1"
              GOPATH: /opt/data/go
              HERMES_DASHBOARD: "1"
              HERMES_DASHBOARD_TUI: "1"
              HERMES_GID: "10000"
              HERMES_HOME: /opt/data
              HERMES_UID: "10000"
              HOME: /opt/data
              # HOMEBREW_CELLAR: /opt/data/.local/homebrew/Cellar
              # HOMEBREW_PREFIX: /opt/data/.local/homebrew
              # HOMEBREW_REPOSITORY: /opt/data/.local/homebrew
              #MATRIX_ENCRYPTION: "true"
              PATH: /opt/data/.local/bin:/opt/data/.local/go/bin:/opt/data/.local/homebrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
              PIP_BREAK_SYSTEM_PACKAGES: "1"
              #SEARXNG_URL: http://searxng.selfhosted.svc.cluster.local:8080
              TERM: xterm-256color
              TZ: &tz America/New_York
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                cpu: 4
                memory: 16Gi
            securityContext:
              allowPrivilegeEscalation: true
              capabilities:
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                drop:
                  - ALL
              readOnlyRootFilesystem: false
              runAsGroup: 0
              runAsUser: 0
          # codeserver:
          #   image:
          #     repository: ghcr.io/coder/code-server
          #     tag: 4.118.0@sha256:4aff9947c113487113201da811564fade1af5f23038b4d683998d024eebbac92
          #   env:
          #     TZ: *tz
          #   args:
          #     [
          #       "--auth",
          #       "none",
          #       "--user-data-dir",
          #       "/opt/data/.vscode",
          #       "--extensions-dir",
          #       "/opt/data/.vscode",
          #       "--port",
          #       "12321",
          #       "/opt/data",
          #     ]
          #   resources:
          #     requests:
          #       cpu: 10m
          #     limits:
          #       memory: 1Gi
          #   securityContext:
          #     allowPrivilegeEscalation: false
          #     capabilities:
          #       drop:
          #         - ALL
          #     runAsGroup: 1000
          #     runAsUser: 1000

    defaultPodOptions:
      shareProcessNamespace: true
      nodeSelector: { kubernetes.io/arch: amd64 }
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: hermes
        ipFamilies:
          - IPv4
        ports:
          # codeserver:
          #   port: 12321
          dashboard:
            port: 9119
          gateway:
            port: 8642

    route:
      app:
        hostnames:
          - hermes.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 9119
      # codeserver:
      #   hostnames:
      #     - hermes-code.${SECRET_DOMAIN}
      #   parentRefs:
      #     - name: envoy-internal
      #       namespace: network
      #   rules:
      #     - backendRefs:
      #         - identifier: app
      #           port: 12321

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /opt/data
      config-yaml:
        type: configMap
        name: hermes-configmap
        defaultMode: 0o755
        advancedMounts:
          hermes:
            init:
              - path: /run/config/config.yaml
                subPath: config.yaml
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      certs:
        type: emptyDir
        globalMounts:
          - path: /certs

    rbac:
      roles:
        hermes-read-all:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - pods/log
                - nodes
                - services
                - namespaces
                - configmaps
                - persistentvolumes
                - persistentvolumeclaims
                - endpoints
                - resourcequotas
                - limitranges
                - serviceaccounts
                - events
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "apps"
              resources:
                - deployments
                - daemonsets
                - statefulsets
                - replicasets
                - controllerrevisions
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "batch"
              resources:
                - "jobs"
                - "cronjobs"
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "networking.k8s.io"
              resources:
                - "ingresses"
                - "ingressclasses"
                - "networkpolicies"
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "storage.k8s.io"
              resources:
                - storageclasses
                - csinodes
                - csidrivers
                - volumeattachments
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "helm.toolkit.fluxcd.io"
              resources:
                - "helmreleases"
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "kustomize.toolkit.fluxcd.io"
              resources:
                - "kustomizations"
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "source.toolkit.fluxcd.io"
              resources:
                - gitrepositories
                - helmrepositories
                - ocirepositories
                - buckets
                - helmcharts
              verbs:
                - "get"
                - "list"
                - "watch"
            - apiGroups:
                - "external-secrets.io"
              resources:
                - externalsecrets
                - secretstores
                - clustersecretstores
              verbs:
                - "get"
                - "list"
                - "watch"
        hermes-pod-delete:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - "pods"
              verbs:
                - "delete"
        hermes-exec-deploy:
          type: Role
          rules:
            - apiGroups:
                - ""
              resources:
                - "pods/exec"
              verbs:
                - "create"
            - apiGroups:
                - "apps"
              resources:
                - "deployments"
              verbs:
                - "patch"
                - "update"
      bindings:
        hermes-read-all:
          type: ClusterRoleBinding
          roleRef:
            identifier: hermes-read-all
          subjects:
            - identifier: hermes
              serviceAccount: hermes
        hermes-pod-delete:
          type: ClusterRoleBinding
          roleRef:
            identifier: hermes-pod-delete
          subjects:
            - identifier: hermes
              serviceAccount: hermes
        hermes-exec-deploy:
          type: RoleBinding
          roleRef:
            identifier: hermes-exec-deploy
          subjects:
            - identifier: hermes
              serviceAccount: hermes
              namespace: ai
    serviceAccount:
      hermes: {}