apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:d1WJSKRw3jTgPZt/i9FYB+NIp1vIfjAk1shVeV24jXGnzuRhOh/x2plbVDdyec66N4YttBdVZuOeycxd5+a5yXy91WBMVAxk/os2e4W5gcGJeDHrqLkyd8NWgFwm3QlMOvWfsP57FHr92gJk2U7vbBneVA6a9MJkd1QTOcgaV98=,iv:CCiBtAACmcDci2EEt2RCCnNXezLIYlZqXtlRTahmp3Y=,tag:v0MTTxQM+O788egtexxUhQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T14:32:24Z"
    mac: ENC[AES256_GCM,data:uPd+aZmXFp+4djFBXyUQWCcVAQc/hzqvn1vycj3UF8m7smdtlOKLCA1IQAJzEkfQi40lhrMF9zbFUImqpUu46t6qzz9NPaC2wPqOpE01cvU5FveG/3lpeVX8xrrYmwWOa5OnMiCiy1RK0ZQ4eGtT2yk66i2Kd02momPjQoozd9o=,iv:jnxhWhigLPEAEOUIwOfLxmGBkXVOd/qM69ubSdOpSNY=,tag:xJDhH0MyyTYkpepA5cLgvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
