apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
type: Opaque
stringData:
    LLAMA_API_KEY: ENC[AES256_GCM,data:zA0M7xiXpqct1bm9fv6hqC3+10I2eeRf6tqzAunqrDJmYEnIEqPWftQVV4Lx/eLf3pUHD0TKCzODRkp/ECCjyg==,iv:2ssqwMhc60eURasKsuIyGpMTh2tmUCKok3uUWuokP30=,tag:57h/pfMaCtH9v8ZTM6d2MA==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:J0DVyvY7K2ZvXkTIXFl90JA06Y3l8/5IdpiMtK5dyxrv1hKuAr+YXUQ9h/0ZfWMQaz+4F52RazA/Xth+ytcqGw==,iv:AQV46xAja8bmvAAgbLJ7oOqIzQF//27h1lYji36siAQ=,tag:ZhvayQ9tK35h96sElEgyQQ==,type:str]
    GATEWAY_ALLOWED_USERS: ENC[AES256_GCM,data:J6+3yg==,iv:CBsBQer0+5lsDHvvXkxJJdLsg9RAPnTCdBQjojsw5KI=,tag:RuK67h4z4ILTNKIDvbz/BA==,type:str]
    HERMES_DASHBOARD_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xKklFVA7KUO7rnr7yFLwU6gGbgFPdR51xk+CleFThqVhupDu4VuPoPgzjPTGmnY60MqJVyye/ykqHALSyIqIdNFnDFBZYIbKvZU5uu+bYyVg+17FZIk9h8uhQM6Jwhl7NZwNPQbduW0057joB3rvnLwx3ulswW+KFbkch5KmeC4=,iv:rprXga3ptG0Iyj4yjQod4Mv7CjymaKHowsKFiTWIiFo=,tag:uKQ+aSHt0dAo2W/62W3Y4Q==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:MgX3hA==,iv:Lx8OukHM+C54cuhtpMR50tpVQJS9ESUOwisgZaeWus4=,tag:MBwU0K40aVB6yDKhb5a3Yg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:j0RPbCocQBU=,iv:jzV4J8VsODrvk14lWcrqPrCMKHhl08k5O/6UmuwObyg=,tag:y58q3CNesWWg/Btc+xpmSA==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:ClMrPbF2iIEmFnBqPh9gJUIQl+PO36CvgOry2ORyUBk=,iv:0Tyn7GxjRhw9o/j4SlHkSrV4cIbS46+4NUEVfc977Z8=,tag:2kxK5khlO1VizQmCiTcmUg==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:qg2iyBbkRV5yMX4VFTisFy/7wBkINKXR,iv:eJqzBnlw76qyIrz2aAIVatij4h4a+5g/AmJqxz4izgQ=,tag:1bBLRbz625NjH+b2Xx9Hww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T15:23:08Z"
    mac: ENC[AES256_GCM,data:tF/v/zYK5sm/7+sw4gIr1B0e0pnPo35rd4tPYQ/Dw9vq/KQfZm3nq1GPv5mvhmEK2mWS8Qg4fo8nsz5/MP6oNa+lDxIUI9s1y44aBkCIgLOpKiYsbdt0XydWlpeG4gKc0EB9QuEPmfhuv/jnVTt4CpsVeZPsBk6pHEwb8r+4UQ0=,iv:f/q+1T5CbHJW/U+kEtGvSPM2RHrSnIuNmqLftJOwfd8=,tag:/jzNKKA8buYQjL/0PR5fpw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
