apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
type: Opaque
stringData:
    LLAMA_API_KEY: ENC[AES256_GCM,data:iyEt1Pfvif6Nqq8fNJL5FmzZYsgOxguy/u9SUio68jf8oR43imO4xs7vdDAjWtdCuQNg8JvPfD9oiOlfk9W/XQ==,iv:3/DQEF2OEcf0b4qt0M3safpIOvl3a5k96XOqQKF/bGI=,tag:kuUkhDf/VAytN436iq5+KA==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:J0DVyvY7K2ZvXkTIXFl90JA06Y3l8/5IdpiMtK5dyxrv1hKuAr+YXUQ9h/0ZfWMQaz+4F52RazA/Xth+ytcqGw==,iv:AQV46xAja8bmvAAgbLJ7oOqIzQF//27h1lYji36siAQ=,tag:ZhvayQ9tK35h96sElEgyQQ==,type:str]
    GATEWAY_ALLOWED_USERS: ENC[AES256_GCM,data:J6+3yg==,iv:CBsBQer0+5lsDHvvXkxJJdLsg9RAPnTCdBQjojsw5KI=,tag:RuK67h4z4ILTNKIDvbz/BA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T01:28:37Z"
    mac: ENC[AES256_GCM,data:mxCoabSLWPe0+bAZvn4KSHwKb+DTuwZMBgvrVwSDuCP1a3uLw5uNYL1Q4pEo1Xfq0ShyedaimMDbu5wKR4xsCeDa6cz6Nw3/zf9dtHAFXR6KnKHee54wsJHsXYvLOR0OSUuToHaCyrAj7q8aJNgm/OD82aX3O5DAJHQTfvrZfRE=,iv:/+xHVnUte5sHKNq8gsCG1k5qDi4cnwqVc5uFOybtKFQ=,tag:T2V5v+Z1fJr+IZAPri1nvQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
