apiVersion: v1
kind: Secret
metadata:
  name: devshell-secret
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:Gnou2Q==,iv:y1T4wlInFwx4vROtqOgQtMIXZr2f5/GQLZawOeAGYT8=,tag:nTqmG8cHvHNO+gU+Grfx0g==,type:str]
  password: ENC[AES256_GCM,data:cHjLCJAPSIQ=,iv:6VN7i7kVjlYl//L61Rw0Y4cNgiWYka/3Pr7faqV6hJ4=,tag:tve9aPYl+AlOM+lNbSUd/A==,type:str]
  user-mapping.xml: ENC[AES256_GCM,data:mI+uIS1XXiaOtqhTLY9aKTdz6858V64W9hgSy9J27ytDpULpx5aGza9DeW4WGmCAI40VnQwB6ze0WPXQtA1bwt/sIDMGP668PgmA+pCpSVqr7mM8AQOnXUDbSmQxzm8xDxd9qdizBWHYkI1+N0q9+IwLi3a3N6x1E4UR3X/RKr7Yj/70s+e4gWhBg45e6lWi/6zuGlnghD4yJtp4uGZKXBHUV2u0h3yIjOJniPQ9KA4nnsS5tgTSIacVKX+teCbagtMGFYDdx7R4xd73EV4xg+hzNKzsCoOqX5BQ4AEYXP+bYV8lNb9+JLpG7sKTMbqZoph00F0WQgz0w5IqLIyaqG1J6Y5+K6j3mrXfjXldnJIt/C0Uqf/2ks103DpDOKGtrD/GsqnJpgTN9qUdujWzTmCXruRFy+opRePrRcDVxJL182XRJ+aq84wcTrpC0U1Sg7Vo3MUUUbZsJ/Q9K/qn,iv:bhOLQ71wuSyFUdi5NlzTabCnoGf/OXte4JirOL2ERHY=,tag:YqNyY6Vltab5wPLi9kpSTA==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZUpvdDVkUmN6M2lMRmhV
        eklhMnJRWDAwdWJRcnV4TzZjTWVXbHBnV1FrClhIc01xT3kwSkFJVkZQZExZUlZC
        cm1lNFpaTjd0dURRTEdYK2RJOGJ0TkkKLS0tIHk0NHkza1AxOTU2KytHcUIrb1lz
        dGdGd1FOV2pFYjhTRG42SW5rMjNKSUkKsTcoB/DEGBuiwaBFg241IhEEhuDb9qqD
        i21GVl6UPFLCg8p2Oza+RCevR51jhVCAly9gOpVrDrEYYUs7UxJmxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T10:27:15Z"
  mac: ENC[AES256_GCM,data:DeYHk0pY+g/YpRcM+M9rZOAPjIiOY4r4W7jv8NMFxaNAWGh2XxGihBbYNT5a2m91TQtzRaHXZ2IyMaG/QJf413Jp+KFRosonFLQJAVtJi08XQ6BJeoeQAwfFtJ+iD9/Eg1Ct4spqp4enRniPpCoZdVdsZ25H4vaVcnyijWG/fE8=,iv:Ys2nWoyGo5q4I+Bo6AF6hGuUsv3WaHdfZttm6iUtlY4=,tag:Lu9IYE6Q3unNxe1QEJ+G7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
