apiVersion: v1
kind: Secret
metadata:
    name: devshell-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:PLXbsQ==,iv:nzPop2TQqyvw7JenwDhJw0tikr275kpmwr2Y8bGi/y8=,tag:dEZ35fgydQl45JSfyvjndA==,type:str]
    password: ENC[AES256_GCM,data:E+lGD1Ry+tQ=,iv:GhGz5MCxBVb0CCiUJjq08bEEP55X5HewwKypgdcvnZE=,tag:JhX+80jyUevah6gUjPXHdA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdjhobUttNU5EWld0aUhM
            WllGSGxNNDJsQklIeU5HNGdDaWRkMDBOenlzCml2RGtDK21BV01rMVhtTVNhMnJz
            Q01jdUs5Zm9OcUg1Y2FES0lXU3hsUzAKLS0tIFIvNmdvQzZTZ3BxK2gzdEQ2S1Z2
            OUt4WFBzOW1OUGNzVjFEVFlDNlQrcFkKesOuwDjlHfgRjdAjZE25wdRMOOQKYbVB
            ESGwAIEzMDZTMK+V3gnH4KGlrnajUftNvLYeAbaME4gYPFqkAZwGuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:09:00Z"
    mac: ENC[AES256_GCM,data:MCwDiUmIAx4CjmHg9uDQWR4Pqx86w1+8BeBvmCuGrsMbDnt0tkLw+uG9mobnR6JDgF8KEayN6eBw2ajijmogro+dnY2SNy9uGRDqPcicWDBXeo40jXxRYH+7wXWHNJEv3nAFgcAzZOjE2dVbWyvGCyqaj+BOzoWbfSX0OiwgmtI=,iv:y9uQt6WcxfIxgRqdp3/Q86wUspffEeYzyBkhQeaFCAE=,tag:uhLERkzjQoUO2c43uAnSmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
