---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
# Allow all pods in this namespace to reach the Kubernetes API server
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-k8s-api
spec:
  endpointSelector: {}
  egress:
    - toServices:
      - k8sService:
          serviceName: kubernetes
          namespace: default
