apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
type: opaque
stringData:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lhxHf67xSCqRPmknC3sKzBvBOkhjKZQwcOIIQ08v+g2J4OOTeHE408IOIXKxfDA4DU+cJhAKHALIDmNGAO2l5T9/HVTZMKYw4oYZCAc9jxd2teJFVrX+CPK7RFAbk4sXec756g9nGwkoW9xzkoKe1Y9Til4pSayHxBxriJJ/YiI=,iv:U8Uby9mUFSh/4+BYzYqm7lzoSMMtSencr06lVeGe4sM=,tag:Fa4h7labJ80PSLRZ/wmCaQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:4xEsCXF3DpPzupo9j+6+x2XTB7I02uV+Wn2qr6ZFGlszC9MmdBrjSfFtAqD1GNApUO5LQmhSpH0OYdJbPEln4g==,iv:d+uaEVlo9YYAPqcPhOlvnCvIIuLfsDF1bffUe/LWL10=,tag:smBQORR9C37V9UoPzhi6LA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dTZNT1FkWlgyR1dqeVJG
            RVFjM2Z5aUx3cVhuY2hsQURGbVkwVDV5TmxNCjFETXd1MVJyVXRGYzdCSUFNZXhz
            dlQzK2NXem55eFJVY1NwRTdsSGRYNDAKLS0tIEdHOHJoNk1Hc1VRNGMyV3cyMWZl
            ZE1SNjliUExlcFBCWXNqRlNJTWU1UUkKXhFC1eRtR1RvgusoEt3Cj6O6tsTQig3J
            aEQhOOrDOG82GNcsU8uPg3U+dvwXsEXn7HSPfknKc3FE1LVogNA4mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:58:59Z"
    mac: ENC[AES256_GCM,data:YpQKplMjBEqRUxfWQG69ACYmP/mxCac5xG9aZ0kp+AHiL/1Ykwb9GFtk8aFS9DvIEw9OeZR0+DO7DX/XGJrVj5CfOnSy4fzBHSTEy0lEhtnqcSpBtwjx+TQP/kD57V5mFUkRtboQaM+/7+S+l/03E9SHE/bvcqtxp1CE4/ZUt3g=,iv:Hv0Wv/KCq1hqC2+8vmBZwXT8HmY2B4sc/jypyxOnMEU=,tag:7O1i6SZgnOpCnPMjZEXC3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
