apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
type: opaque
stringData:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lhxHf67xSCqRPmknC3sKzBvBOkhjKZQwcOIIQ08v+g2J4OOTeHE408IOIXKxfDA4DU+cJhAKHALIDmNGAO2l5T9/HVTZMKYw4oYZCAc9jxd2teJFVrX+CPK7RFAbk4sXec756g9nGwkoW9xzkoKe1Y9Til4pSayHxBxriJJ/YiI=,iv:U8Uby9mUFSh/4+BYzYqm7lzoSMMtSencr06lVeGe4sM=,tag:Fa4h7labJ80PSLRZ/wmCaQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dTZNT1FkWlgyR1dqeVJG
            RVFjM2Z5aUx3cVhuY2hsQURGbVkwVDV5TmxNCjFETXd1MVJyVXRGYzdCSUFNZXhz
            dlQzK2NXem55eFJVY1NwRTdsSGRYNDAKLS0tIEdHOHJoNk1Hc1VRNGMyV3cyMWZl
            ZE1SNjliUExlcFBCWXNqRlNJTWU1UUkKXhFC1eRtR1RvgusoEt3Cj6O6tsTQig3J
            aEQhOOrDOG82GNcsU8uPg3U+dvwXsEXn7HSPfknKc3FE1LVogNA4mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T09:58:10Z"
    mac: ENC[AES256_GCM,data:FuiQepV9Lnxf194Hgabe20a3SbWVXYjRGBnt/DwfNzi2uSdffFDWskTW7OmOEhfFb69OP259jFXUhMtaJGNxyRpDuaGxwsDxO+wipSokw5piCUsmUDHjS0zOyAF+RNqhJ31SwcSoAh+UnhGFxWu3xvak0v746QkxoNrH3C7u7eE=,iv:5irC06zFdjjJgpwsM+3TOmhkZzO68flZojpRnya3/+g=,tag:xfE4bWkTUDniWnd1kUG/6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
