---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw
spec:
  chartRef:
    kind: OCIRepository
    name: openclaw
  interval: 1h
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    controllers:
      openclaw:
        containers:
          app:
            image:
              repository: ghcr.io/openclaw/openclaw
              tag: 2026.5.7@sha256:1af3f457a2d5a1d210f4d95634fa5da6e23f9c0ac7b52ef4bc38e2ecf09704fd
            env:
              OPENCLAW_DISABLE_BONJOUR: "1"
              NODE_OPTIONS: "--max-old-space-size=4096"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 3Gi
              limits:
                memory: 4Gi

    service:
      app:
        ports:
          http:
            port: &port 18791

    route:
      app:
        hostnames:
          - "openclaw.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          openclaw:
            app:
              - path: /home/node
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
