apiVersion: v1
kind: Secret
metadata:
    name: openclaw-client-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:d1WJSKRw3jTgPZt/i9FYB+NIp1vIfjAk1shVeV24jXGnzuRhOh/x2plbVDdyec66N4YttBdVZuOeycxd5+a5yXy91WBMVAxk/os2e4W5gcGJeDHrqLkyd8NWgFwm3QlMOvWfsP57FHr92gJk2U7vbBneVA6a9MJkd1QTOcgaV98=,iv:CCiBtAACmcDci2EEt2RCCnNXezLIYlZqXtlRTahmp3Y=,tag:v0MTTxQM+O788egtexxUhQ==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T00:10:45Z"
    mac: ENC[AES256_GCM,data:LTzYqPhHEpWL6o8G2MCplUfytHONUTyWOmLI8J9LetbT9hKoN69sIyqbAteCv517iR6LStJ6am03vmNnxIwXrPXTZA9fLQw+xayybxWrwje/SYPCs3xoFEEn3ybF7Amla8xpFnpC+NhjKpbhXIYQPYnSgMHLYL3Iv3jmBamHaGg=,iv:lGQa6GnkBes1V24S+BW3OHWJ1U3RUnb68frhMq4Y3r8=,tag:Oh081a/pvGLYKdKF5JMpMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
