apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:g0IFK/wGw93GlGHh58SJ5XXYiitG00bIurT1d7wfuJ/39xkvQuPFpRzmawRljZVumuCBEMsCtJZrANjSDc85pg==,iv:Ld2/T2bwoKdtrfq4G3iUPK+g2usazURnI4QLrA/hjHo=,tag:3akVEHEhHRe/JfEHRR2uqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T00:55:16Z"
    mac: ENC[AES256_GCM,data:bC9UwML3XfxKwrATGQZJySrwFDxOfWdhC0/TLKVQoa8XLzfJr/WBl+IGEVTq7MQM5D/ioKsMIzplrGv3f3WQmx9ZQX5OIP+ZtonjausM0LsPV7tN3sEAZazU6AM6UxUBim5BcqzC3WmVHQ3+UO4cTF/uFkBvZtPt6pvQGf3rtDg=,iv:PQ+Os5EGesAatNc1rQNM/GlVvWWQalOkjNYr6EgYOoQ=,tag:rP+z1q9X7jlorC0cLdr76g==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
