apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Mrl27w==,iv:vtEdJa2/9fgICTgNvPxofjbHHSDUeB1DqM24uXCzRMY=,tag:ed7fWVdUopPHC45CpjefqQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:2zpq4ZYaAaQ=,iv:g34sW4XcplcawTda596b+BlAP4aTMt0GzpSgTnzUeCA=,tag:4t2cpBZXJicFm2W6lj3DVA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:h5NQPlwMWDspLSJZv41W4mQP9BD9SxTcxNFCPQZxhRvIRMsTa7TtKb4W6yjRJCUy5E3UaBjOOwrLE4wxhxhulw==,iv:Z1tyTKl2o9AfoKaWfI3UW5v2zyd836Bu5PCDbDhbVXc=,tag:gFgxERqZAP3SWYMBEQuWgw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T11:27:56Z"
    mac: ENC[AES256_GCM,data:DKecb9JU+C1AJR88IUi0/CZrgplhmMhCpfKY/SWTJ65ReMskHvuP+IOHL6CUQFKaYVp/lDcaMC+7gC1Vk6y3cHJ3y8S9oZ0oKCPgsFgHNwwv5iI6AGJM+a/zEmqiIYFL8IXQdxtFSG2x7k+B4FJTZIikBkCbi1QZzjyoVQK26cw=,iv:azYV/aC7hsdMjTlpohyC8PLKVP/24wDsZeFSOUM1LFc=,tag:x5pcWzfE4ufkmQh1GqkvZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
