apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Mrl27w==,iv:vtEdJa2/9fgICTgNvPxofjbHHSDUeB1DqM24uXCzRMY=,tag:ed7fWVdUopPHC45CpjefqQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:2zpq4ZYaAaQ=,iv:g34sW4XcplcawTda596b+BlAP4aTMt0GzpSgTnzUeCA=,tag:4t2cpBZXJicFm2W6lj3DVA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:h5NQPlwMWDspLSJZv41W4mQP9BD9SxTcxNFCPQZxhRvIRMsTa7TtKb4W6yjRJCUy5E3UaBjOOwrLE4wxhxhulw==,iv:Z1tyTKl2o9AfoKaWfI3UW5v2zyd836Bu5PCDbDhbVXc=,tag:gFgxERqZAP3SWYMBEQuWgw==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:1J78hRTM7W0gpg4A6CPn4z9HuzA4PET8TyTr8fvMcnIU3fbZYGXH+9qajysbokG/mZ7CdjYHNX4QxUTdyw+qa6l3gk0MmXvHxmlZZ8sxGJM2aUkHo1LHOC6z1EAQelfljZFuNybZMg2EeCwtiMSblmUBudyp1WwCjFK5aF9QKZx93A2KBRRZg8fpYzUIIMbSHCk33DwYxV68zsTIwCDES3LYomVXhfBfveyfhldd/CcQfwi6EN9E3/havuJU1ws2Mt6QNhTIUOntdLuetDXZS6Mqq50eESwR19ffa1ghJCbMU5tHPUkU2J/O8agXHPm9J7ObWO7g3UV5zOZwqm69UXov/rE05kyG4TkCa7FFEKFbdza/0+4uezUhebYeMQnPdKnjIIYMsnMUa0l6Hfdj5HJVyChgUj0EAYxNQVtZK003WZiX+SNEvJFdcWK6NMlloGjSOqF6Y8JO8Ea1KYAtUOYmLUR+AAotWphpgLkPszo3bcM3dJTp0ThKX1q0DumvOa7Oyl3dncxCFCjRaVnxNvZwqobXLinaM63CGRvkP6YLnFqVlJyBZkPf9PoHPftY6lmyiWRAo+LzVKNvT1uKx/QaIaa7y4Z27vzpCV8rNsDLaNnnMVerl+OHEtQNUAjulQcouOSR6K8wrjixHx/4ijD8jvAXZ6TFjjBwE1OCJJFQHh0n4yL1uW2Z9R7CK0tomBCjOErIB1JKwFITlCP6gVNUdSNwLW6yIQThdmsPHK6cCdzCOCAGYZttVu+uuYErM9KHA5Mjv7fG/+07fCQ4DVoUYg==,iv:9ZsCG5mTmCPmAbcVpHg1ZIu0/7gqjnGfO51xp/IEVgc=,tag:ZcYg4T0uH7jNRp+XQFz54w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T13:33:41Z"
    mac: ENC[AES256_GCM,data:Ec3gE2OBNncrH7wznvgGtfcE64L6PZNTg5AmPhoc7gU45PhB8gEmh2LLeNTF8yNMnEtNwyKsn7ZiIaDrcyD4++ug2TfOVv+8cKT1wUTHk6pjwen1pghI71jnivy9g2Vy9fF0oklothV16GWFsyiQ5vRr8uzonDDrDFZDD4RKAv4=,iv:afeJyS42TmlDnuPZy1NAUM+rfCYYf3OJaUdE8lnA21w=,tag:p7MOSixKYoG0O/KXopZO4g==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
