apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secret
type: opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:NarijTu/R2beQ8Y=,iv:mmYB6jcvoh1lZK5j+XbUeUTHlHyn37Falo0RZ/uhN2Y=,tag:MuNVZZK6C169ZUUDcQPouQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:kVyRsJTfagI=,iv:mYCtEo7tYOZu/Y+5zE7cTdfBebwZ5+IuOerztIYMdeg=,tag:wSgm8H57YJ1uTPJ34KTlPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN0MwTkVtQytUempaZUZI
            c05wUWxFWnFZRVZ3dE5OakVsa3JoSllzYzNrCis5Uld5TjkvN1REYmpxazJTNm1B
            cjVsT2Q2VjhLVzhydWdRdzcwUU9rTzQKLS0tIHQ2RHArTitCb1NkZ1JOQlNrMUdl
            QXJmKzVONEx3cUUxYkV4MEExcUJiUWcKuDClaaXhJvK1iAIQoGfAiqxPIdzvlx6+
            UufonDFGN7fePzMc5Jbx+dj3e1jqf5tHTh6xBb0JcJf3BoWMEk6ZBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T23:01:08Z"
    mac: ENC[AES256_GCM,data:/olU41787M1pTHbQuZFSwMenzG4vQjSe/Mga8+rfqW7P7dz8CP8n7gdQjng9QIOWXlvnXah54hDrTHXyQrBqNDK6Bbk251Ff4nP+oHw9tOgQi+ywkcSqWDZoQuqwx4IL0ugH7Xg1bSSPpqlwkewitPiIxK5sFs8ZwHKkHQHVUXM=,iv:Nt43CTQ1KwDHmPLxpmySALiuaaNNFT8O8JoPofa4/+4=,tag:OacJEQfB2nBDVK1/nkad9Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
