apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:pI6Tx4HS/UMePs4=,iv:w0YDmwQyBvvcnVL4pxt2pMiEz0UX41WhuZa+tMyX2LI=,tag:TKS3N46o0cAhPhsng5OwEw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdHVhc0ZvWlROVmwrMmI5
            bGlPR2p1cGhwTDNCM0JLbDRqajR5VjlMaFUwCkcwbVN5am85Um13Q005REtpU3Bo
            OGdIRis4ZDBsQmdrR0F1czNaejFmQmcKLS0tIGVESWlFZTY2Zkd2OVg1cG1uRU9n
            cFNZa2xyNDlHc3FrTXpZbUhRYjVBZXMKgocii8dbOwcAI1ePYiKgqjUEvnnJKvcj
            O4YYobqM6GS2et7ch5+CePV0syPWrrXf+VG1cswYnfReRX7OQPO5YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T22:33:32Z"
    mac: ENC[AES256_GCM,data:kHkQZBNX8yVCr24JYMIdtQKZAlTnH1yr0r2g+ZQcL000Qx+M+e4LVfFLrPe1JgHH98bCBrTVrJQ2LYu6ttgTEaOt+TDM092chQGuH8cvI0ZO1LiMgxvpSh1viKvWT6wagLijkDpuCYrdgazBo62hfeEO2LmCOn4u0bDuI2NtWfE=,iv:LeIov+W5Fzt7p7IJ+yojwLQZ9xR3R0HppUZ0iyoVACg=,tag:QQW4Ge/k/c2oOVbvCpbCPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
