apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
type: opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:03ndE1hDTUT4J14=,iv:8xIVaBVgNzMFTRlV5QSnQuZI7ZIe7P4zZXbo9eezeHs=,tag:GJWpVwrBhDSwkp/JuqZuCQ==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdHVhc0ZvWlROVmwrMmI5
        bGlPR2p1cGhwTDNCM0JLbDRqajR5VjlMaFUwCkcwbVN5am85Um13Q005REtpU3Bo
        OGdIRis4ZDBsQmdrR0F1czNaejFmQmcKLS0tIGVESWlFZTY2Zkd2OVg1cG1uRU9n
        cFNZa2xyNDlHc3FrTXpZbUhRYjVBZXMKgocii8dbOwcAI1ePYiKgqjUEvnnJKvcj
        O4YYobqM6GS2et7ch5+CePV0syPWrrXf+VG1cswYnfReRX7OQPO5YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T02:48:47Z"
  mac: ENC[AES256_GCM,data:o9URUb+FqkPHTrBJ3xy1unDdTuKVkmO7UXLlBO4HnV4ck3ToIAxxfd57X6xbVBGSz49bENewCUlNcQavapJIsFwpOlAz+SwJeVpkjtX6ga4HBssvGChw8P13pPNE7q5+mWew+Pp3uaUs1DuY9m79O5qqaTVrkSFvuUAHjm2Cxig=,iv:vxCj/Hm0V40BPBJ798P0MM3enT90bf5cy8Nj1zz/DZA=,tag:rfEye8riXgjc6ub3gPUSbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
