apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-secret
type: Opaque
stringData:
    INIT_USERNAME: ENC[AES256_GCM,data:orfkbQ==,iv:04KNCcVH1t8U0KdI4FAwpWE3tDcihBkHrty9gJDGMtk=,tag:4+8AZXlPBrdDA6zjlHTrsQ==,type:str]
    INIT_PASSWORD: ENC[AES256_GCM,data:LbgY+s2UQNDq8Ly9,iv:juxi0vC3+Hfr2q5dW3rrAxpaSbsQENSDoXqIiv9CY2Q=,tag:St986gdpmxCd1xJw6MegAw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T02:17:40Z"
    mac: ENC[AES256_GCM,data:aZ5zjiA5gP4aq6LqSITFl0ZagMHMjkWcKezQrSDbMYX9Mslm4Bl1TUAF8Wa8V/qoiN+dAPdFgDejeSuGBnpNbcClwsgDPN55kxeTVLVINPfIq7E5lmUqeoJYqnnZmEpMNJ73yHVHxGh1V7TL8yfgV2n6z0MCVJK5/cBfBd6JQiA=,iv:1ze0hq9TwZXXlKuOjzylDdEiryBSBkuf6n8uMaPE/oM=,tag:brGAWvDGH/cUKAkbAi+Qow==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
