apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-secret
type: Opaque
stringData:
    INIT_USERNAME: ENC[AES256_GCM,data:orfkbQ==,iv:04KNCcVH1t8U0KdI4FAwpWE3tDcihBkHrty9gJDGMtk=,tag:4+8AZXlPBrdDA6zjlHTrsQ==,type:str]
    INIT_PASSWORD: ENC[AES256_GCM,data:LbgY+s2UQNDq8Ly9,iv:juxi0vC3+Hfr2q5dW3rrAxpaSbsQENSDoXqIiv9CY2Q=,tag:St986gdpmxCd1xJw6MegAw==,type:str]
    bearer_token: ENC[AES256_GCM,data:Ug2RmQyAwbPXw0QesJTjMb6x6H9ud5OWsTHlW8SAROba6c+CcnzgmPlWFNJAOk+lvvoeZfzqPhlACkjYun/fOw==,iv:EtauwMMbYywCAXwPMG9H/teSVbmtLS6iOddjuvW1C0Q=,tag:DnN0TRhielalrLNut2IFDw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T00:58:52Z"
    mac: ENC[AES256_GCM,data:k6kj5i7Id0ASGFVeKvRxbfrUkizSdS9Dy2gAiVl1ElkpTyBrBN73JWR4RbDxJlOKFykny6DDcNXU/+aZYFzD25ck/iW3Z1gFeqd6YW+WcM7i7elA8ooeSwolKDpf2LZEwtyTbjDR2d9/l2axOnCsJxNriAHYY3u8riJMeSfmQgg=,iv:KTqyO8pwSl/actHzln6xYBexOtqqQ8XHxYo/WpfePTk=,tag:f5YpyhY5cFRe+lkH9p3drA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-client-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:5sAJpozcSzlgVY3AxGZIAOi/TF34Z7S00uI3/smdLRGSQcEE3uJqrxasg7xoXSeLR/J1uy5RszqTeQsO1QXLDgWNrzvsNM/47iHOgDDWD6X7eu1pleUNXCkAYW0PjVDl2h2RI6aN3oGu+Y7P47xmiLCI7CLJAuH0qEXEvhdoMvs=,iv:fMCVgL4L/TfBQ0cc9N1rXC4HfO3JTfaXLz0TPzadRYw=,tag:GCZaTvUpmp+hzblz3otiTA==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T00:58:52Z"
    mac: ENC[AES256_GCM,data:k6kj5i7Id0ASGFVeKvRxbfrUkizSdS9Dy2gAiVl1ElkpTyBrBN73JWR4RbDxJlOKFykny6DDcNXU/+aZYFzD25ck/iW3Z1gFeqd6YW+WcM7i7elA8ooeSwolKDpf2LZEwtyTbjDR2d9/l2axOnCsJxNriAHYY3u8riJMeSfmQgg=,iv:KTqyO8pwSl/actHzln6xYBexOtqqQ8XHxYo/WpfePTk=,tag:f5YpyhY5cFRe+lkH9p3drA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
