---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: wg-easy-oauth-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: wg-easy
  oidc:
    provider:
      issuer: "https://auth.${SECRET_DOMAIN}/application/o/wg"
    clientID: "WqgzUIgnNj8mRt3VgHcCAi2Mt2jpzONuTXBja154"
    clientSecret:
      name: wg-easy-client-secret
    redirectURL: "https://wireguard.${SECRET_DOMAIN}/oauth2/callback"
    cookieDomain: "${SECRET_DOMAIN}"
    cookieNames:
      accessToken: "access-token"
    scopes:
      - "openid"
      - "email"
      - "profile"
      - "groups"
      - "offline_access"
  jwt:
    providers:
      - name: authentik
        issuer: https://auth.${SECRET_DOMAIN}/application/o/wg/
        remoteJWKS:
          uri: https://auth.${SECRET_DOMAIN}/application/o/wg/jwks/
        extractFrom:
          cookies:
            - "access-token"
  cors:
    allowOrigins:
      - "https://wireguard.${SECRET_DOMAIN}"
    allowCredentials: true
    maxAge: "86400s" # Cache the preflight response for 24 hours