apiVersion: v1
kind: Secret
metadata:
    name: immich-s3-secret
type: opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:IxS5X6+6,iv:250OJ8RtTDOnl+qnNzp2AXbiNQdN/OPDDSLwSHOBwJ8=,tag:NF9A3Q1WNIaZTduDS09fnA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:8yL4cEPHTBpgY8z++ygjhngs3VA/RGO5W4Mo03FuhyU=,iv:WOQSJqjHT1H8u5Uy4J3ebDIm7/izp6Od6cvTyTmcz9s=,tag:r7wjCuAHgkT0fWyhQMjV0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T13:13:52Z"
    mac: ENC[AES256_GCM,data:t67H2yg6gsiCMBAYRLboLJkYcIxgih56uSjxuvcOvqaFwyNQltriHJDiCsAKgYpgbFonTO+om80JdZcBlJtgt5nh1PHWQ9Z9wXhPvZoSW4xDkfyZwGRJBEVzxV+hqMvCt0ioEjxJJ6IFIXkWod+02q6TALvyM7PAPLleFfTiqME=,iv:bTv6V9FdTO2LEIEPsy/ftcpYmRMCgFcPSltfG94m4R0=,tag:zsKN9wr336NZjp3ahil5pQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
