apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
type: Opaque
stringData:
    HASS_ELEVATION: ENC[AES256_GCM,data:2rQ=,iv:Qg71ekDCBeKyFEM1+bP7TVoryYwFtiDrjNTyepwDR3s=,tag:WmfEFOTllPHSUYOvz1cJow==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:mSiYH+z//t3EIA==,iv:pC1IEZm6J66nIAuA+ak/lWFIBwARRz+0lwwJMyzDNl8=,tag:pw/FQlMvYrAj8bfGkCVoJw==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:qAu692FdlLJTK88=,iv:zpq1zuhy1tgS581Xt4J+IHwZlbvfNQ1teAeisqsX+eM=,tag:UnqvEFIAFYAeJw3FFL5XGg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ09qdzdnWmZ6WFhTcnhu
            NDZjbWtYU2xlYUNQOUZkOFRXdTE1RmdvaFVVClZWZERCbUFnSEZ1cnJqK1ZRMUpk
            bWtOYWQyNDBRVkpaY3FnanZoazVnaEkKLS0tIGRCb3ljblRXRkNLL3NxSGhIR1F4
            Z1dvVmNUMmVqWjlMNTAvWFZ2ZGUraGcK3bczg8qeC8VH5jveInGXFhEbFuqIjee7
            bhtMidDvlaiw0oJsIvzOQKhB6OiZoWId3vZrp+VvRwYPiMJrvsMlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T02:14:30Z"
    mac: ENC[AES256_GCM,data:U6XDNmC0Yc3PvgmTW5c198lFv6VCrTkJMo0UcYRyGcfk7tkk/zZCAF/KpCmDavousOWgQp9Q6reUunsE9riVubM/4AzBeNitjA+Ohv3p1FUL5Xq4/4HQN81f231yzAlF59D+en+4yAQr6c1O7iBvgaki4QQZmujLlN+iQXomsm0=,iv:HcJOZdV5WMKYWyhY/AAL0/kgpEuJjGr05f/Y+35m/Cs=,tag:QaIwvMp6eTnN9dLcNFnehQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
