---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 2

  storage:
    storageClass: ceph-block
    size: 10Gi
  walStorage:
    storageClass: ceph-block
    size: 5Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-cnpg-s3
        serverName: authentik-db-v7
  bootstrap:
    recovery:
      source: backup-source
      recoveryTarget:
        targetTime: "2026-06-01 01:00:00.00000+00"

  # 3. Reference the original cluster's backup using the plugin
  externalClusters:
    - name: backup-source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: authentik-cnpg-s3
          # This must match the exact metadata.name of the original cluster
          serverName: authentik-db
  monitoring:
    enablePodMonitor: true