apiVersion: v1
kind: Secret
metadata:
    name: authentik-s3-secret
type: opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:MSCY3y+ndwyk,iv:paHMQF5sw8lLuOPAyV1RFqwRidwOuo0ETdhGn0T/aCw=,tag:3K/FHWA6qK8I9KP76F6wZQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:vfV68buDnh+mhxM5W/3MzdQlKb4wcwLsjlDncuS/S+o=,iv:Rq5iwEECFzepUx1SH9cVCKz0U/cqBhB4L0YW5nfJOME=,tag:ITz/ozo0kMJVPiVmCmSnfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnJSN085Um1FYzJlajNr
            WGRTdXhDQ3l1MnNUWEZVUE1taFhuS0JBSjBZCkRHTEVGR3lxWEI0ck81eUtYbm9z
            VXdIOEh2aEYyZzZBUzlkWnhBSzBMMXcKLS0tIHAwNDY4VjJrVnJDR0t6eGtncHFV
            NWl2ZEJmUGFEdDNpN3ZJeTZLMGdBUkUK71h5I/GAVe+QekiiPjO/VBHgTg1ubO14
            QFi0ilK7AGFv+W23tvIpuRyJ97NxNMyRUZ5FdnLUtof0QOnNxSm/sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T12:45:20Z"
    mac: ENC[AES256_GCM,data:JqGgAv/fMcWbB9Q3bb/Mj+v7XGyOL+2+Ip2wv8o2m79ngfOnqfXpFak7QcsvSQGD1ABINc09JEZbBbXZ8dvvbeyHWzxH1YqU9Spz2ajMZAHYBuwsunXiwl29+u9oeX+THZ8Upo0tE3CUg8DZmIgoWIuw86jV7Aa9wmehR1F2Ats=,iv:YNh73xTNY2QhNjR4zwRw/idHxd+68Ss/cTPmFicQeKY=,tag:y2IRFl9L2QcJNpwS8CFI6A==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
