---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
spec:
  interval: 1h
  path: ./kubernetes/apps/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rook-ceph
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi-driver
spec:
  dependsOn:
    - name: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/rook-ceph/rook-ceph/csi-driver
  postBuild:
    substitute:
      APP: ceph-driver
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rook-ceph

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
spec:
  dependsOn:
    - name: rook-ceph
    - name: snapshot-controller
      namespace: kube-system
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/rook-ceph/rook-ceph/cluster
  postBuild:
    substitute:
      APP: rook-ceph-cluster
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rook-ceph
