apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
type: kubernetes.io/rook
stringData:
    ROOK_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:Mryhrp901vm8RK0bftFnZg==,iv:/4UKlkdHdsb1aUm8cNS9uW0N2wCXlVriPXulzkmGbJg=,tag:BdCYZOrp6cvUMIwSj4kzcg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN0MwTkVtQytUempaZUZI
            c05wUWxFWnFZRVZ3dE5OakVsa3JoSllzYzNrCis5Uld5TjkvN1REYmpxazJTNm1B
            cjVsT2Q2VjhLVzhydWdRdzcwUU9rTzQKLS0tIHQ2RHArTitCb1NkZ1JOQlNrMUdl
            QXJmKzVONEx3cUUxYkV4MEExcUJiUWcKuDClaaXhJvK1iAIQoGfAiqxPIdzvlx6+
            UufonDFGN7fePzMc5Jbx+dj3e1jqf5tHTh6xBb0JcJf3BoWMEk6ZBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T23:20:30Z"
    mac: ENC[AES256_GCM,data:CxbyPVAA6rGuFW1TJ5pVeUQ5r1EewvFIpeuBwBjadEZzHIxHYdpGfsnYmKe15E0YzDUgIyzlLccq9D3LswdETReneQoWFXWVsw3KfmKa9xwCO0+GVHcsNZfmWb7roTcuTq54mC5fnzJDddFXxWdlp1EbSQMgjiaHBgv7v43dqvg=,iv:s/+ybw5TClEWJa7GHOydKAv0TEWsGwpUYJpBGIodFMI=,tag:IzTyWTvU4wwoBtlTiay2zA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
