apiVersion: v2
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  ROOK_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:Mryhrp901vm8RK0bftFnZg==,iv:/4UKlkdHdsb1aUm8cNS9uW0N2wCXlVriPXulzkmGbJg=,tag:BdCYZOrp6cvUMIwSj4kzcg==,type:str]
sops:
  age:
    - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN0MwTkVtQytUempaZUZI
        c05wUWxFWnFZRVZ3dE5OakVsa3JoSllzYzNrCis5Uld5TjkvN1REYmpxazJTNm1B
        cjVsT2Q2VjhLVzhydWdRdzcwUU9rTzQKLS0tIHQ2RHArTitCb1NkZ1JOQlNrMUdl
        QXJmKzVONEx3cUUxYkV4MEExcUJiUWcKuDClaaXhJvK1iAIQoGfAiqxPIdzvlx6+
        UufonDFGN7fePzMc5Jbx+dj3e1jqf5tHTh6xBb0JcJf3BoWMEk6ZBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T22:51:59Z"
  mac: ENC[AES256_GCM,data:/itidNASpFwCZ477kyFQSVPWjCWEl7LtwmOiCK0Y/U/XZKXQCgrNkDwowNuYDSjO/CuFRp31skqDI0iwZUewhruMP/D27Z0b1+7LX7lsGdUUfIsb1W6Yr8fLXq2ZuRe0IrPL4q2ZDzq64GScvmr93fuNKGvjd0YhvgcS9Q5k1B4=,iv:ujgLi3w3e6eW/siNjXUTxIm8X9Xullj/voGqJgARZDQ=,tag:HPQzJcEpDEgx/6OyLjKf5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
