---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sensitive
spec:
  interval: 30m
  url: "https://forgejo.${SECRET_DOMAIN}/delf/sensitive.git"
  ref:
    branch: main
  secretRef:
    name: forgejo-pat-secret