apiVersion: v1
kind: Secret
metadata:
    name: forgejo-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:LpHS8OcHaOwvdbahI2pGbVZCNOpACcqZwE3eaZzvBxcV7vPhReCRZA==,iv:XgYYwm+hUCtC0VQmC6wNt32cNQvKxXgjSXegHTxcQE4=,tag:ApPKBiu3ThslhG+X0+b9Zg==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlBhUzBQVXhrQW8yeFl0
            NUg3WDltTFEzaUMxaTR0M0k1cll2V1VNRUg0CnZPbVBTWDQ3N1dhdGZGVXFNa2hq
            U2ZCMURaRlpOQStCRGR0Tlg4aWdKYjAKLS0tIGdLWTR5c2tyWEtlb3o2bXZYdnVj
            ZDdIMEtMS2c2ZGU2ZStDNUJiRi8zdEEKNjyFFdX51JcWGficVv3WUklBa5eVdyet
            2Be4lG4VpiqeM1SsTG1Wc4MIvv341EBH901x/4zSjM33UddamPWO6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:18:30Z"
    mac: ENC[AES256_GCM,data:HQXiVI6AolLxs3PwVir/KeAU7mXJfZ6qYLCkHHzrGGFc2TZooWEAEOwhqtbRUmCxbCXgUmy+n0/cThIP/++qDjcWZZcx9p+A1v6WYaYKkPsDt6I54C6ZMZ9R+YUGDbHvrQHkT1Djc4PEciAvEZ5m1asyXT+GkyPnRcQ5HG2sEMg=,iv:orWW2OStiPAyJZHWs6ZwDSVUSb2gfvJ34aBnZL8b2DM=,tag:wF15cExAgpuo+z1Au6fdDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-pat-secret
stringData:
    username: ENC[AES256_GCM,data:d9sF7w==,iv:A3fab8CNMbWUKK4PEbc0xJsZfk51fkT5yMqWK0x9r/g=,tag:TAzh6brHZcShBAsYvjE4Ew==,type:str]
    password: ENC[AES256_GCM,data:N/TgV5GTqjvVNKd0nivMXCmJTDG7TnR9zG5X1Rxuuu+NJggc/W/u1w==,iv:8G20U7C23sMET+yVHQtylOXihhifsXP7HU03sQ1LB+Y=,tag:SZLFxEuu+qHgJf14Jzz6jw==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlBhUzBQVXhrQW8yeFl0
            NUg3WDltTFEzaUMxaTR0M0k1cll2V1VNRUg0CnZPbVBTWDQ3N1dhdGZGVXFNa2hq
            U2ZCMURaRlpOQStCRGR0Tlg4aWdKYjAKLS0tIGdLWTR5c2tyWEtlb3o2bXZYdnVj
            ZDdIMEtMS2c2ZGU2ZStDNUJiRi8zdEEKNjyFFdX51JcWGficVv3WUklBa5eVdyet
            2Be4lG4VpiqeM1SsTG1Wc4MIvv341EBH901x/4zSjM33UddamPWO6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:18:30Z"
    mac: ENC[AES256_GCM,data:HQXiVI6AolLxs3PwVir/KeAU7mXJfZ6qYLCkHHzrGGFc2TZooWEAEOwhqtbRUmCxbCXgUmy+n0/cThIP/++qDjcWZZcx9p+A1v6WYaYKkPsDt6I54C6ZMZ9R+YUGDbHvrQHkT1Djc4PEciAvEZ5m1asyXT+GkyPnRcQ5HG2sEMg=,iv:orWW2OStiPAyJZHWs6ZwDSVUSb2gfvJ34aBnZL8b2DM=,tag:wF15cExAgpuo+z1Au6fdDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
