---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toolhive-ui
spec:
  chartRef:
    kind: OCIRepository
    name: toolhive-ui
  interval: 1h
  values:
    fullnameOverride: toolhive-ui
    podAnnotations:
      reloader.stakater.com/auto: "true"
    env:
      - name: OIDC_ISSUER_URL
        value: https://auth.${SECRET_DOMAIN}/application/o/toolhive-ui/
      - name: OIDC_CLIENT_ID
        value: gd51JxrUaVMUxpJBm4bIDcdr17dhZzx56yALAEXs
      - name: BETTER_AUTH_URL
        value: https://toolhive.${SECRET_DOMAIN}
      - name: API_BASE_URL
        value: http://toolhive-registry:8080
    envFrom:
      - secretRef:
         name: toolhive-ui-secret