apiVersion: v1
kind: Secret
metadata:
    name: toolhive-ui-secret
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Q3IFebWCvpAumqh3tkGbKu19/5C7vp0yT/adfQEvKKBVvGVUsI4govG/2m5gY5DF3x5dCBdEEQgWfk+8PfpqMtwekDpslzFcvOd/Zz2Qzk1jXGGl1NvropPBEFnm/jRS/opAMzQGCFQSLmRzUYZX1XADZmhGYMJ4cIwZIzEvEvk=,iv:KoBk1VSiEs3C8pa+BvvoFoLTFrXodrFhR3RHy3PnUXs=,tag:w28K4CJ0xhtH9AlXBjYcEg==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:CKmZrIEtsg9+IDAfHV0QZlImQMSP6Ewtv4wug92JXOgx2PGtpl+/kI6snTo=,iv:AQf37urERsj59q57wnIKp+h5kPOpt33oeBizsiUGkkQ=,tag:G5bYY80C1n+8bt/FxKRnvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T17:00:48Z"
    mac: ENC[AES256_GCM,data:2t+AdOgGD1zSzzAk+/l4ENUWSeBsKYu0/Ti4DNYjdUmxDFE9xSbhBS+0B1LRUCEHD0B9sTxb5GRs8/rKmL0Dbw47RFaW/j8n42WFPfZqU38fbgaGNfIv5cTtNWBO90KymLbI3lPZG973E+WRSFg0DoNV7rAz1CZPURStuCakLb0=,iv:czYea8a0DjM0JxIwDkE0UawSuBZGahboJrlorbU4X90=,tag:wm35Cb76RjYNtkTk45IxPA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
