apiVersion: v1
kind: Secret
metadata:
    name: oauth-client-secret
    namespace: default
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:3Q3hnF99Q261wo14uzPRnt93Pk02eQ4yzoNhTnSfsPs=,iv:C8ItEhgqLSfN3gIbdj8BHWoC3oUdyxPox5KZITDMkag=,tag:QJvwrPdc4c1ipM7teTxp4g==,type:str]
sops:
    age:
        - recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T00:45:04Z"
    mac: ENC[AES256_GCM,data:D2V6wehC3ieSLHWsPVlVJtTEeglKDp/X/frdpUUgrPvyjDXAdFjOPrxtAISCUdbo4xUiHHpFpvauNtdyIDOQtRfo2ora0XnnlCiwLs6UIviJNM0/4Z7ba8CHEv+hwK+Ky7Al0xYztz9dChIstzInoD7VDeM4wNrwAzlFUrB4IoQ=,iv:Rg+bmHRagC91J42hPhp6S9ri8IoABF3dy2NeIhKUoes=,tag:7PKqGOLVOtgrwqndy7Dv+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
