apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oauth-policy
  namespace: default
spec:
  # ATTACHMENT: This is how you apply the filter.
  # Option A: Attach to a specific Route (Granular)
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo-oidc

  oidc:
    provider:
      issuer: "https://auth.jonathanrosshart.com/realms/Home" # Or your Keycloak URL
      authorizationEndpoint: "https://auth.jonathanrosshart.com/realms/Home/protocol/openid-connect/auth"
      tokenEndpoint: "https://auth.jonathanrosshart.com/realms/Home/protocol/openid-connect/token"
    clientID: "echo-oidc"
    clientSecret:
      name: oauth-client-secret
    redirectURL: "https://echo-oidc.rnatr.com/myapp/callback" # Must match IdP