apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [] # Empty because we are patching an existing cluster resource
patches:
  - target:
      kind: DaemonSet
      name: intel-gpu-plugin-i915
    patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: unused
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: gpu.intel.com/device-id.0300-9bc8.present
                      operator: In
                      values: ["true"]
                  - matchExpressions:
                    - key: gpu.intel.com/device-id.0300-3e92.present
                      operator: In
                      values: ["true"]