---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish OCI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@8c41d5b56d93d566cab8ae1ddc53580bb0da72c4 # main

      - name: Login to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push OCI Artifact
        run: |
          flux push artifact oci://ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            --path="./kubernetes" \
            --source="${{ github.event.repository.html_url }}" \
            --revision="${{ github.ref_name }}/${{ github.sha }}"
