---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish OCI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push OCI Artifact
        run: |
          flux push artifact oci://ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            --path="./kubernetes" \
            --source="${{ github.event.repository.html_url }}" \
            --revision="${{ github.ref_name }}/${{ github.sha }}"
