---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: comfyui
spec:
  chartRef:
    kind: OCIRepository
    name: comfyui
  interval: 1h
  values:
    controllers:
      comfyui:
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimName: gpu-claim
          securityContext:
            supplementalGroups:
              - 44
              - 992
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          install-custom-nodes:
            image:
              repository: alpine/git
              tag: latest
            command:
              - sh
              - -c
              - |
                #!/bin/sh
                CONFIG_FILE=${CONFIG_FILE:-"/etc/comfyui/plugins.txt"}

                if [ ! -f "$CONFIG_FILE" ]; then
                  echo "Error: Configuration file not found at $CONFIG_FILE"
                  exit 1
                fi

                while read -r repo dest; do
                    # Skip empty lines or lines starting with '#'
                    case "$repo" in
                        ""|\#*) continue ;;
                    esac

                    echo "Processing: $repo -> $dest"

                    if [ -d "$dest/.git" ]; then
                        echo "Updating existing repository at $dest..."
                        cd "$dest" || continue
                        git fetch --all
                        git reset --hard origin/HEAD
                        git clean -fd
                        cd - > /dev/null
                    else
                        echo "Cloning new repository into $dest..."
                        mkdir -p "$dest"
                        git clone "$repo" "$dest"
                    fi
                done < "$CONFIG_FILE"
        containers:
          app:
            image:
              repository: ghcr.io/jhart99/sparkyui
              digest: sha256:e41632b650a42d5966e85d8a2cfc336d2c2785ed14fa83bd12d82f3072c63c24
            env:
              COMFYUI_FLAGS: "--listen 0.0.0.0 --port 8188"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 60
                  periodSeconds: 5
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 4Gi
              limits:
                memory: 16Gi

    defaultPodOptions:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/arch: arm64
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      #   runAsNonRoot: true
      #   fsGroupChangePolicy: OnRootMismatch
      #   seccompProfile:
      #     type: RuntimeDefault

    service:
      app:
        ports:
          http:
            port: 8188

    route:
      app:
        hostnames:
          - "comfyui.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8188

    persistence:
      config:
        existingClaim: comfyui
        globalMounts:
          - path: /opt/ComfyUI/user
      plugin-file:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        globalMounts:
          - path: /etc/comfyui/plugins.txt
            subPath: plugins.txt
      customnodes:
        type: emptyDir
        globalMounts:
          - path: /opt/ComfyUI/custom_nodes
      input:
        type: emptyDir
        globalMounts:
          - path: /opt/ComfyUI/input
      output:
        type: emptyDir
        globalMounts:
          - path: /opt/ComfyUI/output
      models:
        type: nfs
        server: pve.jonathanrosshart.com
        path: /pool/share/fileshare/models
        globalMounts:
          - path: /opt/ComfyUI/models
