apiVersion: v1
kind: Secret
metadata:
    name: comfyui-secret
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:dU5ufVLSX2LhlqVCv4O8UeGB85hHa6TY56nth1DMnSp/pVrQGA==,iv:SPxUD80YWHpp0yh7nHXIBE2FxTytWoUn1LcDApmuQf4=,tag:fUUCA8yxgmnKq8JbWtvGEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUJ0Z2Z0RWE4cXRVbDg0
            T0hQVWx3OWpWVHdVSWdHSzNCekt6dllFRlJJCmYxWnB1bjViZ0tCQXR5OEVSa0di
            STE5L3N1UDd4d2NlL1JQSElEbitDVm8KLS0tIEQ4ZWU3blF5a3ZLRnNBWnBjSjhV
            SDRFQXJsZnhkZFZGd0NOejFmRXZhRjQKxrIH05K9mjeiLsB2cPsnTZP+c8uwkqZd
            7w/A/sDLxTYhykel60vS/dXCOsk9mVLyzT/DH7K13xrb3uewxXA8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T13:55:25Z"
    mac: ENC[AES256_GCM,data:SvVAevfUhCH6ayyvml1Sj/yfNUEMDdqly5XkX2YIJOP65173hvYU8LeVIoI9NOlGooq6IlVOzq/r4u5AXxGil4ak5cORuXDQ5dBiG1Hhj7MeZCuiVYhUhpCxK9Lqms9o/tOPZm/hp4m1CeOP7j00KwTin37pEPv5RyMleac8eyY=,iv:2nIaQFJD7L1di1gL3NM8Z5RIr4NlOyqIcBqtQ2Gz+ls=,tag:wT2Dn3JWBjx+HbowcYuaQA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
