apiVersion: v1
kind: Secret
metadata:
    name: toolhive-s3-secret
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:VTWiv5qjMtz/HfAqr3sXs5/93Ng=,iv:O/1vMB+2lYjbWpqq3fZKGlG4z8i0slfB0f4QhAjliFE=,tag:/CO+79i510R96v0U5/pIkA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:3FW6jPvr8hoTZ4sG8D2sKmYhipETxBwHG0euQF9c2I0xei36Q+mN64VBse6pchGTSinlkGaQwQB82PkqJX6dvg==,iv:1PHjGbOOrW64xNocs/yxQcBoJZWASI2wUkYWVuhh7aA=,tag:cJeIHY1apc4zmut74w+OCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2JvdEhoRitML2E3WVFj
            U0tyWVlabEE4bDdlWFIzbk9nRk9ZQm1HMXlrCnRrM2VyVDFrL2FZekFsL1hwSERn
            WlB3MG8vNzNydFhYa0x2SE9qT1JvZmMKLS0tIHlDSW9aQUZINmRBazNoRHBMTTV4
            clowdTVPa3FuRjBpMG1Ua251MnNzUmMKwSYMVtBw7B+69daX5Hn6k6LKJx0dSBJ8
            2csuyhhO1sEzovjc9IHa1m4RM1dDVabArPvhO09V51f5vB6XQi36Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T12:14:27Z"
    mac: ENC[AES256_GCM,data:+qKS4taTQPsZyhhiXNzNorvmoTazWzziyLPhE9RETs/8aDlcWrepOpHVQrSw2fBZz8dSOCId3pQGLWqj6Vg2JswWlr485vpFZpGT/GBR9+tj4Ug6i01JRztcPjc/8JKieRFPXrWCaqE/WE+e3Y1Llehy/QbMZyNPFm9p53Em+G8=,iv:l1Ymq8B5CW+qfnGNv4iGezx565S6uFsYLNJ2AnlFiwM=,tag:XqxUJWi0q7hpbCdDuXwh1A==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
