apiVersion: v1
kind: Secret
metadata:
    name: toolhive-s3-secret
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:VTWiv5qjMtz/HfAqr3sXs5/93Ng=,iv:O/1vMB+2lYjbWpqq3fZKGlG4z8i0slfB0f4QhAjliFE=,tag:/CO+79i510R96v0U5/pIkA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:sIVE49cl2VykIvcBymIOfvT2NJG5GFmhOk3kx/7g+Dw=,iv:YMxZLoez0TBWjoMfXl7fD3rv2DoDLGCzT/hOxoaDCSg=,tag:GRcO1SX9+nvtxjdvzxsW1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2JvdEhoRitML2E3WVFj
            U0tyWVlabEE4bDdlWFIzbk9nRk9ZQm1HMXlrCnRrM2VyVDFrL2FZekFsL1hwSERn
            WlB3MG8vNzNydFhYa0x2SE9qT1JvZmMKLS0tIHlDSW9aQUZINmRBazNoRHBMTTV4
            clowdTVPa3FuRjBpMG1Ua251MnNzUmMKwSYMVtBw7B+69daX5Hn6k6LKJx0dSBJ8
            2csuyhhO1sEzovjc9IHa1m4RM1dDVabArPvhO09V51f5vB6XQi36Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T12:25:00Z"
    mac: ENC[AES256_GCM,data:GAnjhOiyn4qUMJNI3xiSv3NFn6gKCM4ISDa6s5Obp+8UNRTj7HjE/nQ09LD6P85kVIEUdlQELrSVnJA2fQsYLAiXU/B2bTkJ4skUE4IgQITEuaa5nVV7FqME0rXGsA8qYrNV1NsTBUafnpe0TuLF15cNSkvrU73o/t5yLYrRw5Y=,iv:eVelYCt++QiJZ0Fu7ZUeqShRTuiJno7CzY48as4heCI=,tag:00xGGOljXKQ+p/YmUD/H4w==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
