apiVersion: v1
kind: Secret
metadata:
    name: erecords-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:+sPFtti/rCRW9ICCdmvqr2+HpZCakX2LdqCxgP3uwes=,iv:7ssWEE4aIbTm3RBsBfnLnshPEwHerE+TNrvRyLxmopU=,tag:1gQkVh9kPMWoOb3tTi6IHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlBhUzBQVXhrQW8yeFl0
            NUg3WDltTFEzaUMxaTR0M0k1cll2V1VNRUg0CnZPbVBTWDQ3N1dhdGZGVXFNa2hq
            U2ZCMURaRlpOQStCRGR0Tlg4aWdKYjAKLS0tIGdLWTR5c2tyWEtlb3o2bXZYdnVj
            ZDdIMEtMS2c2ZGU2ZStDNUJiRi8zdEEKNjyFFdX51JcWGficVv3WUklBa5eVdyet
            2Be4lG4VpiqeM1SsTG1Wc4MIvv341EBH901x/4zSjM33UddamPWO6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pec8jh874tjf7uc2asrh6wal9ta6c8sxfvxwy8qrkz76lxjshymsr5fvj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T09:28:51Z"
    mac: ENC[AES256_GCM,data:cAG/07gPNNXB8rn6Vq+dsw0KDARWTo0I152f9ouu2KJrNu7DXIrbpgDfGIzg2O0OUjn3JUq2hQ/Ijf205NuWNi48BGMqeG23dxtmXv3QF/rHl+mtklneB/xLYgKx8IEYoynXiswrW76/k3cgKH7NvYoMVug/yn4KydikJcTNcuI=,iv:YkU7QnHvakoilZO2heYls1/QKv6inQLw5LAoiJNS3IY=,tag:IveGcx0zcOCpPt4x7HaHfg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
